### ISSUE TITLE
Possible buffer overwrite issue in RTSPVideoCapturer::DecoderThread()

### ISSUE THREAD

**Issue by jcarterof** [mpromonet/webrtc-streamer#108]
On line 213 in rtspvideocapturer.cpp, a buffer variable "buf" is allocated with a size equal to the number of bytes in the incoming packet, then those bytes are copied into buf.  This buffer is then used in the initialization of an instance of webrtc::EncodedImage named input_image.  This instance is later passed to the m_decoder->Decode() method which maps to the H264DecoderImpl::Decode() method in the webrtc file src/modules/video_coding/codecs/h264/h264_decoder_impl.cc.  This method uses memset to zero out the 8 padding bytes following the specified data length which results in writing to the 8 bytes following the end of the originally allocated buffer.

All tests on an x64 system have worked flawlessly but all tests on an ARM system have resulted in a segmentation violation.  Correcting the size of the allocation on the line referenced above seems to fix the problem.

**Comment by mpromonet** [comment]
Hi jcarterof,
You are right, buffer need to be allocated adding padding.
I will fix this.
Thanks for reporting this.
Best Regards,
Michel.
