### ISSUE TITLE
Gstreamer / Raspicam Source RTSP Issues

### ISSUE THREAD

**Issue by dherman516** [mpromonet/webrtc-streamer#112]
webrtc-streamer running off a Ubuntu Xenail server (AM64).  When I initialize a RTSP stream  (running of a raspi -- gstreamer / rpicamsrc / gst-rtsp server), I get mmal errors fail to initialize component ENOSPC. 

If I start webrtc-streamer prior to the rtsp server, then it works... Once..

This raspi set up works fine with Janus streaming test and VLC. 

It appears to be something in the way connections are terminated which sets it off. The gstreamer test modules for RTSP recover 100% of the time. So this appears to be a specific issue with rpicamsrc

**Comment by dherman516** [comment]
https://github.com/thaytan/gst-rpicamsrc/issues/74

The issue is that for some reason Live555 was opening up two RTSP connections (which caused a block and a crash of the RTSP server due to the camera being in use).

**Comment by mpromonet** [comment]
Hi,
It open one for video, one for audio, but you can avoid this setting the audio url calling the api /call.
Best Regards,
Michel.

**Comment by dherman516** [comment]
Thanks...
