### ISSUE TITLE
STUN not being honored

### ISSUE THREAD

**Issue by dherman516** [mpromonet/webrtc-streamer#116]
Using a command line for stun and turn (to same address)..   looking at javascript from 

![image](https://user-images.githubusercontent.com/29776679/38513612-c1765e7e-3bfc-11e8-8473-416a3f56bf9e.png)

**Comment by dherman516** [comment]
in main.cpp  the line "if (optarg)"  will never ever trigger so, the optarg is never used

**Comment by mpromonet** [comment]
Hi,
If you refer to line 180, it is trigged when -s have a argument (note that you should not have a space between -s and the argument as it is an parameter that could have an argument or not).
If you try -sdummy, the stunurl will be dummy.
Best Regards,
Michel.

**Comment by dherman516** [comment]
./webrtc-streamer -s 19.86.98.249:3478  rtsp://19.7.95.146:8554/test rtsp://192.168.1.26:8554/wiredCamera

with the logging changes I pushed. Stun server is google's not the specified one

**Comment by mpromonet** [comment]
As I try to explain in my previous comment, you shoule use `-s19.86.98.249:3478` without space.
In your case, -s has no value.

**Comment by dherman516** [comment]
Got it.. turn seems to work with a space though

**Comment by dherman516** [comment]
I am adding to my fork secure stun support.. take a look if interested... only like 10 lines of code changes

**Comment by dherman516** [comment]
I also found that if you set an iptables firewall it confuses the hell out of the stun server
