### ISSUE TITLE
CircleCI  Caching WebRTC and other downloaded components 

### ISSUE THREAD

**Issue by dherman516** [mpromonet/webrtc-streamer#117]
https://circleci.com/docs/2.0/caching/

I think you could save a good 20 minutes in job building by caching the WEBRTC source tree...

**Comment by mpromonet** [comment]
Yes, but WebRTC is updated....

**Comment by dherman516** [comment]
steps:  
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "/depot_tools/README.md" }}   
      - run:
          name: Install Depot Tools
          command: |
              apt-get update
              apt-get install -y --no-install-recommends autoconf automake libtool git make g++ xz-utils
              git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git /depot_tools      
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "/depot_tools/README.md" }}
          paths:
            - "/depot_dools"
      - run: echo 'export PATH=/depot_tools:$PATH' >> $BASH_ENV            
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum "/webrtc/src/PATENTS" }}   
      - run:
          name: Install webrtc Tools
          command: |
              mkdir /webrtc && cd /webrtc 
              fetch --no-history --nohooks webrtc 
              cd ${WEBRTCROOT}
              sed -i -e "s|'src/resources'],|'src/resources'],'condition':'rtc_include_tests==true',|" src/DEPS 
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "/webrtc/src/PATENTS" }}
          paths:
            - "/webrtc"
      - persist_to_workspace:
          root: /
          paths:
            - depot_tools 
            - webrtc

**Comment by dherman516** [comment]
my fork of the project has the new yml.. feel free to tweak it
