### ISSUE TITLE
Web CAM is not working.

### ISSUE THREAD

**Issue by wyounglee** [mpromonet/webrtc-streamer#12]
In my previous Ubuntu, there is no issue for running webrtc-streamer.
However, there is no WebCAM selection in new Ubuntu installation.
I used the same webrtc and webrtc-streamer source and successful compilation.
Also, two log files were exactly same.
Do you have any comment or suggestion?

**Comment by mpromonet** [comment]
Hi,
You should try to run webrtc-streamer with argument `-vvv`, you should have more details why the video device are not enumerated.
Best Regards,
Michel.

**Comment by wyounglee** [comment]
Thanks for updating.
As I mentioned above, two logs (as you described) are exactly same. ^^

**Comment by mpromonet** [comment]
Hi,
If you see the device enumeration with your webcam in the verbose log, the combobox should show it.
You could call /getDeviceList to  get the list of detected device.
Regards,
Michel.

**Comment by franck-talbart** [comment]
Hi,

I can't see my webcam either. /getDeviceList is returning "null".
My webcam is available here:
ls /dev/video0 
/dev/video0

Here is the log. Am I missing something?
[log.txt](https://github.com/mpromonet/webrtc-streamer/files/669155/log.txt)
