### ISSUE TITLE
error while loading shared libraries: libX11.so.6: cannot open shared object file

### ISSUE THREAD

**Issue by choychris** [mpromonet/webrtc-streamer#122]
Hi,

I try to run the latest release in Ubuntu Xenial
But this error occurred: 
./webrtc-streamer: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory. 
Any hints of fixing it?

**Comment by mpromonet** [comment]
Hi Chris,
The latest release use X11 to capture destop, you need to install libgtk-3.
Best Regards,
Michel.

**Comment by choychris** [comment]
Hi,
Thank you! It solves the issue. Closing the issue now.
Best regards,
Chris
