### ISSUE TITLE
stuck while building webrtc on raspberry board

### ISSUE THREAD

**Issue by aby03** [mpromonet/webrtc-streamer#129]
when i run command

gn gen out/Release --args='is_debug=false use_custom_libcxx=false rtc_use_h264=true ffmpeg_branding="Chrome" rtc_include_tests=false use_ozone=true rtc_include_pulse_audio=false'

on raspberry pi, i get stuck on syncing projects 5% everytime i run it

**Comment by mpromonet** [comment]
Hi aby03,
I don't think webrtc could be build on the raspberry board, you should cross-compile for it.
Best Regards,
Michel.
