### ISSUE TITLE
cannot stream local url

### ISSUE THREAD

**Issue by ashishmac7** [mpromonet/webrtc-streamer#140]
hello,
I have rtsp camera and I have install this code from docker . I have tried all url which is provided in example and all works fine but i can not stream my local url.and i have checked my local url from vlc and it works fine. following is code which i used for streaming.

```
<body>
  <video id="video" width="400" controls></video>
</body>

<script>
  var webRtcServer      = new WebRtcStreamer("video","http://localhost:8000");
    window.onload         = function() { webRtcServer.connect("rtsp://85.255.175.241/h264") }
    window.onbeforeunload = function() { webRtcServer.disconnect() }
</script>
```

**Comment by ashishmac7** [comment]
``<body>
  <video id="video" width="400" controls></video>
</body>

<script>
  var webRtcServer      = new WebRtcStreamer("video","http://localhost:8000");
    window.onload         = function() { webRtcServer.connect("rtsp://85.255.175.241/h264") }
    window.onbeforeunload = function() { webRtcServer.disconnect() }
</script>

**Comment by mpromonet** [comment]
Hi ashishmac7,
Did you try to enable log adding `-v` or `-vv` running the docker to look to the output of webrtc-streamer
or enabling using http API  `/api/log?level=2` ?
Maybe this could give some indication ?
Best Regards,
Michel.

**Comment by mpromonet** [comment]
Hi,
I guess this is because you are using UDP, did you tried 
`webRtcServer.connect("rtsp://85.255.175.241/h264","none","rtptransport=tcp")`
Best Regards,
Michel.

**Comment by ashishmac7** [comment]
hi,
now i can stream by adding rtptransport=tcp.
thank you so much
