### ISSUE TITLE
the webrtc-streamer Storage video ？

### ISSUE THREAD

**Issue by jinglings** [mpromonet/webrtc-streamer#143]
hi there,
  the webrtc-streamer support Storage video ? if surppoted,how to do?

**Comment by mpromonet** [comment]
Hi jinglings,
It is not really clear what do you mean, reading video from DVD or some cloud storage ?
Regards,
Michel.

**Comment by jinglings** [comment]
hi mpromonet
 i want to  backup the video ,i dont kown how backup video？

**Comment by Rakiah** [comment]
You may want to use Shinobi as it is open source and probably more suited for what you want @jinglings

**Comment by mpromonet** [comment]
duplicate #45
