### ISSUE TITLE
Build on debian 8 (jessie) failed

### ISSUE THREAD

**Issue by MaxIasat** [mpromonet/webrtc-streamer#144]
What steps will reproduce the problem?
1. Install debian 8 (jessie) in the virtual machine from scratch
2. Install git and depot_tools
3. mkdir webrtc
4. cd webrtc
5. fetch --nohooks webrtc
6. gclient sync
7. cd src
8. ./build/install-build-deps.sh --no-arm
9. gn gen out/Release --args='is_debug=false use_custom_libcxx=false use_custom_libcxx_for_host=true rtc_use_h264=true ffmpeg_branding="Chrome" rtc_include_tests=false rtc_include_pulse_audio=false use_sysroot=false is_clang=false treat_warnings_as_errors=false'
10. ninja -C out/Release
11. Build successfull
12. cd ..
13. cd ..
14. git clone https://github.com/mpromonet/webrtc-streamer.git
15. cd webrtc-streamer
16. sudo make live555
17. make
18. Build failed with following message:

g++ -o src/HttpServerRequestHandler.o -c src/HttpServerRequestHandler.cpp -Wall -pthread -g -std=c++11 -Iinc  --sysroot=/  -DWEBRTC_POSIX -fno-rtti -DHAVE_JPEG -I /home/maxim/git/webrtc-streamer/../webrtc/src -I /home/maxim/git/webrtc-streamer/../webrtc/src/third_party/jsoncpp/source/include -I /home/maxim/git/webrtc-streamer/../webrtc/src/third_party/libyuv/include  -I /home/maxim/git/webrtc-streamer/../webrtc/src/third_party/abseil-cpp -DNDEBUG=1 -DUSE_X11 -DHAVE_ALSA -I //usr/include -DHAVE_LIVE555 -I live555helper/inc -I //usr/include/liveMedia  -I //usr/include/groupsock -I //usr/include/UsageEnvironment -I //usr/include/BasicUsageEnvironment/ -I civetweb/include -DVERSION="\"v0.0.11-66-g83ada67 webrtc@2402154 live555helper@4472593 civetweb@v1.10-357-g3ebb61e\""
g++ -o src/main.o -c src/main.cpp -Wall -pthread -g -std=c++11 -Iinc  --sysroot=/  -DWEBRTC_POSIX -fno-rtti -DHAVE_JPEG -I /home/maxim/git/webrtc-streamer/../webrtc/src -I /home/maxim/git/webrtc-streamer/../webrtc/src/third_party/jsoncpp/source/include -I /home/maxim/git/webrtc-streamer/../webrtc/src/third_party/libyuv/include  -I /home/maxim/git/webrtc-streamer/../webrtc/src/third_party/abseil-cpp -DNDEBUG=1 -DUSE_X11 -DHAVE_ALSA -I //usr/include -DHAVE_LIVE555 -I live555helper/inc -I //usr/include/liveMedia  -I //usr/include/groupsock -I //usr/include/UsageEnvironment -I //usr/include/BasicUsageEnvironment/ -I civetweb/include -DVERSION="\"v0.0.11-66-g83ada67 webrtc@2402154 live555helper@4472593 civetweb@v1.10-357-g3ebb61e\""
g++ -o webrtc-streamer src/rtspaudiocapturer.o src/PeerConnectionManager.o src/rtspvideocapturer.o src/HttpServerRequestHandler.o src/main.o libWebRTC__Release.a live555helper/live555helper.a civetweb/libcivetweb.a -pthread  --sysroot=/ -ldl -lrt  -lX11 -lXext -lXdamage -lXfixes -lXcomposite  -L //usr/lib -lasound live555helper/live555helper.a -L //usr/lib -l:libliveMedia.a -l:libgroupsock.a -l:libUsageEnvironment.a -l:libBasicUsageEnvironment.a  -L civetweb -l civetweb
/usr/bin/ld: libWebRTC__Release.a(logging.o): unrecognized relocation (0x2a) in section `.text._ZN3rtc10LogMessage13OutputToDebugERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS_15LoggingSeverityE.part.60'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:98: recipe for target 'webrtc-streamer' failed
make: *** [webrtc-streamer] Error 1

Remark:
On debian 9 all build steps work successfully!

Please help me to find out the righ configuration and to build webrtc-streamer properly.

Thank you and best regards

**Comment by mpromonet** [comment]
Hi MaxIasat,

Did you try removing the option "use_custom_libcxx_for_host=true" ?

Best Regards,
Michel.
