### ISSUE TITLE
Streaming does not work over NAT port forwarding or over nginx proxy pass

### ISSUE THREAD

**Issue by unrelatedlabs** [mpromonet/webrtc-streamer#148]
I'm trying to access the stream from outside of my home network and can't get it working. Nether with port forwarding (webpage loads, but video does not load) nor nginx reverse proxy.

**Comment by mpromonet** [comment]
Hi unrelatedlabs,
Strange I just check and it seems working without problems.
Maybe your LAN is not able to reach the google STUN server stun.l.google.com:19302 ?
Did you tried to enable the log to see what is going on ?
Best Regards,
Michel.
