### ISSUE TITLE
Add Audio in addition to video in webrtc-streamer

### ISSUE THREAD

**Issue by saket424** [mpromonet/webrtc-streamer#15]
Michel,
Can you comment on the feasibility of adding audio

**Comment by mpromonet** [comment]
Hi Saket424,
It is probably feasible, but I did not investigate on this direction.
Are you speaking about ALSA capture ?
Best Regards,
Michel.

**Comment by saket424** [comment]
Yes either alsa capture or pulseaudio for linux from the webrtc codebase

src/webrtc/modules/audio_device/linux/

More often than not, viewing only video without the associated audio stream is boring and incomplete.

**Comment by saket424** [comment]
Michel,
This awesome. I confirm that the audio constraint is working after the 	b8606e1 pull !!
Thanks
