### ISSUE TITLE
MS Edge InvalidAccessError

### ISSUE THREAD

**Issue by lthrhx** [mpromonet/webrtc-streamer#154]
Running webrtc-streamer release 0.1.0 on Ubuntu 18.0.4.1
Firefox 62 and Chrome 67 work great.
MS Edge 42.17134.1.0 and IE 11 do not.

Running webrtc like this: 
`./webrtc-streamer -H 172.16.0.135:8000 rtsp://172.16.5.16
`

Using this link as it seems to be pretty stripped down:
`172.16.0.135:8000/webrtcstreamer.html?video=rtsp://172.16.5.16&audio=undefined&options=rtptransport=tcp&timeout=60
`

The HTML loads, but the video does not. However the server does show a client connected and is pushing video its way even though nothing is displayed. The servers stops sending data as soon as the browser window is closed.

Screenshot of MS Edge error:
![ms edge error](https://user-images.githubusercontent.com/32741474/46433370-b128fd80-c71e-11e8-9f25-1780424620bf.PNG)

Server console log files, one for an MS Edge connection and one for Firefox:

[log of Firefox.txt](https://github.com/mpromonet/webrtc-streamer/files/2443513/log.of.Firefox.txt)
[log of MS Edge.txt](https://github.com/mpromonet/webrtc-streamer/files/2443514/log.of.MS.Edge.txt)

**Comment by mpromonet** [comment]
Hi lthrhx,
I nearly never use Edge, however you are right this is easy to reproduce, it appends processing setRemoteDescription.
It seems the SDP is not supported by Edge, maybe some options need to add in the server side.
Best Regards,
Michel.
