### ISSUE TITLE
Does this support RTMP Streams?

### ISSUE THREAD

**Issue by abhijitnathwani** [mpromonet/webrtc-streamer#155]
Hi @mpromonet 

Thanks for this wonderful project. I was able to setup RTSP Streams with Jitsi Conference. Is there any way to include RTMP streams as well?

Thanks,
Abhijit Nathwani

**Comment by mpromonet** [comment]
Hi Abhijit,

In order to connect an RTMP stream, you need to implement a VideoCapturer that support RMTP.
Maybe you can inspired from the [RTSPVideoCapturer](https://github.com/mpromonet/webrtc-streamer/blob/master/src/rtspvideocapturer.cpp)

Best Regards,
Michel.

**Comment by mpromonet** [comment]
Hi Tejas,

You are right liv555 doesnot support rmtp, you should find a library that implement an rmtp client.
Probably there is such a things in ffmpeg, vlc or ...

Best Regards,
Michel

**Comment by digger18** [comment]
I am interested in RTMP support as well.

**Comment by mpromonet** [comment]
Hi @digger18 

Feel free to submit pull request that implement RTMP.

Best Regards,

Michel.
