### ISSUE TITLE
Compile for aarch64

### ISSUE THREAD

**Issue by Man777** [mpromonet/webrtc-streamer#157]
./webrtc/src/media/base/mediachannel.h:71: Warnung: undefinierter Verweis auf »rtc::ToString[abi:cxx11](int)«
collect2: error: ld returned 1 exit status
Makefile:98: recipe for target 'webrtc-streamer' failed
make: *** [webrtc-streamer] Error 1

Any Idea why I get at the end the linker problem for Cxx11? I read the last issues, it should be fixed. But its still exist the problem.

**Comment by Man777** [comment]
Got now worked out. For x64 and aarch64 Plattform. I missed to disable the custom libcxx. 
But for other who will tries. Follow the comand down. 
This combination work for camera capture, which build in with the prozessor. 
gcc version 7.3.0 (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04)

For ARM64 Architecutre, Linux

git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
export PATH=$PATH:$(pwd)/depot_tools
mkdir webrtc
pushd webrtc or cd webrtc
GYP_DEFINES="target_arch=arm64" fetch --no-history webrtc
gclient sync
cd src
./build/install-build-deb.sh
build/linux/sysroot_scripts/install-sysroot.py --arch=arm64
gn gen out/arm64 --args='dcheck_always_on=true ffmpeg_branding="Chrome" is_component_build=false is_debug=false rtc_use_h264=true rtc_include_tests=false use_custom_libcxx=false rtc_include_pulse_audio=false target_cpu="arm64"'
ninja -C out/arm64

sudo apt-get install gcc-aarch64-linux-gnu 
webrtc-streamer
cd webrtc-streamer
gedit Makefile -> change it WEBRTCBUILD: arm64
make CROSS=aarch64-linux-gnu- SYSROOT=/home/../webrtc/src/build/linux/debian_sid_arm64-sysroot live555
make CROSS=aarch64-linux-gnu- SYSROOT=/home/../webrtc/src/build/linux/debian_sid_arm64-sysroot tgz
->If sometimes stuck7stop, correct the Makefile, which the source is not founding. 
In my case was running the whole comile at once. Only a link error accour. But forget to disable the custom standard c++ lib.

**Comment by Jishang** [comment]
> Got now worked out. For x64 and aarch64 Plattform. I missed to disable the custom libcxx.
> But for other who will tries. Follow the comand down.
> This combination work for camera capture, which build in with the prozessor.
> gcc version 7.3.0 (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04)
> 
> For ARM64 Architecutre, Linux
> 
> git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
> export PATH=$PATH:$(pwd)/depot_tools
> mkdir webrtc
> pushd webrtc or cd webrtc
> GYP_DEFINES="target_arch=arm64" fetch --no-history webrtc
> gclient sync
> cd src
> ./build/install-build-deb.sh
> build/linux/sysroot_scripts/install-sysroot.py --arch=arm64
> gn gen out/arm64 --args='dcheck_always_on=true ffmpeg_branding="Chrome" is_component_build=false is_debug=false rtc_use_h264=true rtc_include_tests=false use_custom_libcxx=false rtc_include_pulse_audio=false target_cpu="arm64"'
> ninja -C out/arm64
> 
> sudo apt-get install gcc-aarch64-linux-gnu
> webrtc-streamer
> cd webrtc-streamer
> gedit Makefile -> change it WEBRTCBUILD: arm64
> make CROSS=aarch64-linux-gnu- SYSROOT=/home/../webrtc/src/build/linux/debian_sid_arm64-sysroot live555
> make CROSS=aarch64-linux-gnu- SYSROOT=/home/../webrtc/src/build/linux/debian_sid_arm64-sysroot tgz
> ->If sometimes stuck7stop, correct the Makefile, which the source is not founding.
> In my case was running the whole comile at once. Only a link error accour. But forget to disable the custom standard c++ lib.

I am doing the same procedure describe above still getting unknown error.
root/usr/lib -l:libliveMedia.a -l:libgroupsock.a -l:libUsageEnvironment.a -l:libBasicUsageEnvironment.a  -L civetweb -l civetweb

libwebrtc__arm64.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
Makefile:97: recipe for target 'webrtc-streamer' failed
make: *** [webrtc-streamer] Error 1

If you have compiled or release version of that can you please provide me i want to check for my camera?
GCC version:gcc-linaro-5.5.0-2017.10-x86_64_aarch64-linux-gnu

**Comment by lukelu0520** [comment]
There is no ./build/install-build-deb.sh, but ./build/install-build-deps.sh
Is it a typo ?
