### ISSUE TITLE
Support for Firefox for Jitsi Meet Connection

### ISSUE THREAD

**Issue by abhijitnathwani** [mpromonet/webrtc-streamer#158]
Hi @mpromonet ,

I have noticed the Jitsi Room connection does not work on the Firefox browser. Initially I thought it is the CORS issue as per console log. I have added the necessary headers in the `nginx` config and things work fine on Chrome. Do you have any clue as to how to fix this for Firefox?

![console_log_cors_firefox](https://user-images.githubusercontent.com/5513984/46658552-9ba94d00-cbd0-11e8-8921-b518c27b7a9a.PNG)

**Comment by antonsimola** [comment]
Did you manage to get this to work? I'm having some issues with CORS as well.

**Comment by abhijitnathwani** [comment]
Hi @antonsimola ,

Nope, I still haven't managed to get this working. Let me know if you can get this worked.

Abhijit

**Comment by mpromonet** [comment]
Hi,
Usually I use https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi extensin to disable CORS checking.
Best Regards,
Michel

**Comment by abhijitnathwani** [comment]
Hi,

Things work well on Chrome, after using this extension or adding the CORS checking in server config. It is Firefox that is creating the problem.

Abhijit
