### ISSUE TITLE
Unable to stream multiple rtsp stream on same jitsi conference

### ISSUE THREAD

**Issue by bhattdhruvin** [mpromonet/webrtc-streamer#161]
Hello,
I appreciate the great work, and it is helping me like a charm. Reduced a lot of coding work for me!!
Recently, I'm trying to create rtsp streaming as a conference member in jitsi, and this streamer has helped me solve it efficiently.
But, I am unable to stream multiple rtsp streams on a single jitsi conference.
I tried using webrtc-streamer's one server for both streams as well as two different servers for two streams.
A single server works fine when streaming two streams on two conferences independently, but it does not work in single conference.
I tried looking at some logs, and I think that the webrtc-streamer streams the rtsp url to a static named component named "rtsp". Thus, whenever I try to stream it on Jitsi, the log says 

`<video muted="true" autoplay id="remoteVideo_rtsp" style=""></video>`

on every other users, the same value differs even for a user from same system trying multiple times.

`autoplay id = remoteVideo_<variable data string>`

Please help me solve this, as this might be a possible conflict.

Thanks a lot.

**Comment by xchander007** [comment]
Hi, can you please help me how can i create use an external rtsp stream from IP Camera within Jitsi ?
