### ISSUE TITLE
Continuous increase in delay

### ISSUE THREAD

**Issue by cpena** [mpromonet/webrtc-streamer#167]
Hello!,

I've been testing the streamer from a Raspberry Pi 3+ (armv7l), it works fine, but after several minutes watching the video the delay is accumulated, passing less than a second to minutes.

I am testing it in the local network, connecting the camera (Dalhua PTZ) by cable with the RPi and connecting with my laptop via wifi to see the webrtc stream.

Will there be any solution for this?

Greetings and thanks!

**Comment by mpromonet** [comment]
Hi Christian,

This was discuss in #137 I implement a kind of very simple dejittering buffer that add delay to reduce jiterring. I will probably put this conditionnal and rework on it. 
You can remove the code  in rtspvideocapturer.cpp

	if (prevts != 0) {
		int64_t periodSource = decodedImage.timestamp() - previmagets;
		int64_t periodDecode = ts-prevts;
			
		RTC_LOG(LS_VERBOSE) << "RTSPVideoCapturer::Decoded interframe decode:" << periodDecode << " source:" << periodSource;
		int64_t delayms = periodSource-periodDecode;
		if ( (delayms > 0) && (delayms < 1000) ) {
			usleep(delayms*1000);
		}
	}

Best Regards,

Michel.
