### ISSUE TITLE
CMake build does not work

### ISSUE THREAD

**Issue by kdkeyser** [mpromonet/webrtc-streamer#168]
I tried the instructions to build webrtc-streamer using cmake on Linux, but these seem to fail at link time, due to missing webrtc libraries. My guess is that line 83:
`FILE(GLOB_RECURSE WEBRTCEXTRAOBJS {WEBRTCOBJS}/*${CMAKE_C_OUTPUT_EXTENSION})`
results in an empty "WEBRTCEXTRAOBJS", because at the time you run cmake, the webrtc libraries have not yet been build, so the "out" directory is still empty.

If I manually run the `gn gen` and `ninja` commands in the webrtc directory before I run cmake, the build does succeed.

**Comment by mpromonet** [comment]
Hi Koen,

Maybe the cmake was interrupt.

webrtc build is trigged when ${WEBRTCROOT}/out/${WEBRTCBUILD}/args.gn doesnot exists, it then create it and run `gn gen`and `ninja`.

So if you ran cmake, break during the webrtc build, you need to cleanup the args.gn or the whole webrtc build directory before restart `cmake` 
The other solution is what you did, building webrtc.

Best Regards,
Michel.
