### ISSUE TITLE
Link Error "undefined reference to Json::Value:***"

### ISSUE THREAD

**Issue by msedv** [mpromonet/webrtc-streamer#179]
After some tweaks I managed to compile webrtc-streamer, but when linking I get a whole bunch of errors like this:

`[100%] Linking CXX executable webrtc-streamer

HttpServerRequestHandler.cpp:(.text+0x1aac): undefined reference to `Json::Value::Value(Json::ValueType)'
HttpServerRequestHandler.cpp:(.text+0x1b9e): undefined reference to `Json::Value::Value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
HttpServerRequestHandler.cpp:(.text+0x1bab): undefined reference to `Json::Value::append(Json::Value const&)'
HttpServerRequestHandler.cpp:(.text+0x1bb3): undefined reference to `Json::Value::~Value()'
HttpServerRequestHandler.cpp:(.text+0x1c99): undefined reference to `Json::Value::~Value()'
HttpServerRequestHandler.cpp:(.text+0x1cac): undefined reference to `Json::Value::~Value()'

PeerConnectionManager.cpp:(.text+0xf6): undefined reference to `Json::Value::Value(Json::ValueType)'
PeerConnectionManager.cpp:(.text+0x11b): undefined reference to `Json::Value::Value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
PeerConnectionManager.cpp:(.text+0x12a): undefined reference to `Json::Value::operator[](char const*)'
PeerConnectionManager.cpp:(.text+0x135): undefined reference to `Json::Value::operator=(Json::Value const&)'
PeerConnectionManager.cpp:(.text+0x141): undefined reference to `Json::Value::~Value()'
PeerConnectionManager.cpp:(.text+0x16c): undefined reference to `Json::Value::Value(int)'
PeerConnectionManager.cpp:(.text+0x17b): undefined reference to `Json::Value::operator[](char const*)'
PeerConnectionManager.cpp:(.text+0x186): undefined reference to `Json::Value::operator=(Json::Value const&)'
PeerConnectionManager.cpp:(.text+0x193): undefined reference to `Json::Value::~Value()'
`

Any idea what I'm doing wrong? Tnx!

Markus

**Comment by mpromonet** [comment]
Hi Markus,

I see 2 classic possibilities either you didnot build ninja `jsoncpp` target or you build webrtc option `use_custom_libcxx=false` 

Best Regards,
Michel.

**Comment by msedv** [comment]
Hi Michel,

thank you for your response, but none of my experiments in this direction worked. But let me ask from another ppoint of view: which Linux would you recommend me to install a complete build chain for webrtc-streamer running on a 64bit Linux - and is there eventually a more detailed instruction than the one in README.md?

Thank you!

Markus

**Comment by mpromonet** [comment]
Hi Markus,

Then you should look like to symbols defined in the webrtc libraries, using nm and c++filt.
Using make `VERBOSE=1` could help also to get the link command.
The build on circleci use heroku:16 and appveyor use ubuntu 18.04.

Best Regards,
Michel.
