### ISSUE TITLE
WebRTC over LAN without STUN/TURN

### ISSUE THREAD

**Issue by digger18** [mpromonet/webrtc-streamer#185]
My enviornment has no internet access, how can I configure or modify webrtc-streamer to work over LAN without the need for STUN/TURN (without NAT traversal)?

Thanks!

**Comment by mpromonet** [comment]
Hi,
Using the option -S it start an embeded STUN server that Will bé used by the JavaScript side.
This should allow to connect webrtc stream without using internet STUN server.
Best regards
Michel

**Comment by digger18** [comment]
Thanks, I ended up using Coturn as a relay (TURN only server).
