### ISSUE TITLE
 compilation terminated, which commit should checkout for webrtc ?

### ISSUE THREAD

**Issue by codezealot** [mpromonet/webrtc-streamer#188]
webrtc-streamer/inc/CapturerFactory.h:15:53: fatal error: media/engine/webrtcvideocapturerfactory.h: No such file or directory
compilation terminated.
CMakeFiles/webrtc-streamer.dir/build.make:182: recipe for target 'CMakeFiles/webrtc-streamer.dir/src/PeerConnectionManager.cpp.o' failed
make[2]: *** [CMakeFiles/webrtc-streamer.dir/src/PeerConnectionManager.cpp.o] Error 1
CMakeFiles/Makefile2:143: recipe for target 'CMakeFiles/webrtc-streamer.dir/all' failed
make[1]: *** [CMakeFiles/webrtc-streamer.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mpromonet** [comment]
HI codezealot,
I follow the master branch, but it seems WebRtcVideoDeviceCapturerFactory as been remove.
You can get the commit used by the latest build from https://webrtc-streamer.herokuapp.com/api/version that is now e121eb9f47
Depending on what you want to do, you can keep using latest and comment the include file and remove the capture stuff.
Best Regards,
Michel.
