### ISSUE TITLE
Change max frame rate

### ISSUE THREAD

**Issue by 0xbadc0de** [mpromonet/webrtc-streamer#194]
Hello! I'm using webrtc-streamer on linux to serve RTSP stream (about 60fps camera). Streaming is pretty smooth but CPU load is very high (Core i7 4770). I've read that i can change constraints of maxFrameRate but there is no example how i can do that. Is there example settings constraints? Or i can reduce frame rate in encoder?
This is how use library:
```javascript
var webRtcServer = new WebRtcStreamer('video',location.protocol+"//"+window.location.hostname+":8000");
window.onload = function() {
    webRtcServer.connect('ADDRESS_HERE');
};
window.onbeforeunload = function() {
    webRtcServer.disconnect()
}

**Comment by mpromonet** [comment]
Hi Alex,

You're right I should add more information in the README.

The [WebRtcStreamer](http://htmlpreview.github.io/?https://github.com/mpromonet/webrtc-streamer-html/blob/master/jsdoc/WebRtcStreamer.html) accept a parameter to give options to the WebRTC stream : 
 
         connect(videourl, audiourl, options, streamurl)
options is in format key=value&...
By now, for all kind of webrtcstream there is : 

 * bitrate : to set the target min_bitrate_bps  is set to bitrate/2 and max_bitrate_bps  to bitrate*2
 * minWidth, maxWidth
 * minHeight, maxHeight
 * minFrameRate, maxFrameRate

For RTSP there is additionnal arg to resize the input stream:
  * width and height

All of this is quite experimental and need improvement. In particular the containts give to the WebRTC SDK are not so easy to understand, this is why there is a feature in the project to resize it.
This is convinient when displaying 3x3 or more videos.

Best Regards,
Michel.

**Comment by mpromonet** [comment]
Hi,
The options minWidth, maxWidth, minHeight, maxHeight, minFrameRate, maxFrameRate  have been removed from WebRTC.   
So I removed this from this project in commit https://github.com/mpromonet/webrtc-streamer/commit/a700de020efad722b9c97483b5c2f15f6aea4a57#diff-ec938a9c4aa505f34fea8b8a3d7fd6f9
