### ISSUE TITLE
using another HTTP server

### ISSUE THREAD

**Issue by neucoreAn** [mpromonet/webrtc-streamer#208]
If civet web is replaced by an external nginx server, must the internal civet web be removed and the code for interface calls be added?

**Comment by mpromonet** [comment]
Hi neucoreAn,
ciwebweb is used to process the WebRTC signaling stuff, if you remove it you will need an other way to get offer/answer/candidate.
Best Regards,
Michel.

**Comment by neucoreAn** [comment]
Thank you for your reply.
This web server has the function of signaling server. I just need to add the function of signaling exchange in webrtc-streamer, right?

**Comment by mpromonet** [comment]
WebRTC doesnot implement signaling (and doesnot normalize it), in webrtc-streamer, the signaling is implemented using civetweb.
