### ISSUE TITLE
H264 transmission, too high CPU usage

### ISSUE THREAD

**Issue by neucoreAn** [mpromonet/webrtc-streamer#209]
Running on ARM, the CPU takes up 70% of the total. It converts H264 into webrtc. Now can we directly transmit H264  data?

**Comment by mpromonet** [comment]
Hi neucoreAn,
This question was often asked, actually the WebRTC SDK seems to need I420 frames, but maybe you could try to feed the  `rtc::VideoBroadcaster` with an H264 frame ? or modify the WebRTC SDK to process H264 frames.
An project that forward RTP packet without uncompression/compresion is [janus-gateway](https://github.com/meetecho/janus-gateway)
Best Regards,
Michel.

**Comment by neucoreAn** [comment]
Thank you very much.
