### ISSUE TITLE
A question about the code

### ISSUE THREAD

**Issue by DuanJieDong** [mpromonet/webrtc-streamer#219]
hi mpromonet 
I have a question I want to ask you  about the code.
code:
【class RTSPVideoCapturer : public rtc::VideoSourceInterface<webrtc::VideoFrame>, public               RTSPConnection::Callback, public rtc::Thread ,public webrtc::DecodedImageCallback】

why the class RTSPVideoCapturer need inherit rtc::Thread? 
the thread used in this class is std::thread, So I don't understand.
Could you tell me what you think?
thanks!

**Comment by mpromonet** [comment]
Hi DuanJieDong,
There is 2 threads in the class, the rtc::Thread one run the live555 mainloop, and the std::thread one that decode the frames.
Best Regards,
Michel.
