### ISSUE TITLE
failed to create answer

### ISSUE THREAD

**Issue by neucoreAn** [mpromonet/webrtc-streamer#224]
After receiving the offer, webrtc-streamer calls the call function, which generates the answer failure. 

The offer from HTML within webrtc-streamer can successfully create a response within the call function. Receiving an offer from peerconnection_client and creating a reply in the call function fails. Do you have any special settings for offers in webrtc-streamer?

**Comment by mpromonet** [comment]
Hi neucoreAn,

Maybe you should look to the logs of from the server and from the browser ?

Best Regards,

Michel.
