### ISSUE TITLE
No video on janus videoroom

### ISSUE THREAD

**Issue by tartavull** [mpromonet/webrtc-streamer#225]
https://imgur.com/a/nbELSPk

When using http://local-rpi-ip8000/janusvideoroom.html 
t seems to connect correctly and the command line sees to show some streaming,
but no image is shown
```
[674:472] [3254] (bitrate_allocator.cc:111): Current BWE 597760
[678:517] [3271] (quality_scaler.cc:201): Checking average QP 2 (2).
[679:662] [3254] (bitrate_allocator.cc:111): Current BWE 597760
[684:247] [3271] (video_stream_encoder.cc:743): Number of frames: captured 61, dropped (due to encoder blocked) 0, interval_ms 60000
```

http://local-rpi-ip8000/index.html works just fine

http://192.168.2.27:8000/janustest.html doesn't display any video but shows
```
pi2 joining
media joining
pi2 joined
media joined
pi2 publishing
media publishing
media up
pi2 up
```

I'm using the latest release
```
"v0.1.1-dirty webrtc@b3033c448f-dirty live555helper@de09337 civetweb@v1.10-357-g3ebb61e3"
```

Thanks for the help :)

**Comment by mpromonet** [comment]
Hi tartavull,
The janustest.html is just a test to publish webrtc streams to janus gateway, it doesnot display video.
You can modify it to ask to publish your stream, maybe with something like : 
`janus.join(janusRoomConfig.roomId, "mmal service 16.1","video");`
An other way could be to use the nodejs script [joinjanusvideoroom.js](https://raw.githubusercontent.com/mpromonet/webrtc-streamer/master/joinjanusvideoroom.js)
Best Regards,
Michel.
