### ISSUE TITLE
mpromonet/webrtc-streamer:latest-arm32v6 doesn't work on raspberry pi zero

### ISSUE THREAD

**Issue by blademckain** [mpromonet/webrtc-streamer#236]
**Describe the bug**
mpromonet/webrtc-streamer:latest-arm32v6 doesn't work on raspberry pi zero

**To Reproduce**
docker run -d -p 8000:8000 --device=/dev/video0 -it --restart always --name webrtc-streamer mpromonet/webrtc-streamer:latest-arm32v6

the container is still in restarting and the log says:

docker logs --tail 50 --follow --timestamps webrtc-streamer
2019-05-06T19:32:08.070639810Z ./webrtc-streamer: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by ./webrtc-streamer)
2019-05-06T19:32:13.545354713Z ./webrtc-streamer: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by ./webrtc-streamer)

raspbian actually use 2.24 libgc

ldd --version
ldd (Debian GLIBC 2.24-11+deb9u4) 2.24
Copyright (C) 2016 Free Software Foundation, Inc.
Questo è software libero; si veda il sorgente per le condizioni di copiatura.
NON c'è alcuna garanzia; neppure di COMMERCIABILITÀ o IDONEITÀ AD UN
PARTICOLARE SCOPO.
Scritto da Roland McGrath e Ulrich Drepper.

**Comment by mpromonet** [comment]
Hi blademckain,
Yes, this is a problem WebRTC is not compiling with https://github.com/raspberrypi/tools, and crossbuild-essential-armhf use a too recent glibc.
Best Regards,
Michel.

**Comment by mpromonet** [comment]
Hi @blademckain,

Using https://sourceforge.net/projects/raspberry-pi-cross-compilers/, it is possible to build docker for raspberry zero/B.
Starting from 29f01ca41ec8a40ac5dbc2473c5a2993fe6b4eea, the armv6 image is running again.

Best Regards,
Michel.
