### ISSUE TITLE
rdp timestamp overflow error

### ISSUE THREAD

**Issue by MichaelKorn** [mpromonet/webrtc-streamer#237]
Now, we should be able to resolve https://github.com/mpromonet/webrtc-streamer/blob/master/src/rtspvideocapturer.cpp#L279 by using ntp_time_ms_.

Also see: #187 
Resolved webRTC Bug: https://bugs.chromium.org/p/webrtc/issues/detail?id=10303
Change in VideoFrame: https://webrtc-review.googlesource.com/c/src/+/136807/2/modules/video_coding/codecs/h264/h264_decoder_impl.cc

**Comment by MichaelKorn** [comment]
@mpromonet I would only remove L278, L279 and L280. I just tested it and it seems to be alright. Where's the catch, can it really be that easy??

**Comment by mpromonet** [comment]
Hi Michael,
Thanks for your contribution, I will merged this.
My Hack storing in timestamp was only because the field was lost by decoding.
Best Regards,
Michel.
