### ISSUE TITLE
Missing support for TURN relay

### ISSUE THREAD

**Issue by 9a4gl** [mpromonet/webrtc-streamer#24]
I will create a patch and send you as I already have that implemented locally

**Comment by 9a4gl** [comment]
[0001-Add-support-for-TURN-relay.patch.txt](https://github.com/mpromonet/webrtc-streamer/files/887812/0001-Add-support-for-TURN-relay.patch.txt)

Please review and merge upstream if you agree with change.

**Comment by mpromonet** [comment]
Hi,
Thanks, it is more convenient to submit modifications as a pull request.
Regards
Michel.

**Comment by 9a4gl** [comment]
I would do that, but I cannot push. I am new at github, do you need to allow me to push on your repo or ? Help me and I will do that :)

**Comment by mpromonet** [comment]
Hi,
The standard way to process with GitHub  is to fork my repo, push the modification to your forked repo and submit a pull request to my repo.
Then it is easy to see the difference and accept the pull request.
Best Regards,
Michel.

**Comment by 9a4gl** [comment]
Thanks, forking sounded to me like expensive operation that should be used if I want to split from your project. Ok, thanks.
