### ISSUE TITLE
Unable to play RTSP stream from HDMI encoder(rtsp server)

### ISSUE THREAD

**Issue by arunselvam82** [mpromonet/webrtc-streamer#250]
Hi 

I tried playing rtsp stream from HDMI encoder  rtsp server with h264 , i replaced default url in Bunny.html with url from encoder and video is not playing.
I could find the video format is set as wrong height and width then the original , and session is getting closed . i tried understanding the sequence and found before sdp exchange happens codecs is getting initialized. i verified the same by playing the default bunny url in bunny.html and its working by initializing the codecs after receiving sdps from peer.

i verified the rtsp server with live555helperttest and its working fine, only through browser while callig bunny.html its not working.

can you please confirm anything we are missing or its an issue with server.

**Comment by mpromonet** [comment]
Hi,
Maybe the SPS/PPS are not correctly parsed ?
Enabling verbose log, and adding some additionnal logs should helps you to understand if the SPS/PPS are processed correctly.
In the past webrtc::SpsParser::ParseSps was working with too reduce set of SPS, so I used h264bitstream, next I revert to webrtc that manage now more SPS.
If the SPS parsing is wrong you can try with h264bitstream
Best Regards,
Michel.
