### ISSUE TITLE
GLIBCXX_3.4.26 missing dependency for Raspberry pi arm

### ISSUE THREAD

**Issue by janessbach** [mpromonet/webrtc-streamer#258]
hello, thanks for the cool project here. the current latest docker image cannot be started on a raspberry pi model 3. 

stating:
`xxx-webrtc_1  | ./webrtc-streamer: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./webrtc-streamer)
pi_xxx-webrtc_1 exited with code 1`

am I missing something?

**Comment by mpromonet** [comment]
Hi janessbach,
This is folowwing cross-compiler change, I fixed it for armv6l linking statically libstdc++, I will do the same for all linux.
Best Regards,
Michel.

**Comment by janessbach** [comment]
Thanks, issue resolved!
