### ISSUE TITLE
Add release/version to dockerfiles (ENV)

### ISSUE THREAD

**Issue by ohad-orca** [mpromonet/webrtc-streamer#259]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add *_VERSION environment variables to dockerfiles

**Describe alternatives you've considered**
None

**Additional context**
Would be great to have the release/version as environment variables in dockerfiles.
Like:
https://github.com/docker-library/redis/blob/0b2910f292fa6ac32318cb2acc84355b11aa8a7a/5.0/Dockerfile#L42
https://github.com/docker-library/mongo/blob/ebd79727e4e77210272ec55c8b22b17877bfd29a/3.4/Dockerfile#L80

Thanks !

**Comment by mpromonet** [comment]
Hi ohad-orca ,

I don't see what that brings.
You could get the version using the api [/api/version](https://webrtc-streamer.herokuapp.com/api/version) or running with option `-V` like `docker run mpromonet/webrtc-streamer -V`

Best Regards,
Michel.
