### ISSUE TITLE
Use libwebrtc from https://github.com/aisouard/libwebrtc

### ISSUE THREAD

**Issue by 9a4gl** [mpromonet/webrtc-streamer#26]
Guys at https://github.com/aisouard/libwebrtc simplify usage/build of webrtc. And looks they are also close with arm support. Will give a try and report here if we can gain from their work.

**Comment by mpromonet** [comment]
This seems interesting, I will look at that

**Comment by 9a4gl** [comment]
pkg-config --cflags LibWebRTC
-D_GLIBCXX_DEBUG=1 -D_DEBUG=1 -DWEBRTC_POSIX -D_GLIBCXX_USE_CXX11_ABI=0 -std=gnu++0x -pthread -I/usr/local/include  

pkg-config --libs LibWebRTC
-L/usr/local/lib -lwebrtc -lSM -lICE -lX11 -lXext -ldl -lrt

**Comment by 9a4gl** [comment]
Note they stick to "latest working release" of webrtc, not to master. I do not know how latest working release is defined, but webrtc-streamer do not compile with that. I am having troubles building master with their system. Somehow I think webrtc-stream should also stick to stable releases as these VideoCapturer deletion and arm issues may come from using latest code.

**Comment by mpromonet** [comment]
I don't think problems with VideoCapturer deletion and arm crash comes from master (but I could be wrong). I saw these problems sevrals month ago, I guess the problem is related to inconsistent compilation flags. 
What problems do you have to build webrtc-streamer, I guess you should build enabling H264 support with GN_EXTRA_ARGS='rtc_use_h264=true ffmpeg_branding="Chrome"', maybe with WEBRTC_BRANCH_HEAD=master

**Comment by 9a4gl** [comment]
Another problem with libwebrtc it does not include thirtparty stuff, so it is missing json.h files.

**Comment by mpromonet** [comment]
json.h is in out/webrtc/src/thrird_party/jsoncpp/source/include/json

**Comment by 9a4gl** [comment]
I know, I am telling you that header is missing when you use https://github.com/aisouard/libwebrtc

**Comment by mpromonet** [comment]
me too, in libwebrtc/out/webrtc/src/thrird_party/jsoncpp/source/include/json

**Comment by 9a4gl** [comment]
I do not find this library helpful for building webrtc streamer and results with arm are not good.
