### ISSUE TITLE
How to load my RTSP via config.json

### ISSUE THREAD

**Issue by huyflo** [mpromonet/webrtc-streamer#260]
Dear mpromonet,
Thanks for your great project. I have a question that:

I built this project by pulling its images from docker-hub. I started it and worked perfect. However, could you please guild me to add my RTSP to config.json,and run it via docker images?

Thanks you very much.

**Comment by mpromonet** [comment]
Hi huyflo,

It depends on which environment you run you docker.

It is possible to overide the config.json in the container using  : 

     docker run -v $PWD/config.json:/app/config.json -p 8000:8000 mpromonet/webrtc-streamer

Best Regards,
Michel.

**Comment by huyflo** [comment]
Dear mprononet,
Thanks for quick reply. I selected "Havenmond" camera which is available on demo site and copied it to config.json => start docker container with below command: 

`docker run -v $PWD/config.json:/app/config.json -p 8000:8000 mpromonet/webrtc-streamer`

But got below error, do you have any suggest for this? 
 
![image](https://user-images.githubusercontent.com/37761016/62772272-4cba9580-bac9-11e9-9936-41a22deda56c.png)

![image](https://user-images.githubusercontent.com/37761016/62772361-8ab7b980-bac9-11e9-95b9-1f2619936410.png)

**Comment by mpromonet** [comment]
Dear huyflo,

I don't see any error, just logs that show you try to connect and then disconnect.
Probably some network connection pb either to the RTSP server or the STUN server ?
You may enable more logs using :
 
docker run -v $PWD/config.json:/app/config.json -p 8000:8000 mpromonet/webrtc-streamer -C config.json -vvv

Best Regards,
Michel.

**Comment by huyflo** [comment]
Dear mpromonet,
Below is output of your command:

![image](https://user-images.githubusercontent.com/37761016/62778922-f99e0e00-badb-11e9-95bc-71f53f834136.png)

![image](https://user-images.githubusercontent.com/37761016/62778946-028edf80-badc-11e9-9f57-bf3a7628eca4.png)

**Comment by mpromonet** [comment]
Hi huyflo,
You should look if the RTP stream is received, you should see some `RTSPVideoCapturer:onData` logs. 
Best Regards,
Michel.
