### ISSUE TITLE
webrtc-streamer Uncaught (in promise) TypeError

### ISSUE THREAD

**Issue by liezu** [mpromonet/webrtc-streamer#267]
HI:
I need help.
error
webrtc-streamer Uncaught (in promise) TypeError: Failed to execute 'addIceCandidate' on 'RTCPeerConnection': Candidate missing values for both sdpMid and sdpMLineIndex
![WX20190909-153200](https://user-images.githubusercontent.com/11386915/64511533-1c0f8b00-d317-11e9-8749-a940a98d463e.png)

**Comment by mpromonet** [comment]
Hi liezu,
This line is too send a end of candidate event, but it may depends on your browser.
Did you tried to remove the line 289 of webrtcstreamer.js ?
Best Regards,
Michel.

**Comment by liezu** [comment]
Thank you very much

**Comment by liezu** [comment]
> Hi liezu,
> This line is too send a end of candidate event, but it may depends on your browser.
> Did you tried to remove the line 289 of webrtcstreamer.js ?
> Best Regards,
> Michel.

Thank you very much

**Comment by eportico** [comment]
I have the same error. This error ony appear in Chrome. In Firefox is fine. I commented line 289 and It don't show error, but It disconnect connexion and don't show stream.

**Comment by mpromonet** [comment]
Hi,
I don't see this error, even not commenting the line 289.
Maybe you are using a old version of webrtc-streamer, or an old Chrome ?
Best Regards,
Michel.

**Comment by eportico** [comment]
Hi, 
I'm using last version docker image webrtc-stremer and last version Chrome

**Comment by eportico** [comment]
With Firefox is fine

**Comment by eportico** [comment]
The problem was docker. When get getCandidate, webrt-streamer container return ip container. This ip isn't visible in client and fail.
If I run webrtc-streamer container with --network="host" is fine in Chrome and Firefox.
It would good solution add new parameter to run webrtc-stremer to solve this issue.

**Comment by mpromonet** [comment]
Hi @eportico,
This seems different issue.
The getCandidate get the negociated candidates, if there is not viable candidate, you could use a TURN server with the `-t` option.
Best Regards,
Michel.
