### ISSUE TITLE
H264 Decode fail message are displayed continuously

### ISSUE THREAD

**Issue by sacoku** [mpromonet/webrtc-streamer#272]
**Describe the bug**
H264 decode Error messages are displayed continuously.

**To Reproduce**
Always displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/3263190/66400342-4343a000-ea1c-11e9-9fa7-4800e63da6c0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome

**Additional context**
In my opinion. It is necessary to skip NaluType :: kSei, I will show the code below(line 155)
```c++
else if (nalu_type == webrtc::H264::NaluType::kSei) {
    ; //skip
}
```

**Comment by mpromonet** [comment]
Hi sacoku,
I loose this merging file/rtsp consumer, I will re-apply your fix.
Best Regards,
Michel.
