### ISSUE TITLE
Dahua dvr support

### ISSUE THREAD

**Issue by DenisN03** [mpromonet/webrtc-streamer#274]
Hello!
I want to use your project to connect to a Dahua DVR.
Connection to the camera is as follows:
`rtsp://login:password@ip/cam/realmonitor?channel=channel&subtype=0`

But with such a request, the connection to the camera does not occur. I checked the command using the VLC player, the command is correct. Could you tell me what could be the problem and how to connect such a DVR?

**Comment by mpromonet** [comment]
Hi DenisN03,
You may look to the webrtc-streamer logs (maybe enabling more verbosity), maybe something goes wrong during rtsp connection or maybe the codec is not supported.
Best Regards,
Michel.
