### ISSUE TITLE
RTSP stream not stopped if browser do not hang up call

### ISSUE THREAD

**Issue by 9a4gl** [mpromonet/webrtc-streamer#28]
With Chrome browser, if you have your webpage with webrtc-streamer already in history and you start typing it, before you press enter to go to webpage, Chrome will fetch the page and and execute onLoad javascript method which will trigger webrtc stream and also RTSP stream.

If you do not go to you page or after you exit page, webrtc streamer will think there is still user of RTSP stream and will continue to receive video data from RTSP source. 

We should detect dead webrtc streams and remove them from stream users in PeerConnectionManager so that RTSP stream also get closed when not used anymore.

**Comment by mpromonet** [comment]
Fix by PR #29
