### ISSUE TITLE
jpeg Error

### ISSUE THREAD

**Issue by oih741** [mpromonet/webrtc-streamer#284]
My device uses Gstreamer. 
The image on my device is jpeg data, not x-raw data, and the video is sent to h264.
This option cannot be changed.
Is there a way to run it with webRtc-Streamer?
Thank you for reading this article.

**Comment by mpromonet** [comment]
Hi,
The RTSP consumer should be able to read JPEG data and the webrtc negociation will choose the codec (VP8, VP9 or H264)
Best Regards,
Michel.

**Comment by oih741** [comment]
hi,
What other settings should I set?

**Comment by oih741** [comment]
![messageImage_1574382016763](https://user-images.githubusercontent.com/22514655/69512031-cd70a500-0f85-11ea-84c3-fb2271d55289.jpg)
![messageImage_1574382024887](https://user-images.githubusercontent.com/22514655/69512032-cd70a500-0f85-11ea-964c-08787a2a10dc.jpg)
![messageImage_1574382030824](https://user-images.githubusercontent.com/22514655/69512033-cd70a500-0f85-11ea-815a-2159f572c5df.jpg)
![messageImage_1574382036680](https://user-images.githubusercontent.com/22514655/69512034-cd70a500-0f85-11ea-9c42-712443b5bef9.jpg)
![messageImage_1574382041755](https://user-images.githubusercontent.com/22514655/69512035-ce093b80-0f85-11ea-8795-f7cde8afa08b.jpg)
--------------------------------------------------------------------------------------------------------------
Gstreamer (x-raw) -> Webrtc  
   -> Sending x-raw from gstreamer does not cause an error.
But.
Gstreamer (video/jpeg) -> Webrtc  
  -> Sending jpeg from gstreamer will result in the error shown above.

**Comment by mpromonet** [comment]
Hi,
In the log you post, everything seems to be RTSP source of H264 streams....
Best Regards,
Michel.
