### ISSUE TITLE
json/json.h not found

### ISSUE THREAD

**Issue by oscarmh** [mpromonet/webrtc-streamer#295]
Hi Im trying to install in Ubuntu 18.04 , after following instructions and download everything needed I got an error like 

In file included from /root/webrtc-streamer/src/HttpServerRequestHandler.cpp:13:0:
/root/webrtc-streamer/inc/HttpServerRequestHandler.h:16:10: fatal error: json/json.h: No such file or directory
 #include "json/json.h"
          ^~~~~~~~~~~~~

I´ve done cmake . -DWEBRTCBUILD=Release -DWEBRTCROOT=/root/src (in src i got the webrtc from google)

Any hint appreciated, thanks in advance

**Comment by mpromonet** [comment]
Hi,
If you run fetch webtc in /root/src, you should use  `-DWEBRTCROOT=/root/src/webrtc`
Best Regards,
Michel.
