### ISSUE TITLE
How control aspect ratio?

### ISSUE THREAD

**Issue by rossbcan** [mpromonet/webrtc-streamer#296]
OpenWrt x96_64, nginx proxied, webrtc-streamer

demo: https://www.rossco.org/cameras/?layout=2x3

Q: enforce aspect ratio on demo page. Feeds are 16:9. On demo page, using layout option, feeds render as 4:3. How can I enforce aspect ratio on a per-feed basis, or globally? Images are distorted due to aspect ration conversion.

Thanks;
Bill

**Comment by mpromonet** [comment]
Hi Bill,
This is controled by layoutextraoptions in https://github.com/mpromonet/webrtc-streamer-html/blob/master/webrtcstreamer.json 
Trying layoutextraoptions: "&width=320" should keep the ratio.
Best Regards,
Michel.

**Comment by rossbcan** [comment]
That was it.

Thanks;
