### ISSUE TITLE
Make it easier to start the app via docker-compose

### ISSUE THREAD

**Issue by kohnech** [mpromonet/webrtc-streamer#299]
**Is your feature request related to a problem? Please describe.**
It is hard to stop the docker container when started from docker run. Using docker-compose solves this. Also many users are used to start docker containers via docker-compose.

**Describe the solution you'd like**
By using `docker-compose up app` you can easily start the app and also with a video for linux web-camera you just type `docker-compose up app-v4l2`. When you need to stop just use `Ctrl-C`.

**Describe alternatives you've considered**
We could add a background app instead with no stdout and then stop via `docker-compose down`. But the stdout is nice to have to see traffic logs, so thats why I didn't add this feature.

`app` may be changed to another suitable name, maybe `docker-compose up webrtc-streamer`??
Not sure what is the best naming for this service... 

**Additional context**
NA

**Comment by mpromonet** [comment]
Hi kohnech

I am not convinced about adding multiple entries in docker-compose. I prefer to keep it simple.
In order to handle correctly SIGINT handler I made the modification
5cba130

Now it is possible to terminate a docker run command with Ctrl+C.

Best Regards,
Michel.
