### ISSUE TITLE
Streaming live CCTV feed to Android / iOS App

### ISSUE THREAD

**Issue by guruvishnuvardan** [mpromonet/webrtc-streamer#301]
Hi,
**It's a question.
Can you please let me know, if I can integrate RTSP live streaming to an Android / iOS app?? , If yes, Can you please let me know the process or links to learn.

Thanks
Guru

**Comment by mpromonet** [comment]
Hi Guru,
This project makes a gateway rtsp to webrtc, then connecting to the webserver on android/ios should show you the webrtc streams.
You can try with the demo app https://webrtc-streamer.herokuapp.com/
Using Chrome on android it is working, I have no IOS maybe it is working, maybe it needs some debug/modification...
Best Regards,
Michel.

**Comment by vegalou** [comment]
**By my test logs,**

### 1. RTSP format

If you want to _`forward RTSP to mobile`_, push RTSP source to cloud RTSP server, then receive streaming in APP directly. Or if there is TUTK($) like P2P toolkit between IPCam and mobile, they could connect through STUN directly.

### 2. standard html5 video with webrtc

If you're running webrtc-streamer, read the README.MD homepage shows, poll the RTSP streaming via webrtc-streamer, it's HTML5 VIDEO in webrtc already, If it's behind a firewall, then push your source to gateway like Janus via webpage or nodejs cli resource.

Then all pc/mobile browsers could watch HTML5 VIDEO directly.
