### ISSUE TITLE
Is two-way audio supported?

### ISSUE THREAD

**Issue by mutasim** [mpromonet/webrtc-streamer#304]
**Use case**: I have an ONVIF compliant camera, which supports RTSP backchannel audio. I want to build a browser based, audio-only intercom for receiving but also sending back audio over WebRTC. 

Does this project support the sending of WebRTC audio back to the RTSP feed?

**Comment by mpromonet** [comment]
Hi mutasim, 
This is actually not implemented, but the audio can be sent to server using :
`webRtcServer.connect(url.video,url.audio,options,stream)`
Next you should find a way to forward to the RTSP consumer, and then make stuff in live555 to send audio through the RTSPClient object.
Best Regards,
Michel.

**Comment by AleXoundOS** [comment]
@mutasim, have you succeeded?

**Comment by mutasim** [comment]
No sorry - no progress from me.
