### ISSUE TITLE
Memory optimization

### ISSUE THREAD

**Issue by rahul3349** [mpromonet/webrtc-streamer#305]
I'm using webrtc-streamer on linux platform, I can see that RAM usage is up to 4GB, so is there any possiblity of reducing memory foot print?

**Comment by rahul3349** [comment]
I checked webrtc memory consuption by running video loopback test app which also do transcoding, it consumes ~950MB. so Need to know where the rest of memory (~3GB) is being consumed?

**Comment by rahul3349** [comment]
Measured memory usage by live555 client by running openRTSP test app, it is comsuming ~60MB.

**Comment by mpromonet** [comment]
Hi,
Reducing the resolution, the number of connection should help.
Feel free to submit pull request with your improvement.
Best Regards,
Michel.

**Comment by rahul3349** [comment]
@mpromonet  I'm checking memory usage without any connection.
