### ISSUE TITLE
How to configure TCP/UDP port range 

### ISSUE THREAD

**Issue by MinChanSike** [mpromonet/webrtc-streamer#306]
Hi Michel,
Thank you for your great repository.
How can I set for TCP/UDP port range allocation and can I know default port range allocation?
We need to configure port range on firewall.

Best Regards

**Comment by s-beard** [comment]
Hi Michel,
Can you help us to fix a lower range for udp on webrtc ?
Candidate have an udp range to 1024:65535

Thank's

**Comment by mpromonet** [comment]
Hi,

Actually this is using the default behaviour of WebRTC SDK, may be it is possible to overide the default port allocator.
Maybe you can get inspiration from https://github.com/Jamie0/webrtc-streamer/commit/95ad0a6436e78836d2a26fc99b801e7bf9374ea8 ?

Best Regards,
Michel.
