### ISSUE TITLE
peerconnection_client does not run on ARM

### ISSUE THREAD

**Issue by avp24** [mpromonet/webrtc-streamer#308]
Hi, 

I am trying to cross compile webrtc stack for ARM, downloaded as per the steps mentioned in build and cross  compiling using ninja command.
I am able to successfully compile it for ARM.
Now, after copying the peerconnection_client its required libraries and peerconnection_server on my board; executing peerconnection_server in background (it runs successfully) but on executing peerconnection_client --server 192.168..1.168 --port 8888 --autoconnect I get below error:
**./peerconnection_client: /customer/libdbus-1.so.3: unsupported version 0 of Verdef record
./peerconnection_client: /customer/libdbus-1.so.3: unsupported version 0 of Verdef record**
Here i have created softlinks in /customer partition and actual libraries are in SD card mounted on board.

Can anyone please guide me to solve this issue?

**Comment by mpromonet** [comment]
Hi ap24,

If you are refering to wiki page https://github.com/mpromonet/webrtc-streamer/wiki/Cross-compile-WebRTC-for-Raspberry-Pi, it is pretty old, it was some notes when webrtc needs some patching.

The problem describes seems completly in the WebRTC SDK, nothing seems related to this project, then probably reporting to https://bugs.chromium.org/p/webrtc/issues is more appropriated.

Just an guess will be that the cross-compile target has some differences with the running environment. The cross-compiler may be not the one corresponding to the runtime.

Best Regards,
Michel.
