### ISSUE TITLE
how to use external http server (Boa server) instead of internal http server (civetweb server) in webrtc-streamer

### ISSUE THREAD

**Issue by Naisargi-02** [mpromonet/webrtc-streamer#311]
Hello,
I am new to webrtc, so don't know how to use external http server with webrtc-streamer.
I have setup Boa server in my board and it is working fine. I have downloaded the prebuilt binary of webrtc-streamer from the below link :

https://sourcey.com/precompiled-webrtc-libraries/?__cf_chl_captcha_tk__=825d2d3b7f334b9ab10e89ae01b9f1ca89272fed-1583936267-0-AeJe_EfPyBtYuLDA4Jy6xGEaXP0L5jUnof_4XW7ZfvBHz7JjyD23uCxDAJjO19VxNeI2_s9BE6GPQhjreaTKjAfX08zD7FX1reG3sgvcfBJKTnM_D8Zr-0bQNNsWY0194-t1TqgHBplL2eMRzj-6sFAAF_oH0z-uLKltkQZNxZd3WLclg5POJVgA_Izr57jDigivoRiLcFrmfVZJhvpGW-hv9EValUF_tCs8kRS2kml0s4krQDI8i9XqUK7wcJxq_On1nRt7QsTwlQoKZ397g-_JNuqvH1IF57rap98mJxzTpbLd2pwa5c2crdyTs5ZclwAQ1eIA8C-JalpPNzNJO2AjtKbYHOUh1uvqH6bKg9eM3HlhOdWy6OPWC5GB1C7VEgUMlxhUUYEtREGIkQzj-WkoOaHeyBH3mXXOxJGTc6sHyadBba17G_fm6NRr3IwtAvMIY2Cn7eLG-QrOcEbC1KlKgtsL6dXJsqg0tJG6U0EX

And it is using civetweb server for handling http request, but i have boa server on board. So how to use boa server with prebuilt binary of webrtc-streamer.
Note: I am not able to build webrtc-streamer, so please provide me the direct solution which can be use on prebuilt binary of webrtc-streamer.

Thanks in advance.

**Comment by mpromonet** [comment]
Hello,

In order to use external http server that serves the static pages, you can use (from README) a simple page that will use civetweb embedded server for api :
```
<html>
<head>
<script src="libs/request.min.js" ></script>
<script src="libs/adapter.min.js" ></script>
<script src="webrtcstreamer.js" ></script>
<script>        
    var webRtcServer      = null;
    window.onload         = function() { 
        webRtcServer      = new WebRtcStreamer("video",location.protocol+"//"+window.location.hostname+":8000");
	webRtcServer.connect("rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov");
    }
    window.onbeforeunload = function() { webRtcServer.disconnect(); }
</script>
</head>
<body> 
    <video id="video" />
</body>
</html>
```
You need to put copy webrtcstreamer.js, libs/request.min.js and libs/adapter.min.js and it should work with the last release https://github.com/mpromonet/webrtc-streamer/releases/tag/v0.2.6

Best Regards,
Michel.
