### ISSUE TITLE
Window Capturing Issues

### ISSUE THREAD

**Issue by nagarjunabandi** [mpromonet/webrtc-streamer#315]
I have integrated screen capturer module in webrtc native peer connection example. It is working fine when selecting screen through ScreenCapturer class. Able to capture window also with WindowCapturer class only when the window is in maximized state. If the window restored or resized then frames are getting disturbed. Also unable to capture cursor in ScreenCapturer mode as well as WindowCapturer mode.

![image](https://user-images.githubusercontent.com/13998541/79561771-84052b80-80c7-11ea-925b-79bc925c4d60.png)

**Comment by mpromonet** [comment]
Hi nagarjunabandi,

Yes I know, on Windows it works with screen, but not with windows... with older WebRTC SDK it was working. It works on Linux.
Probably a bas computation of stride... if you find the problem thanks to share it.

Best Regards,
MicheL

**Comment by nagarjunabandi** [comment]
Thanks for your quick reply, I will look into the window capture issue, can you please help me out to capture mouse cursor. Thanks in advance.
