### ISSUE TITLE
iOS resolution issue

### ISSUE THREAD

**Issue by SnoyIatK** [mpromonet/webrtc-streamer#320]
On iOS, play a streaming video in portrait mode always results in full screen height, and can not resize to fit screen resolution.
When playing same mp4 file, the player will only fit to screen size.

**To Reproduce**
1. Go to 'https://webrtc-streamer.herokuapp.com/?layout=2x2' using any iPhone
2. Tap to play any video in portrait mode
3. Change to landscape mode

**Expected behavior**
The player should fit to device screen in portrait mode.
See below screenshots.

**Screenshots**
> portrait
![portrait](https://user-images.githubusercontent.com/3056569/80815106-003f5900-8c08-11ea-83e1-12df9d63202a.png)
> landscape
![landscape](https://user-images.githubusercontent.com/3056569/80815111-033a4980-8c08-11ea-9198-f41021644fd6.png)
> mp4
![expected](https://user-images.githubusercontent.com/3056569/80815117-05040d00-8c08-11ea-8ef0-48d03675f5cc.png)
.

**Smartphone (please complete the following information):**
 - OS: iOS 13.3.1
 - Browser: Safari

**Comment by mpromonet** [comment]
Hi SnoyIatK,

This seems html/js/css stuff, there is just very simple stuff to display webrtc streams.
You can easily do your own presnetaion using the webcomponent or the javascript interface or the http interface.

Best Regards,
Michel.

**Comment by jumarti** [comment]
This is a default behaviour on IOs devices. Set the HTML attribute `playsinline` to the video.  It worked for me
