### ISSUE TITLE
Trying to stream RTSP to a JITSI Room

### ISSUE THREAD

**Issue by sigfoxsignal** [mpromonet/webrtc-streamer#321]
Hello
I have installed on my PC webrtc-streamer an launched http://localhost:8000/jitsitest.html
It looks like the demo is not working.

Looking at the javascript logs I found that Strophe cannot connect to Jitsi.
I added the "xmppvideoroom.js:16 Strophe cx : https://meet.jit.si/http-bind" debug line to make sure that the URL was OK.

I also tried your online demo at https://webrtc-streamer.herokuapp.com/xmppvideoroom.html
It looks like it is also not working.

Could you tell me what is wrong ?
Regards
JM

Uncaught ReferenceError: module is not defined
    at xmppvideoroom.js:430
xmppvideoroom.js:16 Strophe cx : https://meet.jit.si/http-bind
**xmppvideoroom.js:64 Strophe is connecting. : meet.jit.si**
favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)
xmppvideoroom.js:66 Strophe failed to connect.
**jitsitest.html:1 Uncaught (in promise) Strophe failed to connect.**
DevTools failed to load SourceMap: Could not load content for http://localhost:8000/sm/363834f72f8830891ded0e2371fb97b773099f4623362586564fdc5db32da561.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:8000/sm/d7936bb6af983cbe306d98c2f5046a8c25cabfe5c7991e8f9d503a857db4bb4e.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:8000/libs/request.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by mpromonet** [comment]
Hi sigfoxsignal,

There is long time I did not work on this subject, XMPP is really badly documented and library are so complex to use.

Anyway jitsitest.html is just a simple test of the javascript, it just publish Bunny.
I made a quick test with https://webrtc-streamer.herokuapp.com/xmppvideoroom.html and I have the same pb you report, "Strophe failed to connect.".    
The connection process have probably change....

Best Regards,
Michel.
