### ISSUE TITLE
Not working on iPhones

### ISSUE THREAD

**Issue by RobBiddle** [mpromonet/webrtc-streamer#322]
**Describe the bug**
Video does not play on iPhones. It does work on iPads. 

**Additional context**
This appears to be the problem:
https://forums.developer.apple.com/thread/88405

**Comment by mpromonet** [comment]
Hi Robert,

There is no problem to add "playsinline" attributes to the video tag, this can be done in the HTML.

Best Regards,
Michel.

**Comment by RobBiddle** [comment]
Thank you Michel, I'm using the Docker image and it is still not playing video when viewed from an iPhone.  Does the Docker image need to be updated as well?

FYI - There's a web-based iPhone emulator here: https://appetize.io/  The demo on the main page allows you to open Safari and browse to a WebRTC site to test.  I've also confirmed on a real iPhone.
