### ISSUE TITLE
Provide a data channel

### ISSUE THREAD

**Issue by distr0** [mpromonet/webrtc-streamer#327]
It would be great to have a data channel available to control a remote PTZ camera through Onvif or any other solution.
Having a data channel would suffice and it might serve other purposes as well.

Is this doable?
Thanks

**Comment by mpromonet** [comment]
Hi,

Sure, the datachannel is opened, see https://github.com/mpromonet/webrtc-streamer/blob/master/inc/PeerConnectionManager.h.

Best Regards,
Michel.
