### ISSUE TITLE
audio streaming problem

### ISSUE THREAD

**Issue by VerHext** [mpromonet/webrtc-streamer#328]
First of all thanks for this nice project.

I try to play rtsp streams with webrtcstreamer.js in the browser. 
Video works fine. But it does not transmit audio.
I try several rtsp streamers, different codecs, demo video bunny, but nothing works for me.
That my client side: https://config.fail/uxewiqewec.html
Is there a special codec that must be used?

**Comment by mpromonet** [comment]
Hi Johannes,

The audio support needs to have build with ALSA installed installed. During the cmake you should see `ALSA_FOUND=true`. There is no easy way to get this from the executable.
Something like `nm webrtc-streamer | grep -i alsa`

Next the format should be supported by live555 and WebRTC SDK, I made test with opus & pcm.
If the codec is not supported by WebRTC you should see the error `LiveAudioSource::onNewSession not support codec`    

Best Regards,
Michel.

**Comment by VerHext** [comment]
Hello Michel,

thanks for your fast response. 

ALSA is installed and enabled. 
With Opus 48k 2 - I get a "not supported codec" error. Using PCM it doesn't play either.
https://config.fail/ovopupulec.md

**Comment by mpromonet** [comment]
Hi Johannes,

There is the Describe answer for video but it seems the RTSP negociation for audio fails `Failed to DESCRIBE: Received a complete`. 
Still there is no log `LiveAudioSource::onNewSession` and then `LiveAudioSource::onData`, no data is received by the consumer.

Best Regards,
MicheL

**Comment by VerHext** [comment]
oh yeah, sorry. 
Thanks works great!
