### ISSUE TITLE
Not working on 4G

### ISSUE THREAD

**Issue by LChacon41** [mpromonet/webrtc-streamer#329]
**Describe the bug**
I've implemented the webrtc-streamer successfully on Ubuntu 18.04, created a HTML page where I can visualize various RTSP streams from any WIFI network, but when I test it on 4G, on android(Chrome) it works only once for a singular stream, and it never works on iOS (Safari). 

**To Reproduce**
I even reproduced the problem trying your live demo on both android (Chrome) and iOS (Safari) mobiles. And again, it worked perfectly on wifi but not with a 4G data connection. 

**Expected behavior**
I expected it to work the same on WiFi and 4G. 

**Screenshots**

iOS-Safari
![image](https://user-images.githubusercontent.com/57192814/84948586-cd123580-b0a0-11ea-8243-c8574907b336.png)

Android-Chrome
![image](https://user-images.githubusercontent.com/57192814/84948574-c5eb2780-b0a0-11ea-883e-475fb5edf713.png)

**Smartphones:**
 - Devices: iPhone 6 (iOS 13.3.1) and Motorola G6Plus (Android 8.1.0)
 - Browsers: Safari and Chrome

**Comment by mpromonet** [comment]
Hi,

This is probably not link to wifi or 4G connection or wired, but more of the ICE negociation & STUN access.
Maybe the google STUN is not reachable when you are using 4G connection.

Best Regards,
Michel.
