### ISSUE TITLE
Can't open stream in another computer in the same network

### ISSUE THREAD

**Issue by CleitinIF** [mpromonet/webrtc-streamer#331]
**Describe the bug**
I can't open stream in another device even being on the same network

**To Reproduce**
1. Starts a container: `docker run -p 8000:8000 -it mpromonet/webrtc-streamer -h`
2. Starts a server with current html:

```
<html>
  <head>
    <script src="libs/request.min.js" ></script>
    <script src="libs/adapter.min.js" ></script>
    <script src="webrtcstreamer.js" ></script>
    <script>        
      var webRtcServer      = null;
      window.onload         = function() { 
        webRtcServer      = new WebRtcStreamer("video",http://myAddress:8000");
	webRtcServer.connect("rtsp://anyValidStream/cam/realmonitor");
      }
      window.onbeforeunload = function() { webRtcServer.disconnect(); }
    </script>
  </head>
  <body> 
    <video id="video" />
  </body>
</html>
```
3. Enter in http://myAddress:8000/ in another device
4. Video doesnt appear

**Screenshots**
![WhatsApp Image 2020-06-22 at 5 23 57 PM](https://user-images.githubusercontent.com/49418438/85331889-58c70000-b4ad-11ea-94eb-806e1f72646f.jpeg)

**Desktop**
 - OS: Ubuntu x64
 - Browser: Chrome and Firefox

**Comment by mpromonet** [comment]
Hi CleitinIF 

This is probably because ICE candidate are using the internal docker ip.
Did you try with :

`docker run -p 8000:8000 --network host -it mpromonet/webrtc-streamer`

Best Regards,
Michel.
