### ISSUE TITLE
how to download the laster tag Windows-AMD64-Release.tar.gz

### ISSUE THREAD

**Issue by dolwin** [mpromonet/webrtc-streamer#332]
I am not good at C language development, I downloaded the old version and have problems

**Comment by mpromonet** [comment]
Hi Dolwin,

What kind of problem do you have ?

Best Regards,
Michel.

**Comment by dolwin** [comment]
@mpromonet  thanks you for reply
can you send me the laster Windows-AMD64-Release.tar.gz to test，I tried one night and it didn't build successfully
my email is glasssky001@gmail.com
sorry to bother you

**Comment by mpromonet** [comment]
Hi,
I published a new release, you can get https://github.com/mpromonet/webrtc-streamer/releases/download/v0.3.0/webrtc-streamer-v0.3.0-Windows-AMD64-Release.tar.gz
Last build can be get from appveyor https://ci.appveyor.com/project/mpromonet/webrtc-streamer/builds/34171553/job/syveb2lvr9l6csgg/artifacts

Best Regards,
Michel

**Comment by dolwin** [comment]
@mpromonet  thanks you
