### ISSUE TITLE
unable to start program for Windows in Debug Mode

### ISSUE THREAD

**Issue by whucj** [mpromonet/webrtc-streamer#340]
On the debug model，the below error  occures.
![image](https://user-images.githubusercontent.com/15603414/88801249-f663cc80-d1db-11ea-8d2c-21789bd2c4b5.png)

My computer environment is as follows:
webrtc-streamer:master branch
webrtc version:m84

windows 10

visual studio 2017

windows 10 sdk  10.0.19041

Thanks

**Comment by mpromonet** [comment]
Hi,

I know you are right since I moved the build from visual studio solution to ninja, it has never worked in debug on windows.

Best Regards,
Michel.

**Comment by mpromonet** [comment]
Hi,

If you like, building with 
```
cmake -G "Visual Studio 16 2019 Win64" -DWEBRTCBUILD=DEBUG .
msbuild webrtc-streamer.sln -p:Configuration=Debug
```
This allow to build a runnable executable and have debug activities.

Best Regards,
Michel.

**Comment by Teddy2212** [comment]
how to fix it CMake Error and Cmake generate step failed....
![image](https://user-images.githubusercontent.com/39071803/94392253-bd6fb600-0192-11eb-95c4-a3e62a0b8927.png)

**Comment by mpromonet** [comment]
Hi,

I am closing the issue as it is working now, using https://github.com/mpromonet/webrtc-streamer/releases/download/v0.3.5/webrtc-streamer-v0.3.5-Windows-AMD64-Debug.tar.gz.

Best Regards,
Michel.
