### ISSUE TITLE
can't get it to work behind nginx proxy

### ISSUE THREAD

**Issue by s0mm3rb** [mpromonet/webrtc-streamer#344]
Hi there, great software but

what is the preferred way to publish the app behind a proxy? nginx in my case

I am out of ideas on how to do it

I am running in docker and the nginx server is in an other container in the same subnet
everything works fine if I access http://dockerhost:8000
but I want to hide and publish this url with my nginx server

my problem is the base url (it would be easy if I could set the base url somewhere)
I want to publish the app as https://mydomain/rtcapp (I cannot use a subdomain)
but it only loads the index.html because it cannot access the api directory
when I open the app the api path does not get redirected to https://mydomain/rtcapp/api
instead it tries to access https://mydomain/api

I tried rewriting the url and using sub filters as suggested here:
[http://sawers.com/blog/reverse-proxying-with-nginx/#option4asymmetricpath](http://sawers.com/blog/reverse-proxying-with-nginx/#option4asymmetricpath)

but nothing works, it still tries to access https://mydomain/api

thanks

please consider an option to change the baseurl in future releases(!)

**Comment by mpromonet** [comment]
Hi @s0mm3rb ,

If you are speaking about the url of the backend, it is possible to set it, the html/js could be served by nginx or whatever webserver (there are embeded just to give a simple working demo) 
Probably the simplest way is setting the url in webrtcstreamer.json : 
```
var webrtcConfig = {
        url: "https://mydomain/rtcapp"
}
```
There is also a option in the webcomponent that do the same thing.

If you are speaking of adding a base url to the backend, this is not complex to do, it just need to change registering of http function (in PeerConnectionManager.cpp):
```
m_func["/api/getMediaList"] 
....
```

Best Regards,
Michel.
