### ISSUE TITLE
Possible CPU optimization -- reference counter for rtsp url

### ISSUE THREAD

**Issue by saket424** [mpromonet/webrtc-streamer#35]
Currently, if more than one browser  accesses a specific rtsp URL, the CPU usage doubles. Is it possible to reuse the transcoded video by maintaining a reference counter and not wastefully transcode the same rtsp stream more than once?

**Comment by mpromonet** [comment]
Not sure about that, I guess each encoder adapt the compression to the comunication bandwidth.
