### ISSUE TITLE
How start docker image with active turn server?

### ISSUE THREAD

**Issue by shurshilov** [mpromonet/webrtc-streamer#351]
I start my webrtc server as docker run -p 8000:8000 -it mpromonet/webrtc-streamer.
I have static Ip, and it work from internet, but localy no. 
I think I need a turn server but how to activate it in docker?
I also try get access from this url but https://eurodoo.com:8000/webrtcstreamer.html?rtsp://user:pass@ip/1/h264major
user and pass change offcause, but video play in my iphone and other, but no on my server directly network, for example computer with docker image run)
https://webrtc-streamer.herokuapp.com/webrtcstreamer.html?rtsp://user:pass@ip/1/h264major
but this link work good on my iphone and my computer, why?

```
<html>
<head>
<script src="request.min.js" ></script>
<script src="adapter.min.js" ></script>
<script src="webrtcstreamer.js" ></script>
<script>        
    var webRtcServer      = null;
    window.onload         = function() { 
        webRtcServer      = new WebRtcStreamer("video","https://eurodoo.com:8000");
	webRtcServer.connect("rtsp://user:pass@ip/1/h264major");
    }
    window.onbeforeunload = function() { webRtcServer.disconnect(); }
</script>
</head>
<body> 
    <video id="video" />
</body>
</html>
```
Attach log)
https://eurodoo.com/web/content/10331?download=true%D0%91%D0%B5%D0%B7%20%D0%B8%D0%BC%D0%B5%D0%BD%D0%B8.png

**Comment by mpromonet** [comment]
Hi,

Did you try with `--net=host` ?

Best Regards,
Michel.

**Comment by shurshilov** [comment]
> Hi,
> 
> Did you try with `--net=host` ?
> 
> Best Regards,
> Michel.

Then I get 502 bad gataway

**Comment by mpromonet** [comment]
Hi

> Then I get 502 bad gataway

Seems more an nginx error message than a error from webrtc-streamer.
You may look to that stuff....

Best Regards,
Michel.

**Comment by shurshilov** [comment]
My setting was 8000 port on firewall proxy to 8001 nginx and than nginx encrypted using SSL and proxied to port 8000 on which the docker image was running. This scheme did not always work. For example, it worked through the network of a mobile operator, it was not inside my network, and for example, when I entered from a computer at work, it did not work either.

Further why I did it. I need to make a widget inside the site that displays the rtsp stream from the camera. The site is naturally https. If you make an iframe directly to the 8000 port of the docker, then since the docker image has http, the browser blocks such an iframe. So I had to proxy. 
Used iframe as js code doesn't work.

**Comment by shurshilov** [comment]
![image](https://user-images.githubusercontent.com/11828278/95026455-29be4e00-069a-11eb-8c13-8927416b3311.png)
this i got if call directly docker http

**Comment by shurshilov** [comment]
I do it man))
Just change
//WRONG dont do it                        webRtcServer.connect(myurlvideo);
                        var url = {'video':this.value}
                        var options = "rtptransport=tcp&timeout=60";
                        webRtcServer.connect(url.video,url.audio,options);

**Comment by mpromonet** [comment]
Hi,

Good to see that giving option argument solve your problem. 
This means that the default transport RTP/UDP between rtsp source and webrtc-streamer doesnot send stream.

Best Regards,
Michel.
