### ISSUE TITLE
docker pull failed

### ISSUE THREAD

**Issue by hp6120c** [mpromonet/webrtc-streamer#355]
when I run `docker run -p 8000:8000 -it mpromonet/webrtc-streamer` in my server(ubuntu 18.04), It is failed and give me a message:`docker: error pulling image configuration: unknown blob` ,I dont know how to fix it
`

**Comment by mpromonet** [comment]
Hi,

The latest dockerhub image is corrupted https://hub.docker.com/r/mpromonet/webrtc-streamer/tags 
`d59494321eca
linux/amd64
0 B`

You should try the lastest tag:
`mpromonet/webrtc-streamer:v0.3.2
`

I will regenerate the image.

Best regards,
Michel.

**Comment by lucastcox** [comment]
Thanks, @mpromonet, just ran into the same issue.

**Comment by mpromonet** [comment]
@lucastcox 

latest should be ok now since commit https://github.com/mpromonet/webrtc-streamer/commit/f6451624ad48e3000cf7141d6b74d07880a790ea

Best Regards,
Michel.
