### ISSUE TITLE
Unable to Build/Start Program 

### ISSUE THREAD

**Issue by MKtheGOD** [mpromonet/webrtc-streamer#357]
I have downloaded WebRTC successfully and have installed Chromium depot tools as well.  I dont know how to Build/Start the program. As per Chromium documentation, I am trying to build project like this, but getting Error as below. Also running "cmake . && make " command gives Error. Please someone guide me how to Setup webrtc-streamer on Windows 10 properly.

Thank You.!

![webrtc_error (2)](https://user-images.githubusercontent.com/67513331/95077718-989ab600-0731-11eb-9147-00a10b46bc97.png)

**Comment by mpromonet** [comment]
Hi,

It seems visual studio is not found.
You may look to [Dockerfile](Dockerfile.windows)

Best Regards,
Michel.
