### ISSUE TITLE
Many streams from one source

### ISSUE THREAD

**Issue by alexfreed58** [mpromonet/webrtc-streamer#358]
I have a question. If I understand correctly, if several clients want to get a feed from the same source, say a camera, the streamer uses a single CAPTURE input, but a separate encoder for each client. Since video encoding is a CPU intensive process, I'm wondering if it is possible to encode the stream once but use the same EncodedImage for multiple streams.

**Comment by mpromonet** [comment]
Hi,

This is done by the WebRTC SDK, but my understanding is that each client have a different negotiation to choose the format, resolution and dynamically adapt the bandwidth, then the encoding is different for each client.

Best Regards,
Michel.

**Comment by alexfreed58** [comment]
Thanks for the answer, but do you have any suggestion as to how to approach this with the SDK?

**Comment by mpromonet** [comment]
Hi,

You can submit your wishes to https://bugs.chromium.org/p/webrtc/issues/entry

Best Regards,
Michel.

**Comment by alexfreed58** [comment]
I'm closing the "issue" as it was really a question rather than an issue :)
