### ISSUE TITLE
Stream Works on index, but not when embedded in Webpage?

### ISSUE THREAD

**Issue by djn10city** [mpromonet/webrtc-streamer#359]
Hello,

I'll default that I may not be doing something correctly, but when I load the stream from the terminal or from index using /?streamurl, it loads fine.

When I use the example embed html and replace your stream with my stream, it doesn't load.

```
<html>
<head>
<script src="libs/request.min.js" ></script>
<script src="libs/adapter.min.js" ></script>
<script src="webrtcstreamer.js" ></script>
<script>        
    var webRtcServer      = null;
    window.onload         = function() { 
        webRtcServer      = new WebRtcStreamer("video",location.protocol+"//"+window.location.hostname+":8000");
	webRtcServer.connect("rtsp://74.94.110.81:7447/n9HSYhAtyQXiRTon");
    }
    window.onbeforeunload = function() { webRtcServer.disconnect(); }
</script>
</head>
<body> 
    <video id="video" />
</body>
</html>
```

Thoughts?

Thanks!

**Comment by mpromonet** [comment]
Hi,

The index.html use the options defined in https://github.com/mpromonet/webrtc-streamer-html/blob/master/webrtcstreamer.json, so maybe you need to add option "rtptransport=tcp" and connect using : 
`webRtcServer.connect("rtsp://74.94.110.81:7447/n9HSYhAtyQXiRTon", "", "rtptransport=tcp");`

Best Regards,
Michel.

**Comment by djn10city** [comment]
Beautiful.  Worked like a champ.

Thank you!
