### ISSUE TITLE
Add daemon mode and log to file

### ISSUE THREAD

**Issue by 9a4gl** [mpromonet/webrtc-streamer#36]
Would be nice to have --daemon option so that it starts in background
Also would be nice to have --log so we can have log in /var/log/webrtc-streamer.log .. also we should have timestamp in from on each log line

**Comment by mpromonet** [comment]
Hi,
I am not fan of this apporach, I prefer that an appilcation doesnot interact too much with the operating system. In order to start as a deamon you could configure your favorite init system and to log it you could redirect the outpout to logger.
Best Regards,
Michel.
