### ISSUE TITLE
Application Flow

### ISSUE THREAD

**Issue by petryx** [mpromonet/webrtc-streamer#361]
Hi Michael,

Firstable your project is awesome. Congratulations for your code.

I'm trying understand your code, would be possible you can describe the application flow of point of view  of IP Camera with rtsp until video appear on browser.

Thanks in advance Michael

**Comment by mpromonet** [comment]
Hi petryx,

The flow is very simple, it makes a very simple protocol conversion, the RTSP Sink frame is decoded (using WebRTC decoder) and post to WebRTC Source.

Best Regards,
Michel.

**Comment by petryx** [comment]
Thanks Michel.

Why need develop a very simple version, with the minimal necessary.

> Hi petryx,
> 
> The flow is very simple, it makes a very simple protocol conversion, the RTSP Sink frame is decoded (using WebRTC decoder) and post to WebRTC Source.
> 
> Best Regards,
> Michel.
