### ISSUE TITLE
RTP / UDP H264 stream compatibility

### ISSUE THREAD

**Issue by lukelu0520** [mpromonet/webrtc-streamer#363]
Dear webrtc-streamer friends,

Recently, we are receiving a RTP / UDP H264 video stream from a device, and we are considering forward it via webrtc-streamer with our server.

We were wondering if any suggested ways to make it. Do we need to convert the RTP / UDP H264 stream to a RTSP stream ? Or webrtc-streamer has an internal method to capture RTP / UDP H264 and make it available. 

Hope to hear your expertise.

Best,
-- Luke

**Comment by mpromonet** [comment]
Dear Luke,

As webrtc-streamer use live555helper to get RTSP stream that also support RTP stream, it should be easy to add RTP support to the consumer.

Best Regards,
Michel.

**Comment by lukelu0520** [comment]
@mpromonet , sounds nice, thanks for your prompt reply! So you mean just simply apply url _rtp://ip_address:port_ ? 
Kindly let us know if any reference (or readme) in order to implement it.

Best,
-- Luke

**Comment by lukelu0520** [comment]
@mpromonet, Update: we tested many configurations like:  
`./webrtc-streamer rtp://[bind_host][:port]@[remote_host[:port]]` or
`./webrtc-streamer udp://[bind_host][:port]@[remote_host[:port]]`

But we can not get the stream so far. Hope to hear your expertise.
Best,
-- Luke

**Comment by mpromonet** [comment]
Hi Luke,

It is needed to modify the code, in the actual situation this is not possible. I was explaining a way to easily adding this feature.

Best Regards,
Michel.
