### ISSUE TITLE
(video_capture_impl.cc:132): Wrong incoming frame length.

### ISSUE THREAD

**Issue by lukelu0520** [mpromonet/webrtc-streamer#364]
Dear webrtc-streamer friends,

We got this error `(video_capture_impl.cc:132): Wrong incoming frame length.` when using gstreamer to v4l2sink (virtual v4l2 device is created by v4l2loopback).

So far, we have to manually re-scale our video size to 640x480 (by using video/x-raw, width=640, height=480) in order to make webrtc-streamer working.

We were wondering the reason and any method to set another video size rather than binding us to 640x480.

Hope to hear your expertise.

Best,
-- Luke

**Comment by mpromonet** [comment]
Hi Luke,

Maybe gstreaming is sending a wrong size, or v4l2looback interpreted wrong, or the code that check it do mistake.
The WebRTC code use `CalcBufferSize` [https://github.com/pristineio/webrtc-mirror/blob/7a5bcdffaab90a05bc1146b2b1ea71c004e54d71/webrtc/common_video/libyuv/webrtc_libyuv.cc]
Depending of the format you are using, framesize should be ` width * height * 3`, `width * height + half_width * half_height * 2` ...

Best Regards,
Michel.

**Comment by lukelu0520** [comment]
Hi Michael, thanks for your prompt reply, after reviewing the source code [webrtc_libyuv.cc](https://github.com/pristineio/webrtc-mirror/blob/7a5bcdffaab90a05bc1146b2b1ea71c004e54d71/webrtc/common_video/libyuv/webrtc_libyuv.cc), we found that a pixel-format "YU12" is not listed in the code.

To our knowledge, pixel-format I420 is equivalent to YU12 in Linux device. So it's weird that WebRTC doesn't list YU12 format in its source code explicitly. 

Below is how to reproduce the error:
1. create a loopback v4l2 device: `sudo modprobe v4l2loopback video_nr=2`  
2. Test video into the device: `gst-launch-1.0 videotestsrc ! "video/x-raw,width=640, height=480,format=(string)I420" ! v4l2sink device=/dev/video2` 
3. Verify the device: `v4l2-ctl --all -d /dev/video2` ; it would show pixel format is YU12.
4. Go to webrtc-streamer/app/ use webrtc: `./webrtc-streamer` ; and use browser by localhost:8000 

We are finding a way to tell WebRTC that YU12 equals to I420, maybe could be done in CMakeLists.txt.

Hope to hear your expertise.

Best,
-- Luke

**Comment by mpromonet** [comment]
Hi Luke,

I think you can try to submit the issue to https://bugs.chromium.org/p/webrtc/issues/list, and maybe a pull request.
In the past I submit some small modification to avoid ugly workaround in this project, there were included in the main stream now.

Best Regards,
Michel.
