### ISSUE TITLE
Issue with empty ICE server list

### ISSUE THREAD

**Issue by neamjr** [mpromonet/webrtc-streamer#369]
If I turn off STUN with the `-s-` flag, the `getIceServers` api call returns this:

```
{
	"iceServers" : null
}
```

This causes an error in the client. The correct response should be:

```
{
	"iceServers" : []
}
```

I think this can be fixed on this line, but I don't have a working build (using the Docker image):

https://github.com/mpromonet/webrtc-streamer/blob/da0ea2bc9023aeffbec481fd774420dcf464b422/src/PeerConnectionManager.cpp#L405

**Comment by mpromonet** [comment]
Hi neamjr,

You are right, it should be something like `Json::Value urls(Json::arrayValue);`.
However if you have not any iceservers, I guess it will works only on LAN.

Best Regards,
Michel.

**Comment by neamjr** [comment]
Hi Michel,

Yes, that is correct. My use case is on a LAN without Internet connectivity.

Thanks,
Michael
