### ISSUE TITLE
Audio support

### ISSUE THREAD

**Issue by yaroslavert** [mpromonet/webrtc-streamer#372]
Hi i used this link rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov. Video  work good but audio do not work 

[https://webrtc-streamer.herokuapp.com/webrtcstreamer.html?video=rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov&audio=rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov](url)

**Comment by mpromonet** [comment]
Hi yaroslavert,

The audio codec supported list depend on WebRTC SDK, in case of Bunny demo url it is using audio/MPEG that is not supported.
You should see in the log something like 

> LiveAudioSource::onNewSession not support codec...

( see https://github.com/mpromonet/webrtc-streamer/blob/master/inc/liveaudiosource.h)

Best Regards,
Michel
