### ISSUE TITLE
Too many open files (sockets)

### ISSUE THREAD

**Issue by 9a4gl** [mpromonet/webrtc-streamer#39]
After a while when using webrtc streamer with a lot of rtsp different sources webrtc-streamer crash and prints to stderr:

Failed to DESCRIBE: unable to create stream socket: Too many open files
[err] evsignal_init: socketpair: Too many open files

for each camera switch
sudo lsof | grep <pid> | wc -l
it increase for about 2000+

**Comment by mpromonet** [comment]
Hi,
Clear the RTP subsession are not closed :)
I modified this is this commit https://github.com/mpromonet/webrtc-streamer/commit/19aca9fb6e5bfde42b3d3f8c375680aa09f8c8f8
It should leaks less.
Best Regards,
Michel.

**Comment by mpromonet** [comment]
Hi,
Do you still see filedescritors leaks ?
Regards
Michel.

**Comment by 9a4gl** [comment]
Hm, I got that while I was developing my webapp, during testing I got that after like 50-100 camera switching.. will test hopefully tomorrow and will report whether number of open files increase

**Comment by 9a4gl** [comment]
sudo lsof -p 10579 | wc -l
increases by 21-25 after switching camera
Today I found it with about 1000 files opened, when I start it has 63.
So I would say we still leak opened files.

**Comment by mpromonet** [comment]
Hi,
Thanks for the update.
Are you using WebRTC in debug ? 
If it reach filedescriptor above 1024, live555 select will failed.
Regards,
Michel.

**Comment by 9a4gl** [comment]
It looks when it reach 1024 it crash and then get restarted by systemd.
