### ISSUE TITLE
Can we run it on a 海思 or 联咏 motion camera? If you can, it's very cool.

### ISSUE THREAD

**Issue by zsinba** [mpromonet/webrtc-streamer#400]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mpromonet** [comment]
Hi zsinba,

It depends on what is motion camera protocol, anyway it is possible to extend backend supported protocols.
Implementing RMTP or multipart jpeg over http or ... need implementing another capturer that extend `rtc::VideoSourceInterface<webrtc::VideoFrame>`

Best Regards,
Michel.

**Comment by zsinba** [comment]
thanks  mpromonet：
I am very glad to receive your reply．
I haven't tried it on a motion camera yet. I have a hisi(海思) development board. I tried to run it on Hayes' board, but it didn't work.
The development of Hays is the structure of ARM. 
As you said, there is no WebRTC related content on this development board.
Do you have any suggestions if I want to run it on a Huawei Hisi(海思)or Motion Camera?


> Hi zsinba,
> 
> It depends on what is motion camera protocol, anyway it is possible to extend backend supported protocols.
> Implementing RMTP or multipart jpeg over http or ... need implementing another capturer that extend `rtc::VideoSourceInterface<webrtc::VideoFrame>`
> 
> Best Regards,
> Michel.

**Comment by zsinba** [comment]
My development board don't have the "rtc::VideoSourceInterface<webrtc::VideoFrame>" interface.  buy I could get the rtc frame binary data from the camera.

**Comment by mpromonet** [comment]
Hi,

I just made a google serach on Hisi development board, it seems an ARMv7 with a JPEG camera.
If the JPEG frames are available from V4L2 interface, it should work. I test the ARMv6 & ARMv7 build on a raspberry, I don't know if it can run on this board, you may need to make your build with this target.

Best Regards,
Michel.

**Comment by zsinba** [comment]
![image](https://user-images.githubusercontent.com/890157/113566237-e3dd4500-963e-11eb-9015-ddcab6c94e6e.png)


I tried to run it, but it didn't work.
You don't mention the compilation process in your documentation. Is there more documentation on compilation?

**Comment by zsinba** [comment]
> Hi,
> 
> I just made a google serach on Hisi development board, it seems an ARMv7 with a JPEG camera.
> If the JPEG frames are available from V4L2 interface, it should work. I test the ARMv6 & ARMv7 build on a raspberry, I don't know if it can run on this board, you may need to make your build with this target.
> 
> Best Regards,
> Michel.

raspberry  is work.  I do.

**Comment by mpromonet** [comment]
Hi,

The compilation is described in Dockerfile, for cross-compilation you can look to https://github.com/mpromonet/webrtc-streamer/blob/master/Dockerfile.rpi or https://github.com/mpromonet/webrtc-streamer/blob/master/Dockerfile.arm64.
You may start installing your target cross compiler and adapt cross compilation variables, after depending on result, you will have more or less work to do.

Best Regards,
Michel.

**Comment by zsinba** [comment]
I tried to compile it under HiLinux(海思). It didn't work out. The dependency is more.

Another, I tried using it under Raspberry. The image from the camera is very blurry, even if it is viewed by a self machine. Why is that?

**Comment by mpromonet** [comment]
Hi @zsinba 

Compiling WebRTC is probably a first step.

When the image is blurry (with grey squares) it may be when network is dropping lots of frames.
You could try to reduce the capture resolution to see if it becomes better. Another possibility if you have a V4L2 that support H264 capture (like raspicam does) is to use the `-o` option that allow H264 capture, reducing cpu ressource needed.

Best Regards,
Miche
