### ISSUE TITLE
Jitsi connection problem

### ISSUE THREAD

**Issue by ginolaku** [mpromonet/webrtc-streamer#408]
we want to use our local RTSP streams to Jitsi meet ,  rtsp stream can be shown in localhost:8000
try to use XMPPVideoRoom.html. https://meet.jit.si/XXXXXroom cannot see the rtsp streaming

even browsing online demo
https://webrtc-streamer.herokuapp.com/xmppvideoroom.html
the situation is the same. 

![未命名](https://user-images.githubusercontent.com/17745634/114560589-6ac59980-9c9f-11eb-8b82-90c6adbc39ea.png)

**Comment by mpromonet** [comment]
Hi @ginolaku,

It seems to not work anymore, it was always quite fragile, connection to jitsi, strophe & co need some work.... it seems more stable with janus-gateway.

Best Regards,
Michel.

**Comment by mpromonet** [comment]
I close this issue, because since the online demo is running with `-o` it stream only H264, and jitsi by default use VP8, then something need to be change to have a working situation.
