### ISSUE TITLE
no audio when connecting through ssl

### ISSUE THREAD

**Issue by Coennie** [mpromonet/webrtc-streamer#409]
Hi There,

I'm running the version 6.2 on windows. When starting the stream without ssl video and audio works. When starting the stream through ssl video works, but I do not get any audio.

Working audio / video with:
webrtc-streamer.exe -n vmix -u "vMix Video" -U "Line 1 (Virtual Audio Cable)"

No audio with:
webrtc-streamer.exe -n vmix -u "vMix Video" -U "Line 1 (Virtual Audio Cable)" -H8000r,7443s -c {{cert.pem}}

When opening chrome://webrtc-internals/ the RTCInboundRTPAudioStream shows all 0 on the package counts.

Does anyone else have this problem, and how can I debug/fix this?

Regards

**Comment by mpromonet** [comment]
Hi @Coennie 

This is strange that it could have a link between using https or http, maybe the problem is elsewhere.
Looking to the log, increase the verbosity could help you to collect more information.

Best Regards,
Michel.

**Comment by Coennie** [comment]
I've enabled the verbose, but can't figure out what is wrong. I've attached the log is this something you can help with?

https://drive.google.com/file/d/1kktHg3ogz4emCv6LBHLHPuw3lJQhvDJY/view?usp=sharing

regards
