### ISSUE TITLE
when I tried to watch two rtsp stream,it happens time delay

### ISSUE THREAD

**Issue by JokerSora** [mpromonet/webrtc-streamer#413]
what caused the delay,how can I do with the problem
so here is the constrator
rtsp stream (xxxx.xxxx.xxxx.1) => webrtc-streamer (xxxx.xxxx.xxxx.2) => web client (xxxx.xxxx.xxxx.3) that is ok

rtsp stream1 (xxxx.xxxx.xxxx.1:xxxx/a) rtsp stream2 (xxxx.xxxx.xxxx.1:xxxx/b) rtsp stream3 (xxxx.xxxx.xxxx.1:xxxx/c)  => webrtc-streamer (xxxx.xxxx.xxxx.2) => web client (xxxx.xxxx.xxxx.3) time delay happened

**Comment by JokerSora** [comment]
er ,now some rtsp stream may happend time delay,so what makes it delay?the net work error a while?or the getIceCandidate api just delayed as  the chrome has a limit of request at one time. why not use websocket to realize the request with no block?

**Comment by mpromonet** [comment]
Hi @JokerSora 

There is no problem to use websocket for signaling, as there is no emerging standard to do this (XMPP, different websocket implementation, ....), this project stay with the simplest signaling using ajax.
However if you like to implement websocket signaling, civetweb support it, so it needs some technical code to make the connection.

Best Regards,
Michel.
