### ISSUE TITLE
connect(videourl,'','') ,videourl，only support one parameters,the more will not be supported? 

### ISSUE THREAD

**Issue by jijiezh** [mpromonet/webrtc-streamer#415]
webRtcServer.connect("rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov"); this is correct.
webRtcServer.connect("rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov?a=1&b=2"); this will work wrong!
because, The call url: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov?a=1, which is not correct.
anybody konw why?
help!

**Comment by mpromonet** [comment]
Hi jijiezh,

You may enable some log, the code seems correct to me https://github.com/mpromonet/webrtc-streamer-html/blob/c144364baadf9edda0fab152a6f5ade55f51ebf5/webrtcstreamer.js#L90, it call encodeURIComponent before sending to server.
I made some simple tests and `&` seems correctly escaped, maybe you are using an old version ?

Best Regards,
Michel.
