### ISSUE TITLE
Provide binary for RPi Zero and 1

### ISSUE THREAD

**Issue by nistath** [mpromonet/webrtc-streamer#42]
The build provided by Travis CI currently does not work on a Raspberry Pi Zero W.
Would it be possible to add builds for the Pi Zero (armv6h) for future releases?

**Comment by nistath** [comment]
Here is gdb output:
```
(gdb) run
Starting program: /home/pi/wrtcstrm/webrtc-streamer
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x00053840 in rtc::LogMessage::LogMessage(char const*, int, rtc::LoggingSeverity, rtc::LogErrorContext, int, char const*) ()
```

**Comment by nistath** [comment]
I think it might have worked! https://travis-ci.org/mpromonet/webrtc-streamer/jobs/247299384
Can we get the binary released so that I can test it?

**Comment by mpromonet** [comment]
Hi,
It doesnot run on a raspberry pi B, compiler option or cross-compiler is not good.
Regards,
Michel.

**Comment by nistath** [comment]
Can you also please test [this build your travis-ci made](https://travis-ci.org/mpromonet/webrtc-streamer/jobs/249195228) and provide me the binary somehow so that I can also have a go at it?
Thank you for your work.

**Comment by mpromonet** [comment]
Hi nistath,
You can try https://github.com/mpromonet/webrtc-streamer/releases/download/v0.0.3/webrtc-streamer_v0.0.3_armv6.tgz, but it doesnot works on raspberry piB.
It exists with Illegal instruction, then probably it will not works on Pi Zero too.
Regards,
Michel.

**Comment by mpromonet** [comment]
Hi nistash,
After some numers of tries,  I build for armv6, the package https://github.com/mpromonet/webrtc-streamer/releases/download/v0.0.4/webrtc-streamer_v0.0.4_rpi-armv6.tgz is running on my raspberry pi B.
I guess it could run on a pi zero. The compilation of WebRTC have less feature, but it works with the raspbicam.
Let me know if it works.
Best Regards,
Michel.
