### ISSUE TITLE
Do not build with actuall webrtc

### ISSUE THREAD

**Issue by petervarkoly** [mpromonet/webrtc-streamer#422]
Hallo!
I have started to build as written in README. But the during make an error occurs:

```
...
[ 99%] Building CXX object CMakeFiles/webrtc-streamer.dir/src/rtspaudiocapturer.cpp.o
[ 99%] Building CXX object CMakeFiles/webrtc-streamer.dir/src/rtspvideocapturer.cpp.o
make[2]: *** No rule to make target '../webrtc/src/out/Release/obj/libwebrtc.a', needed by 'webrtc-streamer'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:194: CMakeFiles/webrtc-streamer.dir/all] Error 2
make: *** [Makefile:169: all] Error 2
```

The directory ../webrtc/src/out/Release/obj/ does not exsits:
ls -lt ../webrtc/src/out/Release/
total 4
-rw-r--r-- 1 petervarkoly 384 Jun  4 13:12 args.gn
petervarkoly@fujitsu ~/123/webrtc-streamer (master)>

**To Reproduce**
```
pushd ..
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
export PATH=$PATH:`realpath depot_tools`
popd
mkdir ../webrtc
pushd ../webrtc
fetch --no-history webrtc 
popd
cmake . && make
```

**Expected behavior**
Should not occur an error :-)

**Comment by mpromonet** [comment]
Hi,

The important error is probably before the one you are showing, that says that webrtc lib is not found.

Best Regards,
Michel.
