### ISSUE TITLE
How should I bind the domain name in Windows environment

### ISSUE THREAD

**Issue by UkVOSklF** [mpromonet/webrtc-streamer#426]
How should I bind the domain name in Windows environment

Thank you for your answer

**Comment by UkVOSklF** [comment]
Since the default service address is now 127.0.0.1:8000, I want to bind my domain name and set HTTPS for it. So how do I do that?

**Comment by mpromonet** [comment]
Hi,

It's up to you to set the listenning address, by default it is `0.0.0.0:8000`, not `127.0.0.1:8000`. The `-H` option is forward to  civetweb `listening_ports`, so you can use the civetweb syntax.

Best Regards,
Michel.
