### ISSUE TITLE
Cannot run webrtc-streamer on windows 10

### ISSUE THREAD

**Issue by pengcx123** [mpromonet/webrtc-streamer#428]
**Describe the bug**
I download the web-streamer for windows, and use below command to run web-streamer:
webrtc-streamer rtsp://localhost/32050000001120000569_0500000570
It exit with error
**To Reproduce**
1. run webrtc-streamer rtsp://localhost/32050000001120000569_0500000570

**Expected behavior**
It can start and run ok

**Screenshots**
D:\temp\webrtc-streamer-v0.6.4-Windows-AMD64-Release\webrtc-streamer-v0.6.4-Windows-AMD64-Release>webrtc-streamer rtsp://localhost/32050000001120000569_0500000570
Version:v0.6.4/Windows-AMD64 civetweb@v1.13 webrtc@82aa094a97-dirty live555helper@d351689
{
        "urls" :
        {
                "rtsp://localhost/32050000001120000569_0500000570" :
                {
                        "video" : "rtsp://localhost/32050000001120000569_0500000570"
                }
        }
}Logger level:3
[000:000][18008] (audio_device_generic.cc:28): BuiltInAGCIsAvailable: Not supported on this platform
[000:000][18008] (audio_device_generic.cc:38): BuiltInNSIsAvailable: Not supported on this platform
HTTP Listen at 0.0.0.0:8000
cannot bind to 0.0.0.0:8000: 10048 (No error)
Failed to setup server ports
Cannot Initialize start HTTP server exception:null context when constructing CivetServer. Possible problem binding to port.
Exit

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pengcx123** [comment]
We will setup the application on Linux

**Comment by mpromonet** [comment]
Hi pengcx123,

It is surely a better way to use Linux, it build on windows, but some features are not implmented in windows.
By the way it seems it fails to listen on port 8000. 
Commonly on windows a popup is openned to ask persmission to bind port. 

Best Regards,
Michel.

**Comment by pengcx123** [comment]
Thanks for your quick reply, it is very helpful.
I closed this issue and will test on linux later.




------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Michel ***@***.***&gt;;
Send time:&nbsp;Monday, Jul 12, 2021 5:41 PM
***@***.***&gt;; 
***@***.***&gt;; "State ***@***.***&gt;; 
Subject: &nbsp;Re: [mpromonet/webrtc-streamer] Cannot run webrtc-streamer on windows 10 (#428)





 
Hi pengcx123,
 
It is surely a better way to use Linux, it build on windows, but some features are not implmented in windows.
 By the way it seems it fails to listen on port 8000.
 Commonly on windows a popup is openned to ask persmission to bind port.
 
Best Regards,
 Michel.
