### ISSUE TITLE
how to install in centos?  I run the docker, but it doesn't work.

### ISSUE THREAD

**Issue by zhuchuanyue** [mpromonet/webrtc-streamer#429]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mpromonet** [comment]
Hi zhuchuanyue,

In order to receive help, you need to describe what means "doesn't work".
Maybe some error messages ?

Best Regards,
Michel.

**Comment by zhuchuanyue** [comment]
![image](https://user-images.githubusercontent.com/22437781/125266730-af151400-e338-11eb-8fbc-3af14e9d6eb9.png)

**Comment by mpromonet** [comment]
Hi zhuchuanyue,

Then it is running and receive calls. If you don't have video, it maybe because of ICE negociation in docker. Adding `--net=host` may help.

Best Regards,
Michel.

**Comment by zhuchuanyue** [comment]
ok，thanks, I can have the  video.

**Comment by zhuchuanyue** [comment]
![image](https://user-images.githubusercontent.com/22437781/125381382-5f7d2980-e3c6-11eb-9b12-ab7c53dc5066.png)

Hi, I open one live  video,  the cpu is over 100%,  how  can  I   resolve  this   question ?

**Comment by mpromonet** [comment]
Hi zhuchuanyue,

An option to reduce the cpu consomption is to use the `-o` argument, it works only for H264 source and will forward the frame. Then there is no possible adaptation (codec, scale, gop, ....) but it use less cpu removing decoding/encoding.

Best Regards,
Michel.

**Comment by zhuchuanyue** [comment]
yes, I try it  by use the -o,  the cpu reduced,  but  the video loading is slow， about  10 seconds.

**Comment by mpromonet** [comment]
Hi,

This depends on the gop of your backend, the first image need to wait for an I-frame, appending more I-frame to the backend stream should reduce this.

Best Regards,
Michel.

**Comment by szueric** [comment]
遇到跨域的问题，怎么处理，请高手帮忙？

```
Access to fetch at 'http://192.168.12.19:18010/api/call?peerid=0.8798291299329237&url=rtsp%3A%2F%2F192.168.12.231%3A8557%2Fh264&options=rtptransport%3Dtcp%26timeout%3D60' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by lizhen789** [comment]
windows11 下
![image](https://user-images.githubusercontent.com/35031472/175527724-ee95e4a3-ecb4-405e-8614-ae7ab0b5cd7f.png)

**Comment by mpromonet** [comment]
Hi @lizhen789 

May you read the issue before posting something that seems completly different issue.... windows and centos seems different os ?

Thanks,
Michel.
