### ISSUE TITLE
cant handle rtsp address

### ISSUE THREAD

**Issue by liyoubdu** [mpromonet/webrtc-streamer#431]
webrtc-streamer  can not handle the rtsp format below:
`./webrtc-streamer rtsp://192.168.1.5:12345/live?skip&video=1&audio=1&intervieweeID=263`

commit: 4922c95934b084a0f97a239d838dd36969ee1f99

**Comment by mpromonet** [comment]
Hi,

I guess you have a problem in the way you pass the parameter.
Did you tried  like this ?

`./webrtc-streamer "rtsp://192.168.1.5:12345/live?skip&video=1&audio=1&intervieweeID=263"`

Best Regards,
Michel.

**Comment by liyoubdu** [comment]
> Hi,
> 
> I guess you have a problem in the way you pass the parameter.
> Did you tried like this ?
> 
> `./webrtc-streamer "rtsp://192.168.1.5:12345/live?skip&video=1&audio=1&intervieweeID=263"`
> 
> Best Regards,
> Michel.

it works. thank you

**Comment by liyoubdu** [comment]
use ./webrtc-streamer "rtsp://192.168.1.5:12345/live?skip&video=1&audio=1&intervieweeID=263". and it works.
