### ISSUE TITLE
Streamer gets 'Core dump' when compiling WebRTC with Debug configuration

### ISSUE THREAD

**Issue by ihabZhaika** [mpromonet/webrtc-streamer#434]
Hey,
I tried to compile the streamer with 'Release' settings then tried to stream file and it work as it should, now i switched the Libwebrtc build to "Debug" on the CMake file, after compiling the streamer and run it, when I  open a web page for watching the streamed video it get core dump as the following:
![image](https://user-images.githubusercontent.com/17564219/126074550-425e3eed-0432-42b4-91d8-f6fc75ad0fd8.png)

This is the system settings that I am running on:
![image](https://user-images.githubusercontent.com/17564219/126074576-7d9e337a-98ef-4a57-8164-b6b05240d0b8.png)
The VM is hosted on Azure, spec: 8 cores, 16GB of RAM, I access via SSH then I run the streamer

To reproduce it follow the following steps:

1. Clone the code, make sure the commit is: 4922c95934b084a0f97a239d838dd36969ee1f99
2. Change the build type in the CmakeList file from 'Release' to 'Debug', i.e: set (CMAKE_BUILD_TYPE "Debug")
3. Run cmake .
4. Run make
5. Run the following command "./webrtc-streamer -N 4  -n video3 -u rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov"
6. Open the browser on the server IP and the streamer will get Core Dump

Any suggestions to mitigate the issue ?

**Comment by mpromonet** [comment]
Hi,

This is a bug, usage of audio stuff doesnot follow webrtc sdk thread access check.
It may works disabling audio wiht `-a` option ?

Best Regards,
Michel.

**Comment by ihabZhaika** [comment]
> Hi,
> 
> This is a bug, usage of audio stuff doesnot follow webrtc sdk thread access check.
> It may works disabling audio wiht `-a` option ?
> 
> Best Regards,
> Michel.

It helped with the TRSP video, it do work now with the -a.
For other streams still crashing, see the following image
![image](https://user-images.githubusercontent.com/17564219/126077173-6ef202b2-ec2f-46f9-92ea-07e877094de6.png)

**Comment by mpromonet** [comment]
Hi,

This seems a very different problem, maybe B-frame bad managed by WebRTC SDK ?

Best Regards,
Michel.

**Comment by ihabZhaika** [comment]
> Hi,
> 
> This seems a very different problem, maybe B-frame bad managed by WebRTC SDK ?
> 
> Best Regards,
> Michel.

Not sure, 
I tried the null codec [ -o ], it do work now without crashing but I have to keep those flags -a -o, in addition I keep getting the following
![image](https://user-images.githubusercontent.com/17564219/126077919-e82e6bbe-0524-469a-a6b8-89996154db61.png)
