### ISSUE TITLE
[1276:438][29132] (livevideosource.h:175): LiveVideoSource: onData no decoder NOTIFY failed

### ISSUE THREAD

**Issue by heyikang** [mpromonet/webrtc-streamer#437]
**Is your feature request related to a problem? Please describe.**
I'm not sure if this is a bug or a feature. This problem occurred when I connected the camera

**Describe the solution you'd like**
Add a new decoder?

**Describe alternatives you've considered**
no

**Additional context**
System  Windows 10 Pro x64 19042.1110
webrtc-streamer  last release

**Comment by heyikang** [comment]
The above problem does not exist in VLC media player, it can be played normally

**Comment by heyikang** [comment]
![question](https://user-images.githubusercontent.com/34233756/128159873-46440414-0e53-44c9-a2e6-a4564c396679.png)

**Comment by mpromonet** [comment]
Hi,

Probably in the logs there is something like format not supported.

Best Regards,
Michel.

**Comment by heyikang** [comment]
@mpromonet Thanks for your help, how can I solve this problem

**Comment by mpromonet** [comment]
Hi,

I think you have choice between using a supported format (H264, VP9, JPEG) or implementing the decoder for your format.

Best Regards,
Michel.

**Comment by heyikang** [comment]
@mpromonet Thanks for your help
