### ISSUE TITLE
build error with latest webrtc(4th augst 2021 lkgr)

### ISSUE THREAD

**Issue by rahul3349** [mpromonet/webrtc-streamer#439]
Getting below build errors while using webrtc from 4th august 2021 lkgr branch.

[100%] Linking CXX executable webrtc-streamer
/home/rbhagwat/sources/webrtc/src/out/Release/obj/third_party/jsoncpp/jsoncpp/json_value.o: In function `Json::Value::Value(char const*)':
json_value.cpp:(.text+0x118): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
json_value.cpp:(.text+0x168): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
/home/rbhagwat/sources/webrtc/src/out/Release/obj/third_party/jsoncpp/jsoncpp/json_value.o: In function `Json::Value::Value(char const*, char const*)':
json_value.cpp:(.text+0x10c): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
/home/rbhagwat/sources/webrtc/src/out/Release/obj/third_party/jsoncpp/jsoncpp/json_value.o: In function `Json::Value::Value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
json_value.cpp:(.text+0x10c): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
/home/rbhagwat/sources/webrtc/src/out/Release/obj/third_party/jsoncpp/jsoncpp/json_value.o: In function `Json::Value::dupPayload(Json::Value const&)':
json_value.cpp:(.text+0x1c0): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
/home/rbhagwat/sources/webrtc/src/out/Release/obj/third_party/jsoncpp/jsoncpp/json_value.o:json_value.cpp:(.text+0xb0): more undefined references to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()' follow
../webrtc/src/out/Release/obj/libwebrtc.a(peer_connection_interface.o): In function `webrtc::PeerConnectionInterface::RTCConfiguration::RTCConfiguration(webrtc::PeerConnectionInterface::RTCConfiguration const&)':
peer_connection_interface.cc:(.text+0x1e4): undefined reference to `__aarch64_ldadd4_relax'
../webrtc/src/out/Release/obj/libwebrtc.a(peer_connection_interface.o): In function `webrtc::PeerConnectionInterface::RTCConfiguration::~RTCConfiguration()':
peer_connection_interface.cc:(.text+0xac): undefined reference to `__aarch64_ldadd4_acq_rel'
../webrtc/src/out/Release/obj/libwebrtc.a(basic_port_allocator.o): In function `cricket::BasicPortAllocatorSession::~BasicPortAllocatorSession()':
basic_port_allocator.cc:(.text+0x1e0): undefined reference to `__aarch64_ldadd4_acq_rel'
../webrtc/src/out/Release/obj/libwebrtc.a(basic_port_allocator.o): In function `cricket::BasicPortAllocatorSession::StartGettingPorts()':
basic_port_allocator.cc:(.text+0x68): undefined reference to `__aarch64_ldadd4_relax'
../webrtc/src/out/Release/obj/libwebrtc.a(basic_port_allocator.o): In function `cricket::BasicPortAllocatorSession::ClearGettingPorts()':
basic_port_allocator.cc:(.text+0x94): undefined reference to `__aarch64_ldadd4_relax'
../webrtc/src/out/Release/obj/libwebrtc.a(basic_port_allocator.o): In function `cricket::BasicPortAllocatorSession::DoAllocate(bool)':
basic_port_allocator.cc:(.text+0x25c): undefined reference to `__aarch64_ldadd4_relax'
basic_port_allocator.cc:(.text+0x410): undefined reference to `__aarch64_ldadd4_relax'
../webrtc/src/out/Release/obj/libwebrtc.a(basic_port_allocator.o): In function `cricket::BasicPortAllocatorSession::GetPortConfigurations()':
basic_port_allocator.cc:(.text+0xc8): undefined reference to `__aarch64_ldadd4_relax'
../webrtc/src/out/

**Comment by mpromonet** [comment]
Hi,

It look like a mix of cflags options between webrtc sdk build and webrtc-streamer.
You may look to Dockerfile.arm64, I just run a build that passed https://cirrus-ci.com/task/4833745950736384

Best Regards,
Michel.
