### ISSUE TITLE
How to remove a network request to stun.lgoogle.com

### ISSUE THREAD

**Issue by yangjieshao** [mpromonet/webrtc-streamer#440]
The LAN environment hopes to modify / remove data requests to Google's servers through configuration
![Snipaste_2021-08-07_17-06-20](https://user-images.githubusercontent.com/3275834/128595135-0f5c79da-612c-43d7-b491-338ccf4d7f13.png)

**Comment by mpromonet** [comment]
Hi,

This is the default stun, you can change it using the -s option:
`         -s[stun_address]                   : use an external STUN server (default:stun.l.google.com:19302 , -:means no STUN)
` 
Best Regards,
Michel.

**Comment by yangjieshao** [comment]
thanks
