### ISSUE TITLE
CPU usage too high

### ISSUE THREAD

**Issue by yangjieshao** [mpromonet/webrtc-streamer#441]
**Describe the bug**
One 4K RTSP video occupies more than 40% of CPU
![Snipaste_2021-08-07_17-09-24](https://user-images.githubusercontent.com/3275834/128595393-9fa92d0e-213e-4d6b-847d-02d7c4d38955.png)
One 1080p RTSP video occupies more than 10% of CPU
![image](https://user-images.githubusercontent.com/3275834/128595510-11c82d7d-d1bb-4576-a263-6226df8ddb8c.png)

**Desktop (please complete the following information):**
 - OS:  Windows10  21H1 19043.1110
 - Browser: Edge  92.0.902.62
![Snipaste_2021-08-07_17-11-42](https://user-images.githubusercontent.com/3275834/128595454-cfd2b5af-f8b4-4c7a-8379-aa35e6b0ec80.png)

![image](https://user-images.githubusercontent.com/3275834/128595446-7e9b8608-e120-45f9-8ea7-e3bc9161b2c8.png)

**Comment by mpromonet** [comment]
Hi,

By default video is decoded and encoded, this is using resource. You can try the `-o` option that forward RTP packet.

Best Regards,
Michel.

**Comment by yangjieshao** [comment]
thanks
