### ISSUE TITLE
webrtc-streamer can't play RTSP stream from mp4 file .

### ISSUE THREAD

**Issue by teo-tsou** [mpromonet/webrtc-streamer#449]
**Describe the bug**
Hello!
So I created a RTSP stream from:  ffmpeg -re -stream_loop -1 -i mj.mp4 -f rtsp rtsp://localhost:8554/mystream 
My RTSP server is RTSP simple server.
I tested the RTSP link on VLC and everything looks fine.

But when I run ./webrtc-streamer rtsp://localhost:8554/mystream 

```
[000:000][4487] (audio_device_pulse_linux.cc:1605): failed to connect context, error=-1
[000:000][4487] (audio_device_pulse_linux.cc:145): failed to initialize PulseAudio
[000:000][4487] (audio_device_impl.cc:341): Audio device initialization failed
(PeerConnectionManager.h:235): virtual void PeerConnectionManager::PeerConnectionObserver::OnSignalingChange(webrtc::PeerConnectionInterface::SignalingState) state:0 peerid:0.09352491457674716
 Requested URL : rtsp://localhost:8554/mystream
```

Then I tried to put video and audio encoding by this: ffmpeg -re -nostdin -i mj.mp4 -vcodec libx264 -preset:v ultrafast -acodec aac  -f rtsp rtsp://localhost:8554/mystream

Then the logs of  `./webrtc-streamer rtsp://localhost:8554/mystream` were these:

![image](https://user-images.githubusercontent.com/56459281/134350811-b38d344a-ce5a-491b-a149-114b0fec6feb.png)

And nothing was displayed on the browser. Can you please help me?

I also can't see any of your rstp urls that you have put on the config.json file. Seems that the video display doesn't work at all.

**Comment by mpromonet** [comment]
Hi Theodoros,

It seems the RTSP consumer cannot get SPS & PPS frame that are needed to uncompress H264.
Probably something in https://github.com/mpromonet/webrtc-streamer/blob/master/inc/livevideosource.h fails, you may look to verbose logs.
Looking to the code, it seems there is a problem when SPS/PPS are not in the sprops-parameters, there is no marker in such a case. I will have a look.

Best Regards,
Michel.

**Comment by teo-tsou** [comment]
Is there any other way to stream a local file with webRTC?

**Comment by mpromonet** [comment]
Hi,

Mkv file with H264, JPEG, VP8, VP9 frames could be streamed using `file://<path to mkv>`.

Best Regards,
Michel.

**Comment by teo-tsou** [comment]
Ok problem solved. Actually, I was running webrtc streamer inside Kubernetes Pod and I couldn't reach STUN. I was able solving this by using host network.
