### ISSUE TITLE
Wrong incoming frame length

### ISSUE THREAD

**Issue by niXman** [mpromonet/webrtc-streamer#452]
hi,

just now I have successfully built master branch and I am trying to start streaming.
I have two v4l2 loopback devices with the following characteristics:
```
ffprobe /dev/video0

Input #0, video4linux2,v4l2, from '/dev/video0':

Duration: N/A, start: 17479.219834, bitrate: 331776 kb/s

Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720, 331776 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc
```
```
ffprobe /dev/video1

Input #0, video4linux2,v4l2, from '/dev/video1':

Duration: N/A, start: 17481.786751, bitrate: 117964 kb/s

Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 640x512, 117964 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc
```
the problem is that I can successfully receive a stream for `/dev/video1`, but for `/dev/video0` I get the following error:
```
[047:963][8324] (video_capture_impl.cc:132): Wrong incoming frame length.
```

any ideas?

best!

**Comment by mpromonet** [comment]
Hi,

It's seems a glitch in v4l2sink of gstreamer ?

Best Regards,
Michel.

**Comment by niXman** [comment]
Yes it is possible...

**Comment by sulim-vladimir** [comment]
Working solution can be found here:
https://github.com/umlaeute/v4l2loopback/issues/190
