### ISSUE TITLE
Is this based on transcoding?

### ISSUE THREAD

**Issue by wojtkowiak** [mpromonet/webrtc-streamer#46]
Hey, quick question.
Is the H264 frame from RTSP stream decoded first and then reencoded to VP8 by WebRTC?
Would it be possible to pass the H264 frame directly to WebRTC without reencoding?

**Comment by mpromonet** [comment]
Hi wojtkowiak,
Yes the H264 stream is decoded and then reeconded in the codec netociated by WebRTC, it could be VP8, VP9, H264, ...
Last time I tried, sending H264 frame to VideoCapturer doesnot works, but maybe recent update of WebRTC allow to forward H264 frames ? 
If you like to have a lightweigth solution, you should look to [janus-gateway](https://github.com/meetecho/janus-gateway)
Best Regards,
Michel.
