### ISSUE TITLE
CPU usage too high with "-o" in docker

### ISSUE THREAD

**Issue by yangjieshao** [mpromonet/webrtc-streamer#464]
**Describe the bug**
CPU usage too high with "-o" in docker

```
docker pull mpromonet/webrtc-streamer
```
```
docker run --restart=always -d --network=host \
           --name webrtc-streamer \
           mpromonet/webrtc-streamer \
           -o -s- -Txxx:xxx@127.0.0.1:3478
```

**Screenshots**
![e7721b46cb22c35f4d8ba1f264b8e90](https://user-images.githubusercontent.com/3275834/143546650-8d7266ab-68f1-4c76-b9e6-9a1fc0941964.png)
![3c8eebfc6a8537190ffb46c4466a76a](https://user-images.githubusercontent.com/3275834/143546658-25772cfd-4a2b-4b15-b280-5fad630dde9c.png)
![4a0a978de5d865c84ccafd7b206023e](https://user-images.githubusercontent.com/3275834/143546682-4dd76d01-ecdc-4613-a01d-aae3deae787a.png)

**Desktop (please complete the following information):**
 - OS:  (docker) Linux version 3.10.0-1160.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Mon Oct 19 16:18:59 UTC 2020 
 - Browser chrome
 - Version v0.6.5-1-gfc3a3d1/Linux-x86_64 civetweb@v1.13 webrtc@a52fc6f940-dirty live555helper@91b1b98

**Comment by mpromonet** [comment]
Hi,

You may use an SFU like janus-gateway ?

Best Regards,
Michel.
