### ISSUE TITLE
unable to open display

### ISSUE THREAD

**Issue by mikefeng-max** [mpromonet/webrtc-streamer#471]
Hello, I use webrtc streamer for video streaming in centos7 environment. But I didn't succeed. As shown in the figure. Could you help me
![error](https://user-images.githubusercontent.com/56988159/146774674-eaf2cf67-917b-4510-a5c4-f09b54d9050c.png)

**Comment by mpromonet** [comment]
Hi,

Increasing the log level may help you to localize the problem.

Best Regards,
Michel.

**Comment by mikefeng-max** [comment]
thanks mpromonet：
I am very glad to receive your reply．
The problem I encountered was that I could not create a datachannel open. Webrtc streamer cannot be used when it is placed on the ECS. However, it can be used normally on the local server.
<img width="950" alt="error1" src="https://user-images.githubusercontent.com/56988159/146857265-3805def0-91c9-4fe9-8c42-ad68448564f1.png">
<img width="950" alt="error2" src="https://user-images.githubusercontent.com/56988159/146857266-e05f97be-94c2-431e-8e88-09681d3033a3.png">

**Comment by mpromonet** [comment]
Hi,

I think opening or not the datachannel is a consequence of ICE negociation/enumeration. In the case that fails it seems candidate is not valid (172.19.45.79), it looks like an internal docker ip. 

Best Regards,
Michel.

**Comment by mikefeng-max** [comment]
Hi Michel,
Thanks a lot for pointing me to the right direction. I will try it out.
