### ISSUE TITLE
Limit no of peers connecting to webrtc-streamer

### ISSUE THREAD

**Issue by Dhoa08** [mpromonet/webrtc-streamer#475]
Hi Michel, 

Is there a way to limit the no of clients connecting to the webrtc-streamer. I have 4 rtsp cameras and a dual core machine. With one client my cpu utilization is over 70%. Every new client increases the cpu utilization by 30 percent.  I am running the streamer without any codec and would like to limit the number of users being able to connect simultaneously to maybe 3. Can it be done easily? I would appreciate your insight.

Thanks and regards,
Abhishek

**Comment by mpromonet** [comment]
Hi Abhishek,

There is no way to do this for now, it may a nice improvement. It is probably possible to limit this refusing the peerconnection creation when number of peerconnection for a stream is above a limit.

Best Regards,
Michel.

**Comment by Dhoa08** [comment]
Hi Michel,
Thank you for your reply. I will try it out.
Thanks and regards,
Abhishek

**Comment by johanehr** [comment]
Hi Michel and Abhishek! 

The CPU usage is something that could potentially become problematic for multiple peers in my use case, especially if a browser tab is left open. Perhaps there could be an option to limit the number of simultaneous peers, and to either refuse new PeerConnections (like you suggested), or drop the oldest peer. Personally, I think dropping the oldest peer would make the most sense as a default, for example on websites where a new visitor expects to gain access to a stream immediately (like live webcams).

Best regards,
Johan

**Comment by mpromonet** [comment]
Hi Johan,

Sure, you may submit a PR to implement this.

Best Regards,
Michel.

**Comment by vegalou** [comment]
If webrtc-streamer is behind R-Proxy of Apache, try mod_qos or mod_limitipconn to LIMIT client connections.

Another easy solution, loop a connection counter in system, web page check connection count in JS.

Exit page when connection over the limit.
