### ISSUE TITLE
How to change option for iframe, plz add x-frame-options parameter

### ISSUE THREAD

**Issue by HWANGHyeonBo** [mpromonet/webrtc-streamer#482]
Dear You.
You're using a Raspberry Pi 4 and you're making good use of your software.
I modified main.cpp/212 to work in iframe and tried to build it, but failed a lot.
It would be appreciated if you could add 'X-Frame-Options' as an option in armv7l for pi.
Thank you.

**Comment by mpromonet** [comment]
Hi,

The header X-Frame-Options is set to "SAMEORIGIN", this should allow to open in an iframe.

Best Regards,
Michel.
