### ISSUE TITLE
support WHIP protocol

### ISSUE THREAD

**Issue by jonassmedegaard** [mpromonet/webrtc-streamer#485]
This project seems a good candidate for embracing the new WebRTC-based streaming protocol WHIP.

The author of janus can introduce it much better than I can: https://www.meetecho.com/blog/whip-janus-part-ii/

**Comment by mpromonet** [comment]
Hi @jonassmedegaard 

Maybe, you may submit a PR to implement it.

Best Regards,
MicheL

**Comment by mpromonet** [comment]
Hi,

Thanks for the sharing, it seems quite close to the /api/call approach that receive an SDP offer and answer with an SDP answer.
Another possible interoperability is xmpp or others...

Best Regards,
Michel.

**Comment by mpromonet** [comment]
Hi Jonas,

I dig a bit more in whip, and it does not seems to be interesting.
This project is, mainly, publishing webrtc stream. WHIP is for webrtc ingestion, I made some tries in  https://github.com/mpromonet/webrtc-streamer/tree/whip, I will probably merge it but for now incoming webrtc stream are not used.

Best Regards,
Michel.

**Comment by mpromonet** [comment]
Hi,

Digging a bit more in this protocol, it is not really interesting it is about injection, then I change the code to support WHEP that is about streaming.

 I made a small test with https://github.com/mpromonet/webrtc-streamer-whep that use this api through the component https://github.com/Eyevinn/whep-video-component.

Best Regards,
Michel.
