### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by jianxin123** [mpromonet/webrtc-streamer#492]
the console prints:
      Invalid URI. Load of media resource  failed.
      This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”
      Get IceServers
      Invalid URI. Load of media resource  failed.
      Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://192.168.1.122:8000/api/getIceServers. (Reason: CORS request did not succeed). Status code: (null)
      onError:getIceServers TypeError: NetworkError when attempting to fetch resource.

and I can see the frame when I use vlc ,so the rtsp source maybe has no problem.  And I use the latset Relsease version of webrtc-streamer.PLS help me thanks

**Comment by jianxin123** [comment]
should I  change 192.168.1.122

**Comment by mpromonet** [comment]
Hi,

If html/js file and backend api comes from same url, everything comes from same origin.
Probably you insert a proxy between webrtc-streamer and the webbrowser that remove CORS headers.

Best Regards,
Michel.

**Comment by jianxin123** [comment]
sorry,its my mistake. I have solved the problem.thank you  .
