### ISSUE TITLE
Binding request timed out from 192.168.0.x:62323

### ISSUE THREAD

**Issue by xingkongdeweilai** [mpromonet/webrtc-streamer#494]
![image](https://user-images.githubusercontent.com/31369019/161362294-5b55c774-8906-4a7a-91de-195f0587b2e4.png)

The page cannot play videos，and non-stop Requested URL. No problem with rtsp，it can be play。

**Comment by xingkongdeweilai** [comment]
I guess the problem comes from UDP，but i cannot resolve

**Comment by mpromonet** [comment]
Hi,

Probably increasing log level will help you.
Anyway it is possible that your RTSP server doesnot suppot RTP over TCP, that is set by default in https://github.com/mpromonet/webrtc-streamer-html/blob/master/webrtcstreamer.json
```
options: "rtptransport=tcp&timeout=60"
```

Best Regards,
Michel.

**Comment by xingkongdeweilai** [comment]
Thanks, it has been solved，the reason is that the camera encoding is set to H.264, not H.265

**Comment by smallPlanet123** [comment]
I set it to h265 and it still doesn't work

**Comment by smallPlanet123** [comment]
> 

I set it to h265 and it still doesn't work
