### ISSUE TITLE
Use webrtc streamer to play RTSP video in Linux environment. How to install CentOS? Docker runs and cannot go on in case of error ((thread. CC: 798): unable to create pthread, error 1)

### ISSUE THREAD

**Issue by hzl1015** [mpromonet/webrtc-streamer#498]
**Describe the bug**
Use webrtc streamer to play RTSP video in Linux environment. How to install CentOS? Docker runs and cannot go on in case of error ((thread. CC: 798): unable to create pthread, error 1)

**To Reproduce**
1.yum install docker
2.systemctl start docker
3.docker pull mpromonet/webrtc-streamer
4.docker run -itd -p 8000:8000 --name webrtc-streamer mpromonet/webrtc-streamer
5. docker ps
6.docker logs 6b06a101826a ，  You will encounter (thread.cc:798): Unable to create pthread, error 1错误
7.telnet 127.0.0.1 8000
8.netstat -apn|grep 8000

**Expected behavior**
Want to successfully use webrtc streamer to play RTSP video in Linux environment. Using docker, you can start webrtc streamer

**Screenshots**
<img width="931" alt="image1" src="https://user-images.githubusercontent.com/104478114/165454935-e08c91db-3752-4371-9a98-f71432011d31.png">
<img width="978" alt="image2" src="https://user-images.githubusercontent.com/104478114/165455128-95f8e1bb-f046-4030-ba08-282339ba002d.png">
<img width="821" alt="image3" src="https://user-images.githubusercontent.com/104478114/165455278-b83bc6f6-f9a8-40c0-ae4c-15d2239492df.png">
<img width="708" alt="image4" src="https://user-images.githubusercontent.com/104478114/165455383-8310eb27-f282-48d1-bc06-e589425af80c.png">
<img width="778" alt="image5" src="https://user-images.githubusercontent.com/104478114/165455405-2e97d879-a70d-4acb-adca-5ee16b22b71f.png">
<img width="765" alt="image6" src="https://user-images.githubusercontent.com/104478114/165455430-e98e6c26-79fd-4778-97e1-d9a8f7bfcf74.png">

**Desktop (please complete the following information):**
 - Version Linux version 3.10.0-1062.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Wed Aug 7 18:08:02 UTC 2019
<img width="1044" alt="image11" src="https://user-images.githubusercontent.com/104478114/165455479-4b5bf70e-b7ee-4155-8810-3ed666b8034b.png">

**Smartphone (please complete the following information):**
![image22](https://user-images.githubusercontent.com/104478114/165455491-7a5f1b6f-1b4c-4b17-981d-b5a691372c8b.png)

**Additional context**
If you want to use webrtc streamer to play RTSP video in Linux environment, you can directly run webrtc streamer and report an error. You need to upgrade glbic and GCC (abandon this method). Therefore, I used docker to install, but I also encountered an error. At present, I can't find any solution. Please ask for help

**Comment by mpromonet** [comment]
Hi,

You probably need to use a kernel more up to date.

Best Regards,
Michel.

**Comment by hzl1015** [comment]
OK, thank you. The problem has been solved

**Comment by lijiajun3029** [comment]
If you are worried that updating the kernel will bring additional bugs, you probably need to use an older webrtc-streamer.
for example:
`docker pull mpromonet/webrtc-streamer:v0.6.5`

**Comment by caihanze** [comment]
> OK, thank you. The problem has been solved

how to solve it?
