### ISSUE TITLE
Question about how to use extern TURN server

### ISSUE THREAD

**Issue by LijunLiu1996** [mpromonet/webrtc-streamer#499]
Hi, mpromonet!
	Sorry to interupt! I'm trying to use webrtcstreamer to transfer rtsp stream to webrtc stream and display it on the website.
your project runs perfectly on the LAN, but my ultimate goal is to display streams over the public network. Since my LAN computer A 
doesn't have a public IP, I rented a cloud server which has a public IP and installed coturn on it as the turnserver and I've downloaded 
_webrtc-streamer-v0.6.5-Windows-AMD64-Debug.tar.gz_ in my computer A, 
then I ran webrtrc-streamer.exe -H 192.168.x.x:8080 -s- -tMyTurnserverInfo on my computer A. 
Both my LAN computer A and my laptop B(under another LAN) has passed the Trickle ICE test.
What I'm confused is that how to use my laptop B to fetch the stream? I cannot connect 192.168.x.x:8080 with my laptop.
This question may seems too basic, but I would appreciate it so much if you could teach me how to do next.
Best Regards,
Fiona.L

**Comment by mpromonet** [comment]
Hi Fiona,

If I follow well, you just miss to redirect the port from your router to 192.168.x.x:8080.

Best Regards,
Michel.

**Comment by LijunLiu1996** [comment]
@mpromonet 
Hi, Michel!

Thank you sooooooooo much!!!
I think I know how to do. 

Best Regards,
Fiona.

**Comment by FqF2021** [comment]
Excuse me, how do you do it
