### ISSUE TITLE
RTSP http tunnel

### ISSUE THREAD

**Issue by antopar** [mpromonet/webrtc-streamer#50]
It is not possible to set http tunnel option specifying a port number for rtsp sources.
Live555 lib provides http tunnel feature.
openRTSP (the live555 client) provides a -T option in order to enable http tunnel.

[(http://www.live555.com/openRTSP/]
[http://mirror.informatimago.com/next/developer.apple.com/quicktime/icefloe/dispatch028.html]

**Comment by mpromonet** [comment]
Hi antopar,
You are right, this feature is not available, this need to forward the parameter through the layer.
Nothing complex, I will probably add this, next time I will extend live555helper.
Regards
Michel

**Comment by DaniloPetrone** [comment]
It would be great!
