### ISSUE TITLE
webrtc-streamer-v0.7.0-Linux-arm64-Release

### ISSUE THREAD

**Issue by luoluo888** [mpromonet/webrtc-streamer#500]
Debian Buster"/lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found"
libc6 2.28.10 is the latest version of libc6 available for Buster.

**Comment by mpromonet** [comment]
Hi,

Then you could upgrade to "Bullseye", use docker image, or try to compile it for your OS.

Best Regards,
Michel.
