### ISSUE TITLE
Under Ubuntu 20.04.2 LTS x86_64 (Py3.7.9), when using webrtc-streamer, admin.html cannot get the size field, it is displayed as 0x0, please solve this problem, thank you

### ISSUE THREAD

**Issue by UkVOSklF** [mpromonet/webrtc-streamer#514]
![20220708115448](https://user-images.githubusercontent.com/80676291/177913810-5a54af5d-52ca-4075-9c11-ba5e3ed2094b.png)

Under Ubuntu 20.04.2 LTS x86_64 (Py3.7.9), when using webrtc-streamer, admin.html cannot get the size field, it is displayed as 0x0, please solve this problem, thank you

**Comment by mpromonet** [comment]
Hi UkVOSklF,

Yes you are right, this occurs in the last refactoring of capturer.
Feel free to submit a PR to solve this.

Best Regards,
Michel.
