### ISSUE TITLE
Can't play video bug ?

### ISSUE THREAD

**Issue by hellolinks** [mpromonet/webrtc-streamer#517]
**Problem Description:**

OS: windows 10 64 bit
Browser: Chrome103.0.5060.114

**The proxy service keeps getting stuck at:**

```
Start playing sink for "video/H264" subsession
markerSize:4
 Requested URL : rtsp://admin:AMPVAF@server.helloworldnet.com:29970/h264/ch1/sub/av_stream
Close session: video/H264
 Requested URL : rtsp://admin:AMPVAF@server.helloworldnet.com:29970/h264/ch1/sub/av_stream
Start playing sink for "video/H264" subsession
markerSize:4
 Requested URL : rtsp://admin:AMPVAF@server.helloworldnet.com:29970/h264/ch1/sub/av_stream
```

**Browser console log:**

```
local datachannel open
webrtcstreamer.js:170 remote datachannel created:{"isTrusted":true}
webrtcstreamer.js:173 remote datachannel open
webrtcstreamer.js:177 remote datachannel recv:"ServerDataChannel open"
webrtcstreamer.js:199 local datachannel recv:"ClientDataChannel open"
```

**Thanks for helping me troubleshoot, thanks.**

**Comment by cjzm888999** [comment]
The proxy service  log: Close session: video/H264,maybe timeout
 you can set options ,example:

webRtcServer  = new WebRtcStreamer("video","http://"+"8.130.45.200:8888");
		var videoUrl="rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4";
		var audioUrl="";
		var options="rtptransport=tcp&timeout=60";
		webRtcServer.connect(videoUrl,audioUrl,options);
