### ISSUE TITLE
 (audio_device_core_win.cc:4162): Core Audio method failed (hr=-2147023728)

### ISSUE THREAD

**Issue by Ben-huang1004** [mpromonet/webrtc-streamer#520]
![未命名](https://user-images.githubusercontent.com/107387663/180763704-2cbe738f-14f8-436f-98c3-d6bc63b24856.png)

**Comment by Ben-huang1004** [comment]
hi 
i download "webrtc-streamer-v0.7.0-dirty-Windows-AMD64-Release.tar.gz" ,then double click "webrtc-streamer.exe" but it show some erro

**Comment by elliott3** [comment]
ignore it

**Comment by elliott3** [comment]
> hi i download "webrtc-streamer-v0.7.0-dirty-Windows-AMD64-Release.tar.gz" ,then double click "webrtc-streamer.exe" but it show some erro

ignore it
