### ISSUE TITLE
LiveVideoSource: onData no decoder NOTIFY failed

### ISSUE THREAD

**Issue by lionelfung7** [mpromonet/webrtc-streamer#523]
![Screenshot 2022-08-01 114642](https://user-images.githubusercontent.com/50703745/182068427-26e4d77a-f7f5-4066-ba83-3b16d4464c20.png)
![Screenshot 2022-08-01 114708](https://user-images.githubusercontent.com/50703745/182068437-62d17ebf-7f87-497c-865e-2d5db2d657fa.png)

**Comment by mpromonet** [comment]
Hi,

You should look in the log, there is probably an error before. webrtc SDK may not supported the h264 profile that you are using ?
You may also try with option `-o` it will forward h264 frames, then the h264 format need to be supported by your web browser.

Best Regards,
Michel.
