### ISSUE TITLE
sir! Can it support win32?

### ISSUE THREAD

**Issue by isbiubiu** [mpromonet/webrtc-streamer#528]
I want to use in win32 OS but it doesn't support it. Hope to get help.

Thank you very much for your contribution。

**Comment by mpromonet** [comment]
Hi,

I never try, you may first build WebRTC for win32. You may submit a pull request to integrate win32 build.

Best Regards,
Michel.

**Comment by isbiubiu** [comment]
Thank you so much for your help! 

Have a great day!
