### ISSUE TITLE
How to capture video playback failures

### ISSUE THREAD

**Issue by Wwfight** [mpromonet/webrtc-streamer#536]
**Describe the solution you'd like**
When the incoming rtsp video stream address fails to play, there is no way to capture it

**Comment by z944395433** [comment]
我也遇到这个问题，我捕获rtsp流回放失败了，原因是账号和密码无法被识别

**Comment by mpromonet** [comment]
Hi,

You can get the current session using /api/getPeerConnectionList, the admin.html show some simple information.

Best Regards,
Michel.
