### ISSUE TITLE
How to use AEC

### ISSUE THREAD

**Issue by w419894293** [mpromonet/webrtc-streamer#541]
How to use AEC

**Comment by mpromonet** [comment]
Hi,

Hope you were well,
Maybe you should elaborate ?

Best Regards,
Michel.

**Comment by w419894293** [comment]
I use two webcams and there is an echo during a video call. I want to eliminate the echo and how to use it

**Comment by mpromonet** [comment]
Hi,

You may try https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings/echoCancellation. A simple way is to use audio source of only one webcam.

Best Regards,
Michel.

**Comment by w419894293** [comment]
您的邮件已经收到，稍后会处理.
