### ISSUE TITLE
Open discussions

### ISSUE THREAD

**Issue by LeoDog896** [mpromonet/webrtc-streamer#544]
Instead of having [help issues as "issues"](https://github.com/mpromonet/webrtc-streamer/issues/531), it would be better to have discussions. I also want to discuss some more project features overall, so the feature would be nice!

You can read more about discussions in [github's docs](https://docs.github.com/en/discussions/quickstart).

**Comment by mpromonet** [comment]
Hi Tristan,

Nice suggestions, dicussions is now available https://github.com/mpromonet/webrtc-streamer/discussions

Best Regards,
Michel.
