### ISSUE TITLE
Running webrtc-streamer-v0.71-linux-x86_64-release in Ubuntu 20.04.2LTS x86_64(Py3.7.9) indicates an error

### ISSUE THREAD

**Issue by UkVOSklF** [mpromonet/webrtc-streamer#557]
Running webrtc-streamer-v0.71-linux-x86_64-release in Ubuntu 20.04.2LTS x86_64(Py3.7.9) indicates an error

As shown in the picture；
![Error](https://user-images.githubusercontent.com/80676291/216249219-764be6c2-b7e7-4785-8db2-73a545374498.png)

If I want to fix this problem, should I upgrade the "GLIBC" version on the server to 2.32-2.35

Thank you for your answer！

**Comment by UkVOSklF** [comment]
This issue does not occur in version 0.70, and it runs normally

**Comment by mpromonet** [comment]
Hi,

The building environnement was upgrade to ubuntu:22.04.

Best Regards,
Michel.

**Comment by UkVOSklF** [comment]
Thanks
