### ISSUE TITLE
Can you handle the problem of compiling under win10

### ISSUE THREAD

**Issue by JackyLucifer** [mpromonet/webrtc-streamer#568]
Under win10, I compile according to the steps of. github/workflow/cpp-windows.yml file

However, the current compilation fails. The prompt content is the same as that in the action of github. Please handle it

**Comment by JackyLucifer** [comment]
![image](https://user-images.githubusercontent.com/18521851/224481419-5485a30b-4a8d-443c-8481-47beeae78ca2.png)

**Comment by mpromonet** [comment]
Hi @JackyLucifer 

I saw this, maintaining windows build is painful... I did not find a fix for now.
It seems a problem in shell interpretation, the single quote vs double quote ....
Don't hesitate to submit a pull request to fix it.

Best Regards,
Michel.

**Comment by JackyLucifer** [comment]
Well, thank you very much.

**Comment by mpromonet** [comment]
Hi @JackyLucifer 

Build on windows is fixed, docker on windows was built. There is till a problem in github action.

Best Regards,
Michel.

**Comment by JackyLucifer** [comment]
![image](https://user-images.githubusercontent.com/18521851/224551211-a2345d6d-3528-4efa-9f8d-45226d612211.png)

**Comment by JackyLucifer** [comment]
i see it is ok ，thank you very much.
