### ISSUE TITLE
New urls  added in config.json is not streaming rtsp video.

### ISSUE THREAD

**Issue by cloudties** [mpromonet/webrtc-streamer#572]
**Describe the bug**
Started the docker container by passing it via command line. In the config.json we added a new rtsp stream . In the webpage a new tab appear but the stream is not getting played 

**To Reproduce**
1. Add a new entry in config.json
2. Launched the docker in a Rasberry pi . May of the existing stream are getting stream properly . 
3. Connected a pi camera and even a USB camera to pi . Both tested separately and simultaneously 
4. On the web UI the new tab is appearing ,but not stream viewed
5. In order to check the camera funciton. we tried the libcamera module 
 libcamera-vid -t 0 --inline -o - | cvlc stream:///dev/stdin --sout '#rtp{sdp=rtsp://:8554/stream}' :demux=h264   --rtsp-host=192.168.29.63 
 The stream is getting generated and using VLC we are able to watch the rtsp stream from camera . But the same stream url added to the  config.json is not getting played 
6. All the devices are in the same network and accessible

**Expected behavior**
New working streams from camera should appear as tab and should show the live stream , like we have the sample 
**Screenshots**

**Rasberry pi (please complete the following information):**
 - OS: Bullseye 
 - Browser  Chrome 
 - Default legacy camera in pi , streams generated and viewed in VLC ,but not via browser UI through the container 
 - USB camera compatible with pi ( with mpeg and yuy  format ) . Small format compatibility there , But stream not appearing via container + conig,json 
 - 

**Smartphone (please complete the following information):**

**Additional context**
 If i am not missing any configuration, The streaming container is having some bottle neck while accepting stream data from the camera connected to the same pi where the web streaaamer docker image is running .

**Comment by mpromonet** [comment]
Hi @cloudties 

You may look to the log, it may helps you to understand the problem. Did you try to use network=host starting docker ?

Best Regards,
Michel.

**Comment by cloudties** [comment]
> Hi @cloudties
> 
> You may look to the log, it may helps you to understand the problem. Did you try to use network=host starting docker ?
> 
> Best Regards, Michel.


Hi,

Wonderful ,that solved the issue . i get the stream on UI . 
How ever in the rtspstreamer i get a extra pattern in the url  "track1" . Is this automatically appended by the server ? 

handleCmd_SETUP:SETUP rtsp://192.168.29.63:8554/live/track1 RTSP/1.0
CSeq: 3
User-Agent: LIVE555 Streaming Media v2023.01.19
Transport: RTP/AVP/TCP;unicast;interleaved=0-1


Additionally , please add the network configuration in case of bridge or nat  for that docker . That helps 

Thanks Michel for the quick response .

Saju .

**Comment by cloudties** [comment]
Closed after adding proper docker parameters
