### ISSUE TITLE
服务端启动参数加入-o 的奇怪问题

### ISSUE THREAD

**Issue by otygoo** [mpromonet/webrtc-streamer#575]
我使用项目做 rtsp 相机 的 web 显示.
经过几天的测试发现一个奇怪的问题:
服务端启动时 加入 -o 参数, 基本播放 一个小时左右都会中断, 如果不加 -o 可以一直播放
使用 docker 镜像, 已更新到最新版本 测试依然.

**Comment by mpromonet** [comment]
對不起，我的中文很有限
