### ISSUE TITLE
demo on herokuapp

### ISSUE THREAD

**Issue by antopar** [mpromonet/webrtc-streamer#58]
Hi mpromonet,

demo page at https://webrtc-streamer.herokuapp.com/ doesn't work properly.
Firefox tells: 
"ICE failed, add a STUN server and see about:webrtc for more details"
"ICE failed, add a TURN server and see about:webrtc for more details"

I tryed in my local machine and it works only with local streamer (VLC), what is the problem?
It is a STUN/TURN server issue?
Thankyou

**Comment by mpromonet** [comment]
Hi antopar,

I don't think it is a STUN/TURN issue, it seems to works better with Chrome.
Till know I did now understand why ICE negotiation fails under firefox, maybe a iceservers arguments are not formatted correctly.
This need to be investigated....
Regards,
Michel.

**Comment by antopar** [comment]
Hi mpromonet,
thank you for your availability.

In my local network all works fine. In a real network there are some issues.
Chrome does exactly the same on herokuapp, so I'm trying to deploy your streamer in a remote server.
Yesterday I tryed to deploy your streamer in a remote server and I cannot stream.

There is something to kwon in order to properly deploy?
Thank you

**Comment by mpromonet** [comment]
Hi antopar,
In your log we see RTSPVideoCapturer::Decoded, I guess the wideo is decoded, as it complains about audio, maybe you can try to disable it setting audiourl to dummy.
Best Regards,
Michel.
