### ISSUE TITLE
webrtc-streamer-v0.7.2-dirty-Windows-AMD64-Release  Windows 7 Ultimate 

### ISSUE THREAD

**Issue by lxp0205** [mpromonet/webrtc-streamer#582]
webrtc-streamer-v0.7.2-dirty-Windows-AMD64-Release  can not run at  Windows 7 Ultimate ：

Unable to start this program because api-ms-win-shcore-scaling-l1-1-1, DLL is missing from the computer. 
Try reinstalling the program to resolve this issue.

**Comment by lxp0205** [comment]
webrtc-streamer-v0.6.5 can run at Windows 7 Ultimate

**Comment by mpromonet** [comment]
Hi,

This project is maintained only for latest dependencies.

Best Regards,
Michel.

**Comment by CHN-STUDENT** [comment]
Thanks, i hope our boss can let us upgrade our server os with latest dependencies, or only 'work' in old version.
