### ISSUE TITLE
cmke error Compilation failed， What is the reason for this? Thank you

### ISSUE THREAD

**Issue by zhuya1996** [mpromonet/webrtc-streamer#586]
![QQ截图20230508212210](https://user-images.githubusercontent.com/25482513/236843304-0d439cdd-cc49-4292-a2ad-1567696db07e.png)
![QQ截图20230508213547](https://user-images.githubusercontent.com/25482513/236843318-ebb7a3ba-c26d-4ee5-a923-0c1457db54c1.png)
![QQ截图20230508213620](https://user-images.githubusercontent.com/25482513/236843349-92c721e9-23e7-42ad-871a-5a9ce1b0c28
![QQ截图20230508213813](https://user-images.githubusercontent.com/25482513/236843392-b2d7943c-c483-4bf8-8e35-a23e6b845de5.png)
2.png)

**Comment by iqbal-h** [comment]
CMakeList.txt is inside webrtc-streamer directory.
`.../webrtc-streamer:~# cmake .`

**Comment by zhuya1996** [comment]
> 

Put it in the depot_ Are tools in the same level directory？

**Comment by zhuya1996** [comment]
> 目录应该是这样的：
> 
> ```
> .../home/depot_tools:~# 
> .../home/webrtc:~# 
> .../home/webrtc-streamer:~# 
> ```
> 
> 添加 depot_tools 的路径是必须的， `cmake . && make`只能在 webrtc-streamer 中运行

![QQ截图20230508230154](https://user-images.githubusercontent.com/25482513/236859494-6eb85b1f-bc73-4f5d-83c9-774ae4305f78.png)
![QQ截图20230508230208](https://user-images.githubusercontent.com/25482513/236859511-c859af12-ae15-4db8-aca3-7fc444428859.png)

**Comment by zhuya1996** [comment]
> > 目录应该是这样的：
> > ```
> > .../home/depot_tools:~# 
> > .../home/webrtc:~# 
> > .../home/webrtc-streamer:~# 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 添加depot_tools的路径是必须的，`cmake . && make`只能在webrtc-streamer中运行
> 
> ![QQ截图20230508230154](https://user-images.githubusercontent.com/25482513/236859494-6eb85b1f-bc73-4f5d-83c9-774ae4305f78.png) ![QQ截图20230508230208](https://user-images.githubusercontent.com/25482513/236859511-c859af12-ae15-4db8-aca3-7fc444428859.png)

There's still a problem

**Comment by mpromonet** [comment]
Hi

Some dependencies are probably missing like glib. You should get needed environnent from dockerfile. 

Best Regards
Michel

**Comment by zhuya1996** [comment]
o no，Not very good at using dockers

**Comment by zhuya1996** [comment]
> 你好
> 
> 可能缺少一些依赖项，例如 glib。您应该从 dockerfile 获得所需的环境。
> 
> 最好的问候 米歇尔

![image](https://user-images.githubusercontent.com/25482513/237028247-a58c1956-475a-4f12-9882-14bc7e476fa0.png)
Hello, have I compiled this successfully？？？

**Comment by mpromonet** [comment]
Hi,

It looks like an executable, it is green, if you look to its permission, it should have +x permission.

Best Regards,
Michel.

**Comment by zhuya1996** [comment]
> 你好，
> 
> 它看起来像一个可执行文件，它是绿色的，如果你查看它的权限，它应该有 +x 权限。
> 
> 最好的问候， 米歇尔。

![QQ截图20230509180257](https://github.com/mpromonet/webrtc-streamer/assets/25482513/e6187f56-b29c-4634-bb4b-e98243b625c8)
After downloading, it is not an exe under Windows

**Comment by mpromonet** [comment]
Hi,
Of course, you build a linux executable...
Best Regards
Michel

**Comment by zhuya1996** [comment]
> 嗨， 当然，你构建了一个 linux 可执行文件...... 最好的问候 Michel

Hello, can you compile exe under Linux for use under Windows？

**Comment by mpromonet** [comment]
Hi,

This need to cross compile for windows under linux, probably not an easy task to build webrtc lib. Why not build on windows for windows ?

Best Regards
Michel.
