### ISSUE TITLE
添加-c参数后，仍然报错net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by 1s1u** [mpromonet/webrtc-streamer#591]
我服务器docker安装镜像之后，通过命令行启动webRtc-streamer，但仍然报错net::ERR_SSL_PROTOCOL_ERROR，证书不是有两个参数么，为什么-c后面只有一个变量。
        也有可能是我-c后面的参数出现了问题，还想请教一下，-c具体怎么带参数

**Comment by 1s1u** [comment]
how tov write the correct format for -c
![image](https://github.com/mpromonet/webrtc-streamer/assets/68693584/45beeb90-cb09-4246-b07b-bb374cf99133)

**Comment by yangjieshao** [comment]
https://github.com/mpromonet/webrtc-streamer/issues/505

> 如果证书参数的格式正确的话，需要安装和配置openSSL Except for correct format of certificate, you also need to install and config openSSL

**Comment by yangjieshao** [comment]
别折腾了 用Nginx转发一下得了

**Comment by mpromonet** [comment]
對不起，我的中文很有限

**Comment by blwinner** [comment]
> 對不起，我的中文很有限
 
thanks for your amizing work.  he start webrtc-streamer by docker, and get error code: net::ERR_SSL_PROTOCOL_ERROR, so his question is : argument '-c' only one input, and create credential need two (i dont understant too:)), how can he start with '-c' in detail

**Comment by mpromonet** [comment]
Hi @blwinner,

Did you look to https://github.com/mpromonet/webrtc-streamer/discussions/592 ?

Best Regards,
Michel.

**Comment by tangxinqi0218** [comment]
> 别折腾了 用Nginx转发一下得了

是的，配置转发分分钟就搞定
