### ISSUE TITLE
docker can't get video stream

### ISSUE THREAD

**Issue by whoamixl** [mpromonet/webrtc-streamer#594]
![image](https://github.com/mpromonet/webrtc-streamer/assets/49057722/2d67df8e-b633-4e99-8405-67f8bb81362e)
![image](https://github.com/mpromonet/webrtc-streamer/assets/49057722/85beedb4-45f5-4289-939a-9d56a66cd618)

After deploying docker on the public network server, the stream cannot be obtained. What should I do?

**Comment by rouxianmantou** [comment]
NAT的问题吧？国内的网络环境还是TURN靠谱...要不就用那种商用的rtc方案
