### ISSUE TITLE
I get build error I can't find failure. 

### ISSUE THREAD

**Issue by mevlutardic** [mpromonet/webrtc-streamer#599]
[ 33%] Built target depot-tools
[ 37%] Performing configure step for 'webrtc-src'
-- Retrieving depot_tools commit before 2017-08-01 09:33:37 +0000
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
CMake Error at /home/mevlut/Desktop/Denemelerim/WebRTC/libwebrtc/CMakeModules/LibWebRTCExecute.cmake:42 (message):
  -- Unable to find depot_tools commit before 2017-08-01 09:33:37 +0000
Call Stack (most recent call first):
  /home/mevlut/Desktop/Denemelerim/WebRTC/libwebrtc/CMakeModules/DepotTools.cmake:30 (libwebrtc_execute)
  CMakeLists.txt:51 (include)

-- Configuring incomplete, errors occurred!
make[2]: *** [CMakeFiles/webrtc-src.dir/build.make:93: webrtc/stamp/webrtc-src-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:114: CMakeFiles/webrtc-src.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by mpromonet** [comment]
Hi @mevlutardic 

I don't know what you are trying to build, probably another project... nothing is called libwebrtc in this one.

Best Regards,
Michel.
