### ISSUE TITLE
WEBRTCROOT and WEBRTCBUILD can not be used by makefile

### ISSUE THREAD

**Issue by maeikei** [mpromonet/webrtc-streamer#6]
fix diff
-----------------------------------
diff --git a/Makefile b/Makefile
index 4319a18..a8be83f 100644
--- a/Makefile
+++ b/Makefile
@@ -10,8 +10,8 @@ ifneq ($(wildcard $(SYSROOT)/usr/include/liveMedia/liveMedia.hh),)
 endif

 # webrtc
-WEBRTCROOT=../webrtc
-WEBRTCBUILD=Release
+WEBRTCROOT ?=../webrtc
+WEBRTCBUILD ?=Release
 WEBRTCLIBPATH=$(WEBRTCROOT)/src/$(GYP_GENERATOR_OUTPUT)/out/$(WEBRTCBUILD)

 CFLAGS += -DWEBRTC_POSIX -fno-rtti

**Comment by mpromonet** [comment]
Thanks, I will include this modification in order to allow to use shell variables.
