### ISSUE TITLE
My RTSP user name contains @ and / characters

### ISSUE THREAD

**Issue by x876609353** [mpromonet/webrtc-streamer#601]
My RTSP user name contains @ and / characters, the video does not play normally, I try to escape them, but it still doesn’t work, the same address, I can put it in a third-party player, the rtsp is as follows:
rtsp://test/@:abc123@127.0.0.1:554
rtsp://test%2F%40:abc123@127.0.0.1:554

**Comment by mpromonet** [comment]
Hi,

This seems strange it seems working well. I just try with `rtsp://test%2F%40:abc123@myserver` using config file, giving it to command line or encoding it using `/webrtcstreamer.html?video=<rtsp url encoded>` 

Best Regards,
Michel.
