### ISSUE TITLE
在win7 32位系统上运行不了

### ISSUE THREAD

**Issue by locklock111** [mpromonet/webrtc-streamer#608]
![微信图片_20230724095034](https://github.com/mpromonet/webrtc-streamer/assets/134594260/a82777d9-b1e0-43b6-b5bd-2db811fdec4e)
大佬，这个是因为在64系统上编译的问题吗？是否用源码在32位系统上编译就可以解决呢？如果是的话请问如何编成可执行程序呢？

**Comment by yangjieshao** [comment]
https://github.com/mpromonet/webrtc-streamer/issues/582

用 v0.6.5

**Comment by yangjieshao** [comment]
看上去  没得32位版本
太古老的系统不建议加程序了
5代i3的工控机只要一千左右，加个工控机吧
不然后面维护会死人的

**Comment by locklock111** [comment]
> #582
> 
> 用 v0.6.5

刚刚试了一下也不兼容 实在不行的话只能换种方法重写了...谢谢
