### ISSUE TITLE
This error occurs when I open the same camera on multiple web pages at the same time!

### ISSUE THREAD

**Issue by yang-classmate** [mpromonet/webrtc-streamer#609]
![image](https://github.com/mpromonet/webrtc-streamer/assets/140583990/1cfdc903-4353-41a9-bbaf-0e30629abe8d)

**Comment by mpromonet** [comment]
Hi,

It seems the rtsp server answer with an error ?
If options are the same it should share the backend RTSP stream, if somes are differents it opens a new RTSP stream.

Best Regards,
Michel.
