### ISSUE TITLE
H265 RTSP need support

### ISSUE THREAD

**Issue by dinggf123** [mpromonet/webrtc-streamer#611]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mpromonet** [comment]
Hi @dinggf123 

Feel free to submit a PR to add this support.

Best Regards,
Michel.

**Comment by liusuyi2021** [comment]
我已经找到一个临时解决265的rtsp的播放方案，就是使用ffmpeg配合mediamtx进行转码 目前试用了几路视频 感觉还可以，你也可以试试。

**Comment by liusuyi2021** [comment]
谷歌已经支持HEVC的H265了，使用最新版本0.8.2 还是无法播放呢？
