### ISSUE TITLE
How to define customized file video capturer?

### ISSUE THREAD

**Issue by cyclizationz** [mpromonet/webrtc-streamer#627]
I want to carry out some pre-processing on the captured frame in the video capture. However, I am not sure where the frame is constructed. 

Can I use the onData() function in livevideosource.h, line104? If that works and the video is H264 coded, at which line is the frame data first captured and I can cast operations?

**Comment by mpromonet** [comment]
Hi,

onData is the callback of RTSPConnection, it is called when data should be processed, it contains coded frame.

Best Regards,
Michel.
