### ISSUE TITLE
Not working on Safari 11

### ISSUE THREAD

**Issue by AdoPi** [mpromonet/webrtc-streamer#63]
Hi, thanks for your big work on this streamer!
The website does not work on Safari 11, maybe using [adapter.js](https://github.com/webrtc/adapter) can solve the problem.

**Comment by GregBakker** [comment]
adapter may be part of the solution - but it's not 100% for Safari. Also had to use
```
	if (isSafari) {
            this.pc.addTransceiver('video')
	    this.pc.addTransceiver('audio')
	}
```
on the PeerConnection. Even so, this doesn't immediately work on IOS safari - might have to do with the safety of the origin of the element; haven't tried this via https yet.

**Comment by GregBakker** [comment]
...but definitely a useful codebase, thx!

**Comment by mpromonet** [comment]
Hi,
Maybe I will look what is different in safari webrtc interface, however probably the html/js in the project will stay as simple as it could. 
I would like to avoid dependencies with some extra layer like adapter.js, maybe I will change my mind...
You could develop an interface using adapter.js and webrtc-streamer API.
Best Regards,
Michel.

**Comment by AdoPi** [comment]
I see that the adapter lib has been included on the project so I close this issue.
Thanks for your works :)
