### ISSUE TITLE
docker container return [h264 @ 0x7f682b0ed000] no frame!

### ISSUE THREAD

**Issue by LRxRayTse** [mpromonet/webrtc-streamer#632]
Hi, I want to ask why container console keep showing following message. (The steaming is still working)
 
![image](https://github.com/mpromonet/webrtc-streamer/assets/92071641/11520c2c-185a-45b4-8846-fcfbbfafd172)

Thank you. <3

**Comment by yangjieshao** [comment]
try 
```
docker run --restart=always -d --network=host \
           --name webrtc-streamer \
           mpromonet/webrtc-streamer 
```

only 8000 is not enough

**Comment by mpromonet** [comment]
Hi @LRxRayTse 

This is coming from h264 decoder of ffmeg that cannot get frame, this depends on your backend stream. Probably ffplay with the same backend stream will do the same....

Best Regards,
Michel.

**Comment by LRxRayTse** [comment]
@yangjieshao @mpromonet 

Thank a lot, I will try and check my backend stream. <3
