### ISSUE TITLE
Error in parsing EncodedImage4

### ISSUE THREAD

**Issue by mjchow** [mpromonet/webrtc-streamer#636]
I used the -o parameter and encountered an error log (NullEncoder.h:73): Error in parsing EncodedImage4. What should I do?
I do not use the -o parameter for the video, and the video can play, but there are also several lines of error logs: (VideoDecoder.h:265): VideoDecoder::DecoderThread no decoder
[h264 @ 0x7fe1fa10e240] No start code is found.
[h264 @ 0x7fe1fa10e240] Error splitting the input into NAL units.

**Comment by mpromonet** [comment]
Hi,
It may be some problem in the H264 stream ?
Best Regards,
Michel.
