### ISSUE TITLE
When using some Dahua cameras, it prompts "no frame!"

### ISSUE THREAD

**Issue by 51jintian** [mpromonet/webrtc-streamer#648]
**Describe the bug**

When using some Dahua cameras, it prompts "no frame!". In this case, the screen of the instance can be played, but the CPU usage is very high. If the -o parameter is used, there is no video screen display, and the screen keeps spinning.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/mpromonet/webrtc-streamer/assets/153275897/95b87cd8-e542-465d-92d8-8dee261b98c7)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]windows 11  22621.2715
 - Browser [e.g. chrome, safari] edge，chrome 
 - Version [e.g. 22] webrtc-streamer-v0.8.4-dirty-Windows-AMD64-Release

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mpromonet** [comment]
Hi,

The ffmpeg log "no frame!" just means ther is no frame in the packet, it may be problems in parsing. Increasing loglevel may helps you.

Best Regards,
Michel.
