### ISSUE TITLE
Any chance to do the other way around? How?

### ISSUE THREAD

**Issue by novikovmaa** [mpromonet/webrtc-streamer#65]
Hello!

Your project is cool and it works, thanks! Any chance to do the reverse? Such a use case: i open a webpage and send out a webrtc stream (webcam or a shared screen in Chrome - which can be full HD) - and the server receives that stream from me and produces RTSP on output?

My goal is to play it with omxplayer on Raspberry PI in full screen then - omxplayer accepts only a limited choice of protocols, among which there is no webrtc, so currently i am forced to encapsulate ffmpeg in my video streaming application and send out udp stream of mpegts to omxplayer directly, which is resource intensive on the client and prone to compatibility issues - webrtc is universal (as long as i carry Chromium with me - it is an Electron app). Being able to send out webrtc and somehow play it on omxplayer through some intermediary would be cool.

Directly playing webrtc on Raspberry is not an option. It is simply too slow, won't work full screen 1080. Nothing except omxplayer seem to play 1080 video well on Raspberry 3. 

Thanks!

Mikhail

**Comment by mpromonet** [comment]
Hi Mikhail,

In fact the webrtc stream given as the offer is /call API is received by webrtc-streamer, but nothing is done with.
It could feed an RTSP server.
Looking in the peerconnection sample in webrtc and some RTSP server using live555, binding these pieces should do something like what you describe.

Best Regards,
Michel.
