### ISSUE TITLE
SSL is possible?

### ISSUE THREAD

**Issue by roberto497** [mpromonet/webrtc-streamer#66]
I need to use ssl, it's possible?

**Comment by mpromonet** [comment]
Hi roberto497,
civetweb support it, you need to give -H8000,8001s to listen http on port 8000 and https on 8001.
It needs probably a little modification in order to give key/certificate to civetweb.
Best Regards,
Michel.

**Comment by roberto497** [comment]
Not working for me.
I've changed the civetweb.conf file, includes the lines:
listening_ports 80, 443s
ssl_certificate ./ssl_cert.pem

I started webrtc-streamer with -H 8000,8001s, but it only works on http

**Comment by mpromonet** [comment]
Hi roberto497,
There is no configuration file, your civetweb.conf is not read.
I added an option -c to give the ssl material.
Best Regards,
Michel.
