### ISSUE TITLE
Vulnerabilities scan result by BDBA（Black Duck Binary Analysis）

### ISSUE THREAD

**Issue by manupstairs** [mpromonet/webrtc-streamer#661]
Thank you for your great webrtc-streamer!
I need to scan vulnerabilities in BDBA when I use webrtc-streamer in my project.
The problem is that there are some third-party libraries can't be detected in BDBA automatically.
Is there any document or code or link which can help me to indicate these third-party libraries version info?
For example, webrtc-streamer reference FFmpeg, but I can't find FFmpeg version info, the BDBA will report all historical vulnerabilities. 
<img width="664" alt="image" src="https://github.com/mpromonet/webrtc-streamer/assets/1835049/09b030b7-db7d-4b88-9097-846283d88ca9">

**Comment by mpromonet** [comment]
Hi,
These third parties are WebRTC ones, you could remove some of them build parameters, especially setting is_chrome_branded=false  https://github.com/mpromonet/webrtc-streamer/blob/master/CMakeLists.txt#L63C19-L63C36 
Best Regards,
Michel.

**Comment by manupstairs** [comment]
Hi , according to your guidance, I find something I need at here:
https://chromium.googlesource.com/chromium/third_party/ffmpeg/
Share the infomation with others.
Many thanks, @mpromonet!
