### ISSUE TITLE
android rtsp client integration [question]

### ISSUE THREAD

**Issue by ozankonur** [mpromonet/webrtc-streamer#67]
Hi,
I am using an android camera streaming rtsp client. It only needs a rtsp end-point to stream on it. Now I installed webrtc-streamer on my machine. So, do I need live555 media server for integration ? I mean, is it possible  like ;
Android Client (needs rtsp://... endpoint) ---> Live555 Media Server ---> webrtc-streamer
Or can I integrate directly like ;
Android Client (needs rtsp://... endpoint) --->  webrtc-streamer

**Comment by mpromonet** [comment]
Hi ozankonur,
If you are running an RTSP server like https://play.google.com/store/apps/details?id=com.miv.rtspcamera you can transform RTSP stream to WebRTC directly using the rtsp endpoint.
Best Regards,
Michel.
