### ISSUE TITLE
Concurrency support

### ISSUE THREAD

**Issue by bacium** [mpromonet/webrtc-streamer#673]
How many channels of real-time streaming can webrtc-streamer support at most? The video freezes after I call the video from multiple cameras. Finally, webrtc-streamer.exe will crash and exit automatically.
webrtc-streamer-version：0.8.4
system: window11

**Comment by mpromonet** [comment]
Hi,
It probably depends on video size, bandwith, codec....
Best Regards
Michel

**Comment by bacium** [comment]
> 嗨， 这可能取决于视频大小、带宽、编解码器...... 最好的问候 米歇尔

Thank you very much for your answer. I will check the reason.
