### ISSUE TITLE
rtsp video stream cannot be played

### ISSUE THREAD

**Issue by yikexiaoshu1** [mpromonet/webrtc-streamer#677]
Hello, I used VLC to simulate an rtsp video stream, such as rtsp://172.16.50.12:8554/v. I installed webrtc-streamer in window and linux and played the rtsp video stream through webrtcstreamer.html. The webrtc-streamer will report an error. 
Error content: 
Failed to SETUP: 461 Unsupported transport
Failed to SETUP: 461 Unsupported transport
Failed to PLAY: No RTSP session is currently in progress.

How should I solve it? Thank you.

**Comment by yikexiaoshu1** [comment]
In VLC test RTSP address can be played normally

**Comment by mpromonet** [comment]
Hi,
By default, it use rtp over TCP.
Best Regards
Michel

**Comment by yikexiaoshu1** [comment]
Hello, I don’t understand what you mean. Can you explain it in detail?How can I set it up to play rtsp video stream?

**Comment by mpromonet** [comment]
Hi @yikexiaoshu1,

The default options are defined in https://github.com/mpromonet/webrtc-streamer-html/blob/f27dc4ca97aab57ce1f85589983f867a197a70cd/webrtcconfig.js, then
`options: "rtptransport=tcp&timeout=60",`

You could overide it adding in url  `/webrtcstreamer.html?video=.....&options=` or `/webrtcstreamer.html?video=.....&options=rtptransport%3Dudp` 

Best Regards,
Michel.
