### ISSUE TITLE
[windows] build failing: 'libboringssl.lib', needed by 'webrtc-streamer` 

### ISSUE THREAD

**Issue by cash-metall** [mpromonet/webrtc-streamer#679]
im trying to build webrtc-streamer for windows
im try with clang/msvc and both compilers show 
```
ninja: error: 'E:/git/webrtc/src/out/Debug/obj/third_party/boringssl/boringssl.lib', needed by 'webrtc-streamer.exe', missing and no known rule to make it
16:40:18: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 1.
```
looks like the same problem [667](https://github.com/mpromonet/webrtc-streamer/issues/667) but for windows

**Comment by mpromonet** [comment]
Hi @cash-metall 

I guess like for #667 , a problem occurs before this error, that just says boringssl have not be build.

Best Regards,
Michel.
