### ISSUE TITLE
Build binary

### ISSUE THREAD

**Issue by alecapu80** [mpromonet/webrtc-streamer#68]
Hi,
I've seen that you use Travis for test build with 3 different build. 
Is possibile to access to the build binary without rebuild it?

**Comment by mpromonet** [comment]
Hi alecapu80,
I don't know how to access to travis build, but the travis job push binaries to github releases.
You can get it from https://github.com/mpromonet/webrtc-streamer/releases
Best Regards,
Michel.

**Comment by alecapu80** [comment]
WOW, thank you very much. It works very well with ONE RTSP stream on Raspberry Pi 3 B.
Unfortunately with more contemporary stream it crash, probably for the limited resources of the Raspberry. Very very nice job!! It's very useful! 
Tnks

**Comment by xunxin03** [comment]
How can I use the Build binary file? Where should I put it in? Which system is ok? ubuntu?

**Comment by mpromonet** [comment]
Hi xunxin03,
You can extract file from tar.gz and run webrtc-streamer.
The build is for ubuntu trusty, it should also works on next release. I test it on xenial and it run well.
Best Regards,
Michel.
