### ISSUE TITLE
 UDP H264 stream compatibility

### ISSUE THREAD

**Issue by yikexiaoshu1** [mpromonet/webrtc-streamer#680]
Hello, we need to receive multicast ts H264 video streams from the device, we want to use webrtc-streamer, we need to stream ts into rtsp streams? If necessary, can you recommend a method with high performance and stability?
Hope to get your reply

**Comment by mpromonet** [comment]
Hi,
You need to add support for ts, and demux it.
Feel free to submit a PR.
Best Regards 
Michel
