### ISSUE TITLE
May I ask if modifying SDL to support H265 encoding and decoding is done in webrtcstreamer.js? I would like to see H265 negotiation in SDP

### ISSUE THREAD

**Issue by zhuya1996** [mpromonet/webrtc-streamer#684]
May I ask if modifying SDL to support H265 encoding and decoding is done in webrtcstreamer.js? I would like to see H265 negotiation in SDP  ，thanks

**Comment by mpromonet** [comment]
Hi,
Sure, feel free to submit a PR.
Best Regards 
Michel

**Comment by zhuya1996** [comment]
> 提交 PR

Hello, what I mean is, where can I modify it for you? It's not about submitting a PR

**Comment by mpromonet** [comment]
Hi,
Maybe I don't understand your point, If your browser support h265, it should include in offer.
Best Regards 
Michel
