### ISSUE TITLE
I decided to use datachannel to transmit h265 and then decode it locally. Can you teach me how to use datachannel?

### ISSUE THREAD

**Issue by zhuya1996** [mpromonet/webrtc-streamer#687]
I decided to use datachannel to transmit h265 and then decode it locally. Can you teach me how to use datachannel?  thanks

**Comment by mpromonet** [comment]
Hi,
I feel this approach strange, in such a case why using webrtc, just use a standard websocket.
Best Regards 
Michel

**Comment by zhuya1996** [comment]
datachannel has relatively better bandwidth control capabilities, better latency, and better data transmission security.

**Comment by zhuya1996** [comment]
> 嗨， 我觉得这种方法很奇怪，在这种情况下为什么使用 webrtc，只使用标准的 websocket。 您可以查看使用 H265 的https://github.com/mpromonet/rtsp2web 。 最好的问候 米歇尔

datachannel has relatively better bandwidth control capabilities, better latency, and better data transmission security.

**Comment by zhuya1996** [comment]
> Hi, I feel this approach strange, in such a case why using webrtc, just use a standard websocket. You may look to https://github.com/mpromonet/rtsp2web that is working with H265. Best Regards Michel

Do you know that the datachannel project has GCC congestion algorithm?

**Comment by mpromonet** [comment]
Hi @zhuya1996 

You may look to https://www.w3.org/TR/webtransport/

Best Regards,
Michel.
