### ISSUE TITLE
After a period of time, frames are dropped and reconnection is impossible

### ISSUE THREAD

**Issue by zhou1591** [mpromonet/webrtc-streamer#690]
### I am now using the win10 above the official website example, my camera push rtsp video stream, the code is H264, the size of the video is 1280*720, the wifi bandwidth is about 20M, after I use the example to start sometimes there will be frame loss

![iwEcAqNwbmcDAQTRB4AF0QNGBrDXq1NMFAHoWQYDb3NaowIAB9Itg102CAAJomltCgAL0gAF3Us png_720x720q90](https://github.com/mpromonet/webrtc-streamer/assets/39522200/7e59ab20-b58f-447b-95ae-8eccf1d9eb68)

### Then there is another problem, after I close the exe inside the official sample program, I open it again, sometimes the backend service api will report an error directly in the js

```
WebRtcStreamer.prototype.onError
```

**Comment by mpromonet** [comment]
Hi,

It is usually a good practice to ask only one question in a thread. Otherwise it becomes quickly messy.
Reading quickly I don't know what is rtsp_demo.c, it doesnot seems to come from this project.
However when there is some frame drops, it may be possible to take some decisions.

Best Regards 
Michel

**Comment by zhou1591** [comment]
> Hi,
> 
> It is usually a good practice to ask only one question in a thread. Otherwise it becomes quickly messy. Reading quickly I don't know what is rtsp_demo.c, it doesnot seems to come from this project. However when there is some frame drops, it may be possible to take some decisions. Nowdays connection is closed (and then restarted) when no data is received for an amount of time.
> 
> Best Regards Michel

Is there any way I can catch a dropped frame error in the exe and re-establish the link without closing the exe?

**Comment by zhou1591** [comment]
![image](https://github.com/mpromonet/webrtc-streamer/assets/39522200/8a401ff8-e5f4-4bb2-983a-5f8853d9fbf4)


> Hi,
> 
> It is usually a good practice to ask only one question in a thread. Otherwise it becomes quickly messy. Reading quickly I don't know what is rtsp_demo.c, it doesnot seems to come from this project. However when there is some frame drops, it may be possible to take some decisions. Nowdays connection is closed (and then restarted) when no data is received for an amount of time.
> 
> Best Regards Michel

Sometimes the program itself shows this up
