### ISSUE TITLE
Frame ancestors

### ISSUE THREAD

**Issue by marcelimati** [mpromonet/webrtc-streamer#692]
Hello, I need a way to open url in iframe hosted by http server of your application.
By default it host http server on port 8000, which is fine by me, I tried to run the app with -X parameter which if i understood correctly removed this part: 
`if (!disableXframeOptions) {
	options.push_back("additional_header");
	options.push_back("X-Frame-Options: SAMEORIGIN");
}`
But in newest browsers you need to pass parameter Content-Security-Policy: frame-ancestors http://192.168.0.192; in header so it will allow to embed the page in iframe from other origin(which is only the same url but on different port), how can i achieve it? I tried to add the line in source but I don't know how to build it on windows because it gives me errors.

**Comment by mpromonet** [comment]
Hi,

It may be simpler with the webcomponent of this project or https://github.com/Eyevinn/webrtc-player

Best Regards,
Michel.
