### ISSUE TITLE
how to insert username and password in RTSP source ?

### ISSUE THREAD

**Issue by k13elle** [mpromonet/webrtc-streamer#70]
how to insert username and password in RTSP source ?

i tried to use "rtsp://[username]:[password]@url:port/dist/blah/blah" as a source list (in command line) but it didn't work.

output show it always try to connect.

**Comment by mpromonet** [comment]
Hi k13elle,

It works giving rtsp://<username>:<password>@....
Depending how you give the url to the /call API, it may needed to escape some character, try with a simple user & password.
Best Regards,
Michel.

**Comment by k13elle** [comment]
Hi Michel

Now it works without any changes.
I have no idea how it work.
 
Thanks for your kindly reply.

Best Regard,
Nathapon.
