### ISSUE TITLE
The delay of using audio and video is much greater than that of playing video alone. Please tell me why this is happening. I am waiting for your reply. Thank you.

### ISSUE THREAD

**Issue by zhuya1996** [mpromonet/webrtc-streamer#710]
![QQ截图20240802093017](https://github.com/user-attachments/assets/a0de97eb-c858-4ede-ba0a-b85f9e532497)
![QQ截图20240802092850](https://github.com/user-attachments/assets/44ef2278-d2dd-4dda-ab37-d75fd6f625b7)

**Comment by mpromonet** [comment]
Hi @zhuya1996,

It might be because there is 2 rtsp connections, it may also have some improvement to do in timestamp publish to webrtc sdk...

Best Regards,
Michel.

**Comment by zhuya1996** [comment]
> 你好@zhuya1996，
> 
> 这可能是因为有 2 个 rtsp 连接，在将时间戳发布到 webrtc sdk 时可能也需要做一些改进...
> 
> 此致敬礼， 米歇尔。



> Hi @zhuya1996,
> 
> It might be because there is 2 rtsp connections, it may also have some improvement to do in timestamp publish to webrtc sdk...
> 
> Best Regards, Michel.

1. Should I modify the sent timestamp in webrtc-streamer or in the webrtc source code?
2. If I remove the audio and video synchronization, I wonder if it can solve the problem of video delay. What do you think?
