### ISSUE TITLE
Could you please tell me the difference between true and false? Thanks

### ISSUE THREAD

**Issue by zhuya1996** [mpromonet/webrtc-streamer#712]
RTSPAudioSource::RTSPAudioSource(rtc::scoped_refptr<webrtc::AudioDecoderFactory> audioDecoderFactory, const std::string & uri, const std::map<std::string,std::string> & opts) 
				: LiveAudioSource(audioDecoderFactory, uri, opts, true) {
}

I found that the parameter [jitterBufferDelay/jitterBufferEmittedCount_in_ms] equal to true will always be in a relatively low state

**Comment by mpromonet** [comment]
Hi @zhuya1996,

Looking to liveaudiosource you will see it is a flag to delay frames. The reason of this is reading mkv file needs to wait between frames. For rtsp source it should be false. 

Best Regards 
Michel
