### ISSUE TITLE
I have no ideal for this error can found counter.h gauge.h etc in freebsd 14 it's too hard for me

### ISSUE THREAD

**Issue by runsys** [mpromonet/webrtc-streamer#716]
root@BPC:/da/work/code/qt/webrtc-streamer-master # make install
[ 11%] Built target civetweb
[ 40%] Built target libv4l2cpp
[ 62%] Built target liblive555helper
[ 66%] Building CXX object CMakeFiles/webrtc-streamer.dir/src/HttpServerRequestHandler.cpp.o
/da/work/code/qt/webrtc-streamer-master/src/HttpServerRequestHandler.cpp:21:10: fatal error: 'prometheus/counter.h' file not found
   21 | #include "prometheus/counter.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /da/work/code/qt/webrtc-streamer-master
*** Error code 1

Stop.
make[1]: stopped in /da/work/code/qt/webrtc-streamer-master
*** Error code 1

Stop.
make: stopped in /da/work/code/qt/webrtc-streamer-master

**Comment by mpromonet** [comment]
Hi @runsys 
This include is part of https://github.com/jupp0r/prometheus-cpp
Best Regards 
Michel
