### ISSUE TITLE
I build work stop at here .i didnot have any solution for this error

### ISSUE THREAD

**Issue by runsys** [mpromonet/webrtc-streamer#717]
root@BPC:/da/work/code/qt/webrtc-streamer-master # make install
[ 11%] Built target civetweb
[ 40%] Built target libv4l2cpp
[ 62%] Built target liblive555helper
[ 66%] Building CXX object CMakeFiles/webrtc-streamer.dir/src/HttpServerRequestHandler.cpp.o
In file included from /da/work/code/qt/webrtc-streamer-master/src/HttpServerRequestHandler.cpp:22:
In file included from /da/work/code/qt/webrtc-streamer-master/src/prometheus/gauge.h:14:
/da/work/code/qt/webrtc-streamer-master/inc/wx/defs.h:62:13: error: "No Target! You should use wx-config program for compilation flags!"
   62 | #           error "No Target! You should use wx-config program for compilation flags!"
      |             ^
In file included from /da/work/code/qt/webrtc-streamer-master/src/HttpServerRequestHandler.cpp:22:
In file included from /da/work/code/qt/webrtc-streamer-master/src/prometheus/gauge.h:18:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/control.h:22:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/window.h:18:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/event.h:22:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/cursor.h:57:
/da/work/code/qt/webrtc-streamer-master/inc/wx/gtk/cursor.h:44:5: error: unknown type name 'GdkCursor'; did you mean 'wxCursor'?
   44 |     GdkCursor *GetCursor() const;
      |     ^~~~~~~~~
      |     wxCursor
/da/work/code/qt/webrtc-streamer-master/inc/wx/gtk/cursor.h:18:24: note: 'wxCursor' declared here
   18 | class WXDLLIMPEXP_CORE wxCursor : public wxCursorBase
      |                        ^
In file included from /da/work/code/qt/webrtc-streamer-master/src/HttpServerRequestHandler.cpp:22:
In file included from /da/work/code/qt/webrtc-streamer-master/src/prometheus/gauge.h:18:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/control.h:22:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/window.h:24:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/colour.h:233:
/da/work/code/qt/webrtc-streamer-master/inc/wx/gtk/colour.h:26:20: error: unknown type name 'GdkColor'
   26 |     wxColour(const GdkColor& gdkColor);
      |                    ^
/da/work/code/qt/webrtc-streamer-master/inc/wx/gtk/colour.h:48:11: error: unknown type name 'GdkColor'
   48 |     const GdkColor *GetColor() const;
      |           ^
In file included from /da/work/code/qt/webrtc-streamer-master/src/HttpServerRequestHandler.cpp:22:
In file included from /da/work/code/qt/webrtc-streamer-master/src/prometheus/gauge.h:18:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/control.h:22:
/da/work/code/qt/webrtc-streamer-master/inc/wx/window.h:1630:13: error: unknown type name 'WXWidget'
 1630 |     virtual WXWidget GetHandle() const = 0;
      |             ^
/da/work/code/qt/webrtc-streamer-master/inc/wx/window.h:1632:34: error: unknown type name 'WXWidget'
 1632 |     virtual void AssociateHandle(WXWidget WXUNUSED(handle)) { }
      |                                  ^
/da/work/code/qt/webrtc-streamer-master/inc/wx/window.h:1849:26: error: field has incomplete type 'wxPalette'
 1849 |     wxPalette            m_palette;
      |                          ^
/da/work/code/qt/webrtc-streamer-master/inc/wx/gdicmn.h:35:28: note: forward declaration of 'wxPalette'
   35 | class WXDLLIMPEXP_FWD_CORE wxPalette;
      |                            ^
In file included from /da/work/code/qt/webrtc-streamer-master/src/HttpServerRequestHandler.cpp:22:
In file included from /da/work/code/qt/webrtc-streamer-master/src/prometheus/gauge.h:18:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/control.h:22:
/da/work/code/qt/webrtc-streamer-master/inc/wx/window.h:1639:15: error: incomplete result type 'wxPalette' in function definition
 1639 |     wxPalette GetPalette() const { return m_palette; }
      |               ^
/da/work/code/qt/webrtc-streamer-master/inc/wx/gdicmn.h:35:28: note: forward declaration of 'wxPalette'
   35 | class WXDLLIMPEXP_FWD_CORE wxPalette;
      |                            ^
In file included from /da/work/code/qt/webrtc-streamer-master/src/HttpServerRequestHandler.cpp:22:
In file included from /da/work/code/qt/webrtc-streamer-master/src/prometheus/gauge.h:18:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/control.h:22:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/window.h:2085:
/da/work/code/qt/webrtc-streamer-master/inc/wx/gtk/window.h:28:30: error: use of undeclared identifier 'GdkWindow'
   28 | WX_DEFINE_EXPORTED_ARRAY_PTR(GdkWindow *, wxArrayGdkWindows);
      |                              ^
/da/work/code/qt/webrtc-streamer-master/inc/wx/gtk/window.h:28:1: error: expected expression
   28 | WX_DEFINE_EXPORTED_ARRAY_PTR(GdkWindow *, wxArrayGdkWindows);
      | ^
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:711:5: note: expanded from macro 'WX_DEFINE_EXPORTED_ARRAY_PTR'
  711 |     WX_DEFINE_EXPORTED_TYPEARRAY_PTR(T, name, wxBaseArrayPtrVoid)
      |     ^
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:499:5: note: expanded from macro 'WX_DEFINE_EXPORTED_TYPEARRAY_PTR'
  499 |     WX_DEFINE_TYPEARRAY_WITH_DECL_PTR(T, name, base, class WXDLLIMPEXP_CORE)
      |     ^
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:544:5: note: expanded from macro 'WX_DEFINE_TYPEARRAY_WITH_DECL_PTR'
  544 |     WX_DEFINE_TYPEARRAY_WITH_DECL(T, name, base, classdecl)
      |     ^
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:529:26: note: expanded from macro 'WX_DEFINE_TYPEARRAY_WITH_DECL'
  529 |     typedef wxBaseArray<T> wxBaseArrayFor##name;                              \
      |                          ^
In file included from /da/work/code/qt/webrtc-streamer-master/src/HttpServerRequestHandler.cpp:22:
In file included from /da/work/code/qt/webrtc-streamer-master/src/prometheus/gauge.h:18:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/control.h:22:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/window.h:2085:
/da/work/code/qt/webrtc-streamer-master/inc/wx/gtk/window.h:28:1: error: base specifier must name a class
   28 | WX_DEFINE_EXPORTED_ARRAY_PTR(GdkWindow *, wxArrayGdkWindows);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:711:5: note: expanded from macro 'WX_DEFINE_EXPORTED_ARRAY_PTR'
  711 |     WX_DEFINE_EXPORTED_TYPEARRAY_PTR(T, name, wxBaseArrayPtrVoid)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:499:5: note: expanded from macro 'WX_DEFINE_EXPORTED_TYPEARRAY_PTR'
  499 |     WX_DEFINE_TYPEARRAY_WITH_DECL_PTR(T, name, base, class WXDLLIMPEXP_CORE)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:544:5: note: expanded from macro 'WX_DEFINE_TYPEARRAY_WITH_DECL_PTR'
  544 |     WX_DEFINE_TYPEARRAY_WITH_DECL(T, name, base, classdecl)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:530:25: note: expanded from macro 'WX_DEFINE_TYPEARRAY_WITH_DECL'
  530 |     class name : public wxBaseArrayFor##name                                  \
      |                  ~~~~~~~^~~~~~~~~~~~~~~~~~~~
<scratch space>:41:1: note: expanded from here
   41 | wxBaseArrayForwxArrayGdkWindows
      | ^
In file included from /da/work/code/qt/webrtc-streamer-master/src/HttpServerRequestHandler.cpp:22:
In file included from /da/work/code/qt/webrtc-streamer-master/src/prometheus/gauge.h:18:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/control.h:22:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/window.h:2085:
/da/work/code/qt/webrtc-streamer-master/inc/wx/gtk/window.h:28:1: error: 'wxArrayGdkWindows::Base' (aka 'int') is not a class, namespace, or enumeration
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:711:5: note: expanded from macro 'WX_DEFINE_EXPORTED_ARRAY_PTR'
  711 |     WX_DEFINE_EXPORTED_TYPEARRAY_PTR(T, name, wxBaseArrayPtrVoid)
      |     ^
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:499:5: note: expanded from macro 'WX_DEFINE_EXPORTED_TYPEARRAY_PTR'
  499 |     WX_DEFINE_TYPEARRAY_WITH_DECL_PTR(T, name, base, class WXDLLIMPEXP_CORE)
      |     ^
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:544:5: note: expanded from macro 'WX_DEFINE_TYPEARRAY_WITH_DECL_PTR'
  544 |     WX_DEFINE_TYPEARRAY_WITH_DECL(T, name, base, classdecl)
      |     ^
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:536:24: note: expanded from macro 'WX_DEFINE_TYPEARRAY_WITH_DECL'
  536 |         name(size_t n, Base::const_reference v) : Base(n, v) { }              \
      |                        ^
In file included from /da/work/code/qt/webrtc-streamer-master/src/HttpServerRequestHandler.cpp:22:
In file included from /da/work/code/qt/webrtc-streamer-master/src/prometheus/gauge.h:18:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/control.h:22:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/window.h:2085:
/da/work/code/qt/webrtc-streamer-master/inc/wx/gtk/window.h:28:1: error: constructor initializer 'Base' (aka 'int') does not name a class
   28 | WX_DEFINE_EXPORTED_ARRAY_PTR(GdkWindow *, wxArrayGdkWindows);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:711:5: note: expanded from macro 'WX_DEFINE_EXPORTED_ARRAY_PTR'
  711 |     WX_DEFINE_EXPORTED_TYPEARRAY_PTR(T, name, wxBaseArrayPtrVoid)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:499:5: note: expanded from macro 'WX_DEFINE_EXPORTED_TYPEARRAY_PTR'
  499 |     WX_DEFINE_TYPEARRAY_WITH_DECL_PTR(T, name, base, class WXDLLIMPEXP_CORE)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:544:5: note: expanded from macro 'WX_DEFINE_TYPEARRAY_WITH_DECL_PTR'
  544 |     WX_DEFINE_TYPEARRAY_WITH_DECL(T, name, base, classdecl)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:534:18: note: expanded from macro 'WX_DEFINE_TYPEARRAY_WITH_DECL'
  534 |         name() : Base() { }                                                   \
      |                  ^~~~
In file included from /da/work/code/qt/webrtc-streamer-master/src/HttpServerRequestHandler.cpp:22:
In file included from /da/work/code/qt/webrtc-streamer-master/src/prometheus/gauge.h:18:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/control.h:22:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/window.h:2085:
/da/work/code/qt/webrtc-streamer-master/inc/wx/gtk/window.h:28:1: error: constructor initializer 'Base' (aka 'int') does not name a class
   28 | WX_DEFINE_EXPORTED_ARRAY_PTR(GdkWindow *, wxArrayGdkWindows);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:711:5: note: expanded from macro 'WX_DEFINE_EXPORTED_ARRAY_PTR'
  711 |     WX_DEFINE_EXPORTED_TYPEARRAY_PTR(T, name, wxBaseArrayPtrVoid)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:499:5: note: expanded from macro 'WX_DEFINE_EXPORTED_TYPEARRAY_PTR'
  499 |     WX_DEFINE_TYPEARRAY_WITH_DECL_PTR(T, name, base, class WXDLLIMPEXP_CORE)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:544:5: note: expanded from macro 'WX_DEFINE_TYPEARRAY_WITH_DECL_PTR'
  544 |     WX_DEFINE_TYPEARRAY_WITH_DECL(T, name, base, classdecl)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:535:35: note: expanded from macro 'WX_DEFINE_TYPEARRAY_WITH_DECL'
  535 |         explicit name(size_t n) : Base(n) { }                                 \
      |                                   ^~~~
In file included from /da/work/code/qt/webrtc-streamer-master/src/HttpServerRequestHandler.cpp:22:
In file included from /da/work/code/qt/webrtc-streamer-master/src/prometheus/gauge.h:18:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/control.h:22:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/window.h:2085:
/da/work/code/qt/webrtc-streamer-master/inc/wx/gtk/window.h:28:1: error: constructor initializer 'Base' (aka 'int') does not name a class
   28 | WX_DEFINE_EXPORTED_ARRAY_PTR(GdkWindow *, wxArrayGdkWindows);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:711:5: note: expanded from macro 'WX_DEFINE_EXPORTED_ARRAY_PTR'
  711 |     WX_DEFINE_EXPORTED_TYPEARRAY_PTR(T, name, wxBaseArrayPtrVoid)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:499:5: note: expanded from macro 'WX_DEFINE_EXPORTED_TYPEARRAY_PTR'
  499 |     WX_DEFINE_TYPEARRAY_WITH_DECL_PTR(T, name, base, class WXDLLIMPEXP_CORE)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:544:5: note: expanded from macro 'WX_DEFINE_TYPEARRAY_WITH_DECL_PTR'
  544 |     WX_DEFINE_TYPEARRAY_WITH_DECL(T, name, base, classdecl)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:536:51: note: expanded from macro 'WX_DEFINE_TYPEARRAY_WITH_DECL'
  536 |         name(size_t n, Base::const_reference v) : Base(n, v) { }              \
      |                                                   ^~~~
In file included from /da/work/code/qt/webrtc-streamer-master/src/HttpServerRequestHandler.cpp:22:
In file included from /da/work/code/qt/webrtc-streamer-master/src/prometheus/gauge.h:18:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/control.h:22:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/window.h:2085:
/da/work/code/qt/webrtc-streamer-master/inc/wx/gtk/window.h:28:1: error: constructor initializer 'Base' (aka 'int') does not name a class
   28 | WX_DEFINE_EXPORTED_ARRAY_PTR(GdkWindow *, wxArrayGdkWindows);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:711:5: note: expanded from macro 'WX_DEFINE_EXPORTED_ARRAY_PTR'
  711 |     WX_DEFINE_EXPORTED_TYPEARRAY_PTR(T, name, wxBaseArrayPtrVoid)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:499:5: note: expanded from macro 'WX_DEFINE_EXPORTED_TYPEARRAY_PTR'
  499 |     WX_DEFINE_TYPEARRAY_WITH_DECL_PTR(T, name, base, class WXDLLIMPEXP_CORE)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:544:5: note: expanded from macro 'WX_DEFINE_TYPEARRAY_WITH_DECL_PTR'
  544 |     WX_DEFINE_TYPEARRAY_WITH_DECL(T, name, base, classdecl)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:538:57: note: expanded from macro 'WX_DEFINE_TYPEARRAY_WITH_DECL'
  538 |         name(InputIterator first, InputIterator last) : Base(first, last) { } \
      |                                                         ^~~~
In file included from /da/work/code/qt/webrtc-streamer-master/src/HttpServerRequestHandler.cpp:22:
In file included from /da/work/code/qt/webrtc-streamer-master/src/prometheus/gauge.h:18:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/control.h:22:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/window.h:2085:
/da/work/code/qt/webrtc-streamer-master/inc/wx/gtk/window.h:28:1: error: constructor initializer 'Base' (aka 'int') does not name a class
   28 | WX_DEFINE_EXPORTED_ARRAY_PTR(GdkWindow *, wxArrayGdkWindows);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:711:5: note: expanded from macro 'WX_DEFINE_EXPORTED_ARRAY_PTR'
  711 |     WX_DEFINE_EXPORTED_TYPEARRAY_PTR(T, name, wxBaseArrayPtrVoid)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:499:5: note: expanded from macro 'WX_DEFINE_EXPORTED_TYPEARRAY_PTR'
  499 |     WX_DEFINE_TYPEARRAY_WITH_DECL_PTR(T, name, base, class WXDLLIMPEXP_CORE)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:544:5: note: expanded from macro 'WX_DEFINE_TYPEARRAY_WITH_DECL_PTR'
  544 |     WX_DEFINE_TYPEARRAY_WITH_DECL(T, name, base, classdecl)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:539:9: note: expanded from macro 'WX_DEFINE_TYPEARRAY_WITH_DECL'
  539 |         WX_DEFINE_CTOR_FROM_INIT_LIST(T, name, base, classdecl)               \
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/da/work/code/qt/webrtc-streamer-master/inc/wx/dynarray.h:510:51: note: expanded from macro 'WX_DEFINE_CTOR_FROM_INIT_LIST'
  510 |             name(std::initializer_list<U> list) : Base(list.begin(), list.end()) { }
      |                                                   ^~~~
In file included from /da/work/code/qt/webrtc-streamer-master/src/HttpServerRequestHandler.cpp:22:
In file included from /da/work/code/qt/webrtc-streamer-master/src/prometheus/gauge.h:18:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/control.h:22:
In file included from /da/work/code/qt/webrtc-streamer-master/inc/wx/window.h:2085:
/da/work/code/qt/webrtc-streamer-master/inc/wx/gtk/window.h:141:13: error: unknown type name 'WXWidget'
  141 |     virtual WXWidget GetHandle() const wxOVERRIDE { return m_widget; }
      |             ^
/da/work/code/qt/webrtc-streamer-master/inc/wx/gtk/window.h:171:13: error: unknown type name 'GtkWidget'
  171 |     virtual GtkWidget* GetConnectWidget();
      |             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
*** Error code 1

Stop.
make[2]: stopped in /da/work/code/qt/webrtc-streamer-master
*** Error code 1

Stop.

**Comment by mpromonet** [comment]
Hi @runsys 
I don't know what is wx-config, it seems you mixed differents packages....
Best Regards,
Michel.
