### ISSUE TITLE
Screen flickering or distorted display

### ISSUE THREAD

**Issue by 3-7k** [mpromonet/webrtc-streamer#718]
When I use the -o parameter, the screen often flickers and turns green, but this doesn't happen when I don't use the -o parameter. How can I solve this issue?

<img width="367" alt="image" src="https://github.com/user-attachments/assets/99c8eb26-64a6-4fa0-96c7-6937c5588e16">

<img width="1135" alt="image" src="https://github.com/user-attachments/assets/011f6a5d-957c-48e1-b0f4-f03fb599482c">

**Comment by mpromonet** [comment]
Hi,

It might be SPS/PPS parsing ?

Best Regards,
Michel.

**Comment by BlockCnFuture** [comment]
> Hi, 你好，
> 
> It might be SPS/PPS parsing ?可能是SPS/PPS解析？
> 
> Best Regards, 此致， Michel. 米歇尔.

I have the same problem, is there a solution? Thanks

**Comment by mpromonet** [comment]
Hi @BlockCnFuture 

You can look of buffer in https://github.com/mpromonet/webrtc-streamer/blob/master/inc/livevideosource.h#L107 and look how are processed SPS/PPS and buffer send in https://github.com/mpromonet/webrtc-streamer/blob/master/inc/livevideosource.h#L157C21-L157C28

Best Regards,
Michel.

**Comment by 3-7k** [comment]
@mpromonet thanks for your help

**Comment by flowersBloom826** [comment]
@3-7k Boss, then how to solve it?
