### ISSUE TITLE
./webrtc-streamer: error while loading shared libraries: libSM.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Songgexnl** [mpromonet/webrtc-streamer#723]
![image](https://github.com/user-attachments/assets/67c28e12-e301-45a7-80f8-d11e9e38ef59)
Download this, and then run it in the x86_64 x86_64 x86_64 GNU/Linux environment and report an error./webrtc-streamer: error while loading shared libraries: libSM.so.6: cannot open shared object file: No such file or directory
;and I have installed
![image](https://github.com/user-attachments/assets/f72f35b7-ed4e-496f-8ed4-d44f6462f5ee)
Execute ./webrtc-streamer
Still reporting error error while loading shared libraries: libSM.so.6: cannot open shared object file: No such file or directory

**Comment by mpromonet** [comment]
Hi @Songgexnl 
Binaries for Linux are built on Ubuntu 24.04.
Best Regards 
Michel

**Comment by Songgexnl** [comment]
> Hi @Songgexnl Binaries for Linux are built on Ubuntu 24.04. Best Regards Michel

Do you have this installation package for x86_64 x86_64 GNU/Linux environment

**Comment by mpromonet** [comment]
Hi @Songgexnl 

Did you look to https://amalgjose.com/2020/03/14/importerror-libsm-so-6-cannot-open-shared-object-file-no-such-file-or-directory/ ?

Best Regards,
Michel.
