### ISSUE TITLE
When playing RTSP monitoring, the screen occasionally freezes, and the reason for the original monitoring stream has been ruled out.

### ISSUE THREAD

**Issue by bijianhua123** [mpromonet/webrtc-streamer#731]

**Comment by mpromonet** [comment]
Hi @bijianhua123 

Thanks for your issue, but if you like some answer you need to clarify.... what is RTSP monitoring...

Best Regards,
Michel.

**Comment by bijianhua123** [comment]
Hikvision surveillance video stream，It is RTSP type

**Comment by mpromonet** [comment]
Hi @bijianhua123 

Wireshark or tcpdump may helps you.

Best Regards 
Michel

**Comment by yangjieshao** [comment]
> surveillance

直连设备还是通过isc平台？
通过isc平台好像是有问题，isc返回的rtsp地址是加密后的，是有有效期的，理论上只要连上了就可以一直放
但是不知道为什么 用webrtc-streamer，地址过期后就会断开

**Comment by bijianhua123** [comment]
isc platform。Have you also encountered this problem? Is there any solution? @yangjieshao

**Comment by yangjieshao** [comment]
> isc platform。Have you also encountered this problem? Is there any solution? @yangjieshao

https://github.com/mpromonet/webrtc-streamer/issues/654

最终是和业主协商，直连设备才解决的
It was ultimately resolved through negotiation with the property owner and direct connection to the equipment

**Comment by zhuya1996** [comment]
需要自己编译的webrtc 改里面代码 就解决了 我也遇到了

**Comment by a9010028** [comment]
@zhuya1996 請問您是修改哪邊東西呢 是否能分享一下,感謝(May I ask which part you modified? Would you mind sharing it with me? Thank you!)

**Comment by zhuya1996** [comment]
> [@zhuya1996](https://github.com/zhuya1996) 請問您是修改哪邊東西呢 是否能分享一下,感謝(May I ask which part you modified? Would you mind sharing it with me? Thank you!)

Need to add my QQ 2308193190 Not free

**Comment by hansongLove** [comment]
> isc平台。你也遇到过这个问题吗？有什么解决办法吗？[@yangjieshao](https://github.com/yangjieshao)

Have you solved this problem? Can you help me with it? Thank you.

**Comment by zhuya1996** [comment]
你是中国人吧，是不是在csdn上已经问过我了



---Original---
From: ***@***.***&gt;
Date: Tue, Jul 22, 2025 14:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mpromonet/webrtc-streamer] When playing RTSP monitoring, thescreen occasionally freezes, and the reason for the original monitoring streamhas been ruled out. (Issue #731)


hansongLove left a comment (mpromonet/webrtc-streamer#731)
  
@zhuya1996请问您是修改哪边东西呢 是否能分享一下，谢谢（请问您修改了哪一部分？您介意与我分享吗？谢谢！）
  
Have you solved this problem? Can you help me with it? Thank you.
