### ISSUE TITLE
how to set external STUN server?

### ISSUE THREAD

**Issue by yangjieshao** [mpromonet/webrtc-streamer#734]
i try to set external STUN server 
my command:
` .\webrtc-streamer.exe -s81.68.179.47`
![image](https://github.com/user-attachments/assets/b6dbb1ba-96e3-4fd2-b214-8a7fd213d833)

![image](https://github.com/user-attachments/assets/764b01dc-88c9-4577-a28f-cd4fc18715e7)

.\webrtc-streamer.exe -s 81.68.179.47
![image](https://github.com/user-attachments/assets/e5f54a18-1ac7-4640-8473-8ade2eb62a8b)

![image](https://github.com/user-attachments/assets/bfa65945-930b-4271-ae28-e997a8a51fd0)

**Comment by mpromonet** [comment]
Hi @yangjieshao 

Just ```webrtc-streamer.exe -s81.68.179.47:3478``` without space between -s and address.

Best Regards,
Michel.

**Comment by yangjieshao** [comment]
thanks
add quote is ok
