### ISSUE TITLE
503 service unavailable

### ISSUE THREAD

**Issue by maheshkumarg** [mpromonet/webrtc-streamer#74]
Hi,
Thanks for providing this project to stream an RTSP video. 

I get this error few times, please let me know how can i resolve this issue?

**Comment by mpromonet** [comment]
Hi maheshkumarg,
Maybe you should give a little more details ? 
Are you speaking about an RTSP code, an HTTP code ? using the live demo ? what is the method that receive this answer....
Best Regards,
Michel.
