### ISSUE TITLE
How to change encoder setting?

### ISSUE THREAD

**Issue by traw** [mpromonet/webrtc-streamer#80]
How can we change encoder setting whilst streaming local webcam?

**Comment by mpromonet** [comment]
Hi traw,
You can use v4l2-ctl to change the webcam setting, however it is highly probable that your capture device will answer BUSY to this command, till the capture device is used by the WebRTC SDK.
Best Regards,
Michel.

**Comment by traw** [comment]
ok, I was asking about audio/video codec like vp8, vp9, g711 etc.

**Comment by mpromonet** [comment]
You can do this modifying the SDP you get.
There is lots of article about SDP munging https://bloggeek.me/webrtc-sdp-munging-prohibited/

**Comment by traw** [comment]
does that mean I may need to modify `OnSuccess` in either `SetSessionDescriptionObserver` or `CreateSessionDescriptionObserver` class located in `PeerConnectionManager.h`.
Am I getting it right?

**Comment by mpromonet** [comment]
Hi,
I guess you should rather modify the JavaScript to modify the sdp receive as call answer before giving it to setRemoteDescription.
Best regards
Michel
