### ISSUE TITLE
Stream /dev/v4l/by-id/usb-INOGENI_2633-INOGENI_4K2USB3_01C92633-video-index0 device

### ISSUE THREAD

**Issue by gaspa85** [mpromonet/webrtc-streamer#87]
Hi,

is possibile to stream /dev/v4l/by-id/usb-INOGENI_2633-INOGENI_4K2USB3_01C92633-video-index0?

i have try to start server with this command

./webrtc-streamer -vvv /dev/v4l/by-id/usb-INOGENI_2633-INOGENI_4K2USB3_01C92633-video-index0

and after open browser with this url

http://10.0.2.86:8000/webrtcstream.html?/dev/v4l/by-id/usb-INOGENI_2633-INOGENI_4K2USB3_01C92633-video-index0

but I can not see the video stream on the browser.

The server return this log
[log.txt](https://github.com/mpromonet/webrtc-streamer/files/1521036/log.txt)

thanks for your times

Marco Gasparini

**Comment by mpromonet** [comment]
Hi Marko,
You don't need to give the url to capture, webrtc-streamer enumerate using WebRTC SDK available capture device.
You can get the list using http://10.0.2.86:8000/getVideoDeviceList.
Next should should be able to display http://10.0.2.86:8000/webrtcstream.html?<with the name of your device> or http://10.0.2.86:8000/webrtcstream.html?video=<with the name of your device>.
Best Regards,
Michel.

**Comment by gaspa85** [comment]
thanks so mutch Michel, find periferal and start stream.
Marco G.
