### ISSUE TITLE
Error when building on Raspberry Pi 

### ISSUE THREAD

**Issue by laeknishendr** [mpromonet/webrtc-streamer#88]
Following the tutorial found in https://www.raspberrypi.org/forums/viewtopic.php?t=186271, and after getting all the previous steps executed without problems, when getting and building the WebRTC for Raspberry Pi, I get the following error: 

pi@raspberrypi:home/pi/webrtc $ GYP_DEFINES="target_arch=arm"
pi@raspberrypi:home/pi/webrtc $ fetch --no-history webrtc
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://webrtc.googlesource.com/src.git",
    "managed": False,
    "name": "src",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --no-history --with_branch_heads
Error: Command '/usr/bin/python src/third_party/binutils/download.py' returned non-zero exit status 1 in /home/pi/webrtcTraceback (most recent call last):
  File "/home/pi/depot_tools/fetch.py", line 301, in <module>
    sys.exit(main())
  File "/home/pi/depot_tools/fetch.py", line 296, in main
    return run(options, spec, root)
  File "/home/pi/depot_tools/fetch.py", line 290, in run
    return checkout.init()
  File "/home/pi/depot_tools/fetch.py", line 133, in init
    self.run_gclient(*sync_cmd)
  File "/home/pi/depot_tools/fetch.py", line 78, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/home/pi/depot_tools/fetch.py", line 68, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--no-history', '--with_branch_heads')' returned non-zero exit status 2

What should I do?

**Comment by mpromonet** [comment]
Hi,
The webrtc repository is quite big, several GB, you need space and memory.
If it timeout, you can continue running `gclient sync`
Best Regards,
Michel.
