### ISSUE TITLE
FEATURE: CMake support for better dependency management 

### ISSUE THREAD

**Issue by traw** [mpromonet/webrtc-streamer#93]
CMake support for better dependency management and for IDE Supports

**Comment by mpromonet** [comment]
Hi traw,
This is far from my priorities.
I saw some nice work to build WbeRTC using cmake https://github.com/aisouard/libwebrtc, maybe you can inspire from it.
Best Regards,
Michel.

**Comment by traw** [comment]
I'm giving it a try, if I succeed then I'll submit here

**Comment by mpromonet** [comment]
Hi traw,
Finally I did it for windows support.
Best Regards,
Michel.
